<div style="background: linear-gradient(135deg, #1a237e 0%, #0d47a1 50%, #01579b 100%); padding: 48px 40px; border-radius: 12px; color: white; font-family: 'Segoe UI', sans-serif; text-align: center;">

<h1 style="font-size: 2.6em; font-weight: 800; margin: 0 0 8px 0; letter-spacing: 1px;">📘 NumPy Array Creation</h1>
<p style="font-size: 1.2em; margin: 0 0 32px 0; opacity: 0.85;">Complete Guide — Examples · Edge Cases · Interview Questions</p>

<hr style="border: 1px solid rgba(255,255,255,0.3); margin-bottom: 28px;">

<table style="margin: 0 auto; border-collapse: collapse; color: white; font-size: 0.95em;">
<tr>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Author</b>
  Harsh Thakur
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">GitHub</b>
  <a href="https://github.com/HarshAIWorks" style="color:#90CAF9;">HarshAIWorks</a>
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topic</b>
  NumPy Fundamentals
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Difficulty</b>
  Beginner → Intermediate
</td>
<td style="padding: 8px 28px;">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">No of topics</b>
  ~8
</td>
</tr>
</table>

<hr style="border: 1px solid rgba(255,255,255,0.3); margin: 28px 0 16px 0;">
<p style="font-size: 0.85em; opacity: 0.65; margin: 0;">Last Updated: July 2026&nbsp;|&nbsp;Python &nbsp;|&nbsp;NumPy &nbsp;|&nbsp;Part of the AI Engineer Roadmap</p>
</div>

---

## 📋 Table of Contents

| # | Topic | Key Sub-topics |
|---|-------|----------------|
| 1 | [np.array()](#1-nparray) | 1D/2D/3D, dtype, strings, upcasting, special cases, dict/set, None vs nan, copying |
| 2 | [np.arange()](#2-nparange) | stop, start/stop/step, negative step, float step, dtype |
| 3 | [np.linspace()](#3-nplinspace) | num, endpoint, retstep, dtype + np.logspace() |
| 4 | [np.zeros()](#4-npzeros) | shapes, dtype, empty dims + np.empty() |
| 5 | [np.ones()](#5-npones) | shapes, dtype |
| 6 | [np.full()](#6-npfull) | shapes, dtype, fill with nan |
| 7 | [np.eye() & np.identity()](#7-npeye--npidentity) | identity matrix, rectangular, diagonal offsets |
| 8 | [np.random](#8-nprandom) | rand, randn, randint, choice, seed, shuffle, permutation |
| — | [Interview Questions](#interview-questions) | Beginner → Advanced |
| — | [Practice Questions](#practice-questions) | Easy → Hard |
| — | [Mini Challenge](#mini-challenge) | Combined exercise |
| — | [Summary](#summary) | Key takeaways & function reference |
| — | [References](#references) | Docs & further reading |

---

## 🎯 Learning Objectives

After completing this notebook you will be able to:

✔ Create NumPy arrays from Python lists, tuples, ranges, and other sequences using the most common constructors  
✔ Understand how NumPy determines and promotes data types — upcasting, unicode sizing, object dtype  
✔ Choose the right array-creation function (`np.array`, `np.arange`, `np.linspace`, `np.zeros`, `np.ones`, `np.full`, `np.eye`) for a given task  
✔ Use `np.random` functions to generate controlled and reproducible random datasets  
✔ Anticipate common pitfalls: truncation, empty arrays, in-place vs copy, object dtype for dicts/sets  

---

In [4]:
# Importing numpy as np
import numpy as np

<a id="1-nparray"></a>

<div style="background:#1E2235; border-radius:10px; padding:18px 24px; margin:32px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:16px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="color:#FFFFFF; font-size:1.4em; font-weight:800; min-width:32px; font-family:'Segoe UI',sans-serif;">1.</span>
<div style="display:flex; align-items:center; gap:8px; flex-wrap:wrap;">
<code style="background:#2A2F47; color:#E8A84A; font-size:1.15em; font-weight:700; padding:5px 14px; border-radius:6px; letter-spacing:0.3px; font-family:'Courier New',monospace;">np.array()</code>
</div>
</div>---




> **The universal constructor.** Converts any sequence-like object — list, tuple, range, another array — into a NumPy `ndarray`.

**Syntax:**
```python
np.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
```

| Parameter | Description | Default |
|-----------|-------------|---------|
| `object` | Input data (list, tuple, array…) | Required |
| `dtype` | Override the data type | Auto-detected |
| `copy` | Create a new array or share memory | `True` |
| `ndmin` | Minimum number of dimensions | `0` |

In [7]:
# 1-D
a =np.array([1,2,3])
a


array([1, 2, 3])

In [ ]:
# 2-D and 3-D
b= np.array([[1,2,3],[4,5,6]])

c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("2-D array: ",b)
print("3-D array: ",c) #3-D creates like- make list of list and each list have another lists 

2-D array:  [[1 2 3]
 [4 5 6]]
3-D array:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;">
<span style="font-size:1.1em;">💡</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Tip</span>
</div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
Think of dimensions as nesting depth:<br>plain list → 1-D &nbsp;|&nbsp; list of lists → 2-D &nbsp;|&nbsp; list of lists of lists → 3-D
</div>
</div>

<div style="border:2px solid #16A34A; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#15803D; padding:8px 16px; display:flex; align-items:center; gap:8px;">
<span style="font-size:1.1em;">ℹ️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Info — dtype argument</span>
</div>
<div style="background:#F0FDF4; padding:14px 18px; color:#14532D; font-size:0.97em; line-height:1.6;">
Pass dtype as a string (<code>'int32'</code>, <code>'float64'</code>) or a NumPy type (<code>np.float32</code>). NumPy converts all elements at creation time.
</div>
</div>

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 1) With Datatype argument</span></div>


In [ ]:

d= np.array((1,2,3),dtype=float)
d

array([1., 2., 3.])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 2) Using String items</span></div>

<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;">
<span style="font-size:1.1em;">💡</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Tip — Unicode dtype format</span>
</div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
<code>&lt;U6</code> means: <b>little-endian Unicode string, max 6 characters per element</b>. NumPy sizes it automatically to the longest string.
</div>
</div>

In [ ]:

s= np.array(['apple', 'banana', 'mango'])

print(s)
print(s.dtype) # <U6
               # U → Unicode String 6 → maximum length is 6 characters
               # NumPy automatically picks the longest string length.

['apple' 'banana' 'mango']
<U6


In [26]:
arr = np.array(['AI', 'Machine Learning', 'Deep Learning'])
print(arr.dtype) # <U16 Because:"Machine Learning" contains 16 characters.

<U16


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 3) With Fixed Length Strings</span></div>
NumPy stores strings in fixed-size memory blocks.

In [29]:
arr = np.array(['cat','elephant'])
print(arr.dtype) #<U8 Since elephant has 8 letters. 
                 #All elements reserve space for 8 characters.
                # Memory becomes predictable.
                #This is useful internally for fast operations.

<U8


<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;">
<span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Warning — String Truncation</span>
</div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
If <code>dtype='U4'</code> is shorter than your data, NumPy <b>silently truncates</b> strings. Always verify output when fixing string width manually.
</div>
</div>

if dtype length is smaller?

In [33]:
array= np.array(["machine","learning"],dtype='U4')
array # list items- ['mach' 'lear'] - Strings get truncated.


array(['mach', 'lear'], dtype='<U4')

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 4) Explicit String Types</span></div>
Unicode and ASCII

In [ ]:
arr1 = np.array(['python','numpy'],dtype='U10') #Unicode
arr2 = np.array(['python','numpy'],dtype='S10') #ASCII
print(arr1) #ASCII stores bytes.
print(arr2) #Unicode is preferred.
            

['python' 'numpy']
[b'python' b'numpy']


Dtype selection for mix values

In [ ]:
mix= np.array(["apple", "banana",4.5,2])
print(mix.dtype) # <U32- Numpy forces one dtype, so all can be converted in a single unicode string.
                 #U32> means fixed width(32chrtr) unicode string.
                 #it doesn't pick longest element- banana, instead numpy allocates safe default size(32) when prompting mixed datatypes

<U32


<h4 align="left" style="color:green">5) AI Engineer Perspective

Although AI models work mainly with numerical arrays, string arrays are common in: NLP

In [ ]:
#before tokenization
np.array([
'good movie',
'bad movie',
'excellent film'
])

#Labels
labels = np.array([
'cat',
'dog',
'bird'
])
 #Dataset Metadata
 files = np.array([
'img001.jpg',
'img002.jpg',
'img003.jpg'
])

array(['good movie', 'bad movie', 'excellent film'], dtype='<U14')

<div style="background:#166534; border-radius:8px; padding:10px 18px; margin:20px 0 10px 0; display:flex; align-items:center; gap:10px; font-family:'Segoe UI',sans-serif;"><span style="color:#4ADE80; font-size:1.3em;">▶</span><span style="color:#FFFFFF; font-weight:700; font-size:1.08em;">6) Exceptional, Special, and Error Cases</span></div>

---
### 6️⃣ Upcasting (Type Promotion)

NumPy enforces a **single dtype** per array. When you mix types, it promotes to the most capable type:

`bool` → `int` → `float` → `complex` → `str` → `object`

 Int + float ---> float items and type

In [40]:
arra=np.array([1,2.5,3])
print(arra,arra.dtype)

[1.  2.5 3. ] float64


Int + Float + Complex --> Complex items and Datatypes

In [43]:
arrb= np.array([1,2,3.5,4.0,2+3j])
print(arrb,arrb.dtype)

[1. +0.j 2. +0.j 3.5+0.j 4. +0.j 2. +3.j] complex128


Boolean with Numbers - Number Items and number type

True -- 1
False -- 0


In [45]:
arrc= np.array([1,2,True])
print(arrc,arrc.dtype)

[1 2 1] int64


---
### ⚡ Special Cases

Empty Array - by default (float64)

In [47]:
emp= np.array([])
print(emp.dtype)

float64


Scalar Instead of Sequence - 0-D shape

In [64]:
scalar1=np.array("hello")
scalar2=np.array(8)
print(scalar1,scalar1.shape)
print(scalar2,scalar2.shape)

hello ()
8 ()


<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;">
<span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Warning — Intentional error cell below</span>
</div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
The next cell contains a <b>deliberate syntax error</b> (<code>1.2.3</code> is not valid Python) to demonstrate what happens with malformed data. This error is intentional — a teaching example.
</div>
</div>

Nested Lists with Different Lengths ⚠️

In [65]:
np.array([[1.2],[1.2.3]])

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2754248903.py, line 1)

---
### 7️⃣ Dictionary and Set — Important AI Engineer Notes

Dictionaries and sets passed directly to `np.array()` are treated as a **single Python object** (0-D array, `dtype=object`). You must iterate their keys/values/items explicitly.

<div style="border:2px solid #8B5CF6; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#7C3AED; padding:8px 16px; display:flex; align-items:center; gap:8px;">
<span style="font-size:1.1em;">🤖</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">AI Insight</span>
</div>
<div style="background:#F5F3FF; padding:14px 18px; color:#3B0764; font-size:0.97em; line-height:1.6;">
In ML pipelines, feature dictionaries (<code>{feature: value}</code>) are common. Always extract values with <code>list(d.values())</code> before passing to NumPy — never pass the dict directly.
</div>
</div>

Dictionary inside - 0-D array

In [ ]:
dictionary = np.array({
    'Name': 'Harsh',
    'class': 10,
    'age' : 16
})
print(dictionary) #NumPy treats the entire dictionary as a single Python object, not as multiple elements.
                  #Shape: 0-D

array({'Name': 'Harsh', 'class': 10, 'age': 16}, dtype=object)

Creating an array from dictionary keys

In [71]:
dic = {
    'Name': 'Harsh',
    'class': 10,
    'age' : 16
}
keys= np.array(list(dic.keys())) #let create a list of items comes from keys- .keys() give all keys
print(keys)

['Name' 'class' 'age']


Creating an array from dictionary values

In [74]:
values= np.array(list(dic.values()))
print(values)

['Harsh' '10' '16']


Creating an array from dictionary items

In [76]:
items= np.array(list(dic.items()))
print(items)

[['Name' 'Harsh']
 ['class' '10']
 ['age' '16']]


<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;">
<span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Warning — Sets are Unordered</span>
</div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
Sets have <b>no guaranteed element order</b>. Converting a set to a NumPy array may produce different orderings between runs. Sort after converting if order matters: <code>np.sort(np.array(list(my_set)))</code>.
</div>
</div>

Set inside

In [78]:
sets= np.array({1,3,5})
print(sets)
print(sets.dtype)# Object: A set is considered one Python object. as whole inside() as we checkd in scalar case

{1, 3, 5}
object


NumPy does not iterate over it automatically. // need to convt it into a list using #casting

In [90]:
set= {1,3,5}
new_set= np.array(list(set))# keep in mind put sets in list() not old array- np.array({1,2,3}) as its an object as whole and obj cant be iterate
print(new_set) # sets are unordered so after next clicks order may change 

[1 3 5]


---
### 8️⃣ `None` vs `np.nan`

| | `None` | `np.nan` |
|--|--------|----------|
| Python type | `NoneType` object | `float` |
| NumPy dtype when mixed with numbers | forces `object` | stays `float64` |
| Math operations | raises `TypeError` | propagates `nan` |
| Best used for | non-numeric missing data | numeric missing data in ML |

<div style="border:2px solid #8B5CF6; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#7C3AED; padding:8px 16px; display:flex; align-items:center; gap:8px;">
<span style="font-size:1.1em;">🤖</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">AI Insight — Missing Data in ML</span>
</div>
<div style="background:#F5F3FF; padding:14px 18px; color:#3B0764; font-size:0.97em; line-height:1.6;">
Always prefer <code>np.nan</code> over <code>None</code> for missing numeric values. pandas and scikit-learn detect and handle <code>np.nan</code> efficiently. Using <code>None</code> forces <code>dtype=object</code>, disabling vectorised computation.
</div>
</div>

In [91]:
arr = np.array([1, 2, None])

print(arr)
print(arr.dtype)

[1 2 None]
object


In [ ]:
arr = np.array([1, 2, np.nan])

print(arr)
print(arr.dtype) # float output 

[ 1.  2. nan]
float64


---
### 9️⃣ Copying an Existing NumPy Array

By default, `np.array(existing_array)` makes a **deep copy** — modifying the original will not affect the copy.  
Setting `copy=False` allows both variables to share the same memory block (a view).

In [ ]:
old= np.array(["hello",1,5.0])
new= np.array(old)
print(new) #upcasting: array prioroty- array items

['hello' '1' '5.0']


Are both same objects?

In [95]:
old is new

False

Any change in old will not affect new one

In [96]:
old[0]=100
print(old)
print(new)

['100' '1' '5.0']
['hello' '1' '5.0']


Copy=False

In [ ]:
#because copy = true by default parameter 
c=np.array([1,20,"good"])
d=np.array(c, copy=False)
c is d # now chnages also happen in another one

True

<a id="1-nparray"></a>

<div style="background:#1E2235; border-radius:10px; padding:18px 24px; margin:32px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:16px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="color:#FFFFFF; font-size:1.4em; font-weight:800; min-width:32px; font-family:'Segoe UI',sans-serif;">2.</span>
<div style="display:flex; align-items:center; gap:8px; flex-wrap:wrap;">
<code style="background:#2A2F47; color:#E8A84A; font-size:1.15em; font-weight:700; padding:5px 14px; border-radius:6px; letter-spacing:0.3px; font-family:'Courier New',monospace;">np.arange()</code>
</div>
</div>------




> **NumPy's version of Python's built-in `range()`** — returns an `ndarray` and supports float steps.

**Syntax:**
```python
np.arange([start,] stop[, step], dtype=None)
```

| Parameter | Description | Default |
|-----------|-------------|---------|
| `start` | Starting value (included) | `0` |
| `stop` | Ending value (**excluded**) | Required |
| `step` | Spacing between values (cannot be 0) | `1` |
| `dtype` | Override data type | Auto |

Creates a NumPy array with evenly spaced values using a fixed step.

<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;">
<span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Note — Syntax illustration cell</span>
</div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
The code cell below assigns a parameter-signature string to a variable for illustration. It raises a <code>SyntaxError</code> as written — this is intentional; it is a syntax reference, not runnable code.
</div>
</div>

In [ ]:
syntax= np.arange([start,] stop[, step], dtype=None)

<h4>1) Only Stop

In [ ]:
range= np.arange(5)
print(range)

<h4> 2) start, stop, and step  ----> step can't be 0

In [5]:
range1= np.arange(1,20,2)
print(range1)

[ 1  3  5  7  9 11 13 15 17 19]


<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;">
<span style="font-size:1.1em;">💡</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Tip — Direction Rules</span>
</div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
<ul style='margin:4px 0 0 0;padding-left:18px;'><li><code>start &lt; stop</code> with <b>positive step</b> → ascending array</li><li><code>start &gt; stop</code> with <b>negative step</b> → descending array</li><li>Mismatched direction → <b>empty array <code>[]</code></b></li></ul>
</div>
</div>

<h4> 3) Negative Step      //reverse count

In [ ]:
range2= np.arange(1,20,-2) # if start should be small from stop -- result: empty list[]
print(range2)  

[]


In [10]:
range3=np.arange(20,0,-2)
print(range3)

[20 18 16 14 12 10  8  6  4  2]


4. Float Step 

<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;">
<span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Warning — Float Step Precision</span>
</div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
Floating-point arithmetic can cause <b>unexpected extra or missing elements</b> with float steps. Prefer <code>np.linspace()</code> when you need an exact element count from a float range.
</div>
</div>

In [12]:
range4=np.arange(0,10,0.2)
print(range4)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.
 7.2 7.4 7.6 7.8 8.  8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]


<h4> 4. Using dtype  

In [ ]:
range5= np.arange(5, dtype="float")
print(range5) # [0,1,2,3,4] as int make it float--[0.0, 1.0, 2.0, 3.0, 4.0]

[0. 1. 2. 3. 4.]


In [ ]:
arr = np.arange(2, dtype=bool)
print(arr) # [0,1] as int make it bool--[False, True]

[False  True]


Start < Stop with Negative Step -- [] empty list
Start > Stop with Positive Step -- [] empty list

Integer + Float Inputs

In [23]:
arr = np.arange(1, 5.5)

print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5.]
float64


---<a id="1-nparray"></a>

<div style="background:#1E2235; border-radius:10px; padding:18px 24px; margin:32px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:16px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="color:#FFFFFF; font-size:1.4em; font-weight:800; min-width:32px; font-family:'Segoe UI',sans-serif;">3.</span>
<div style="display:flex; align-items:center; gap:8px; flex-wrap:wrap;">
<code style="background:#2A2F47; color:#E8A84A; font-size:1.15em; font-weight:700; padding:5px 14px; border-radius:6px; letter-spacing:0.3px; font-family:'Courier New',monospace;">np.linspace()</code>
</div>
</div>---




> **Control the count, not the step.** You specify *how many* equally-spaced values you want between `start` and `stop`.

| Parameter | Description | Default |
|-----------|-------------|---------|
| `start` | Starting value (included) | Required |
| `stop` | Ending value | Required |
| `num` | Number of values to generate | `50` |
| `endpoint` | Include `stop` or not | `True` |
| `retstep` | Also return the step size | `False` |
| `dtype` | Data type | Auto |

<div style="border:2px solid #8B5CF6; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#7C3AED; padding:8px 16px; display:flex; align-items:center; gap:8px;">
<span style="font-size:1.1em;">🤖</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">AI Insight — Why linspace matters</span>
</div>
<div style="background:#F5F3FF; padding:14px 18px; color:#3B0764; font-size:0.97em; line-height:1.6;">
In deep learning, <code>np.linspace()</code> is used to: build learning rate schedules, create x-axis values for loss curves, generate evenly-spaced ROC thresholds, and define numerical integration grid points.
</div>
</div>

In [31]:
#np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

"""  Parameter	           Description	                   Default
     
     start	           Starting value (included)	       Required
      stop	                Ending value                    Required
      num	         Number of values to generate	         50
     endpoint	         Include stop or not	            True
     retstep          	 Return step size also	            False
      dtype	                 Data type	                     Auto
      axis	         Axis to store samples (advanced)	      0            """

'  Parameter\t           Description\t                   Default\n\n     start\t           Starting value (included)\t       Required\n      stop\t                Ending value                    Required\n      num\t         Number of values to generate\t         50\n     endpoint\t         Include stop or not\t            True\n     retstep          \t Return step size also\t            False\n      dtype\t                 Data type\t                     Auto\n      axis\t         Axis to store samples (advanced)\t      0            '

Creates equally spaced numbers between a start and stop value.

Unlike np.arange(), you specify the number of values, not the step size.

<h4> 1) Without Specifying Num

In [ ]:
x= np.linspace(1,5) #by default no of separation = 50~
print(x)

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


<h4> 2) Specifying Num

In [ ]:
y=np.linspace(1,5,10) # manulay gives 5 for no of separations
print(y)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


<H4>3) Decimal Values

In [37]:
a=np.linspace(0,5,5)
print(a)

[0.   1.25 2.5  3.75 5.  ]


<h4> 4. Endpoint=False

In [40]:
b=np.linspace(1,5,4,endpoint=False) #5 will not include
print(b)

[1. 2. 3. 4.]


<h4>5) retstep=True  // Useful when you also need the spacing.

In [42]:
spaces, without_spaces= np.linspace(1,5,5, retstep=True)
print(spaces,without_spaces)

[1. 2. 3. 4. 5.] 1.0


<h4> 6) Using dtype

In [50]:
array1= np.linspace(0,5,10)
array2= np.linspace(0,5,10, dtype=int)
array3= np.linspace(0,5,10, dtype=bool)
print(array1)
print("After using bool: ", array3)
print("after using Int: ", array2)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
After using bool:  [False  True  True  True  True  True  True  True  True  True]
after using Int:  [0 0 1 1 2 2 3 3 4 5]


<H4>7)  Negative Range

In [52]:
axis= np.linspace(-5,5,11,dtype=int)
print(axis)

[-5 -4 -3 -2 -1  0  1  2  3  4  5]


<h4> 8) Num=1, returns start value


In [53]:
num= np.linspace(1,100,1)
print(num)

[1.]


<h4> 9) num=0 ---> []  empty array

In [55]:
num1= np.linspace(1,100,0)
print(num1)

[]


In [124]:
np.logspace(range(5), 4,5)

array([[1.00000000e+00, 1.00000000e+01, 1.00000000e+02, 1.00000000e+03,
        1.00000000e+04],
       [1.00000000e+01, 5.62341325e+01, 3.16227766e+02, 1.77827941e+03,
        1.00000000e+04],
       [1.00000000e+02, 3.16227766e+02, 1.00000000e+03, 3.16227766e+03,
        1.00000000e+04],
       [1.00000000e+03, 1.77827941e+03, 3.16227766e+03, 5.62341325e+03,
        1.00000000e+04],
       [1.00000000e+04, 1.00000000e+04, 1.00000000e+04, 1.00000000e+04,
        1.00000000e+04]])

---
### `np.logspace()`

> `np.logspace(a, b, n)` is equivalent to `10 ** np.linspace(a, b, n)`.  
> Values are spaced **logarithmically** — essential for hyperparameter search.

<div style="border:2px solid #8B5CF6; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#7C3AED; padding:8px 16px; display:flex; align-items:center; gap:8px;">
<span style="font-size:1.1em;">🤖</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">AI Insight — Log Scale in ML</span>
</div>
<div style="background:#F5F3FF; padding:14px 18px; color:#3B0764; font-size:0.97em; line-height:1.6;">
Learning rates typically range from <code>1e-5</code> to <code>1e-1</code>. <code>np.logspace(-5, -1, 5)</code> produces a log-scale grid — exactly how grid search hyperparameter tuning works.
</div>
</div>

<h4>np.logspace(a,b,n) == 10 ** np.linspace(a,b,n)

In [ ]:
x= np.logspace(0,3,4)  #10**np.linspace(0,3,4)
y= np.linspace(0,3,4)
print(x)
print(y)

[   1.   10.  100. 1000.]
[0. 1. 2. 3.]




<div style="background:#1E2235; border-radius:10px; padding:18px 24px; margin:32px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:16px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="color:#FFFFFF; font-size:1.4em; font-weight:800; min-width:32px; font-family:'Segoe UI',sans-serif;">4.</span>
<div style="display:flex; align-items:center; gap:8px; flex-wrap:wrap;">
<code style="background:#2A2F47; color:#E8A84A; font-size:1.15em; font-weight:700; padding:5px 14px; border-radius:6px; letter-spacing:0.3px; font-family:'Courier New',monospace;">np.zeros()</code>
</div>
</div>------




> Creates an array of a given shape where **every element is 0**.

**Syntax:**
```python
np.zeros(shape, dtype=float, order='C')
```

Shapes are passed as tuples: `(rows, cols)` for 2-D, `(depth, rows, cols)` for 3-D.

<div style="border:2px solid #8B5CF6; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#7C3AED; padding:8px 16px; display:flex; align-items:center; gap:8px;">
<span style="font-size:1.1em;">🤖</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">AI Insight</span>
</div>
<div style="background:#F5F3FF; padding:14px 18px; color:#3B0764; font-size:0.97em; line-height:1.6;">
Bias vectors in neural networks are almost always initialised to zero. Zero arrays are also used as placeholder output buffers when you plan to fill values element-by-element in a loop.
</div>
</div>

Creates an array filled entirely with 0s ................     //shape under tuple

In [ ]:
#np.zeros(shape, dtype=float, order='C')

<h4>1) Different shapes

In [68]:
#1-D
one_d= np.zeros(5)
two_d= np.zeros((2,3))
three_d= np.zeros((2,2,3))
print(one_d)
print()
print(two_d)
print()
print(three_d)



[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


<h4>2) Specifying dtype

In [70]:
integer = np.zeros(2, dtype=int)
boole = np.zeros(2,dtype=bool)
comple =np.zeros(2, dtype=complex)
print(integer)
print(boole)
print(comple)

[0 0]
[False False]
[0.+0.j 0.+0.j]


<h4> 3) Empty dimensions

In [ ]:
empty= np.zeros(())
empty2= np.zeros((0,))
empty3= np.zeros((0,0))
print(empty)
print(empty2)
print(empty3)
# EVEN (1,0) ONE ROW 0 COLUMNS MEANS []


0.0
[]
[]


---
### `np.empty()`

> Creates an array of a given shape **without initialising its values**.  
> Allocates memory and returns whatever bytes already exist at that location.  
> You must overwrite all values before reading them.

<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;">
<span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Warning</span>
</div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
Never read from a <code>np.empty()</code> array before writing to every element. Values are <b>not guaranteed to be zero</b> — they are leftover memory.
</div>
</div>

Creates an array without initializing its values.

It allocates memory and returns whatever values are already present at that memory location.
You will overwrite all values later

<h4> 1) Different Shapes

In [142]:
emp= np.empty(5)
emp1=np.empty((2,3))
emp2=np.empty((2,3,4))
print(emp)
print()
print(emp1)
print()
print(emp2)

[1.   0.75 0.5  0.25 0.  ]

[[1. 1. 1.]
 [1. 1. 1.]]

[[[3.5e-323 3.5e-323 3.5e-323 3.5e-323]
  [3.5e-323 3.5e-323 3.5e-323 3.5e-323]
  [3.5e-323 3.5e-323 3.5e-323 3.5e-323]]

 [[3.5e-323 3.5e-323 3.5e-323 3.5e-323]
  [3.5e-323 3.5e-323 3.5e-323 3.5e-323]
  [3.5e-323 3.5e-323 3.5e-323 3.5e-323]]]


Values are not predictable- They are not random numbers; they are leftover memory values.

In [143]:
a= np.ones((0,))
a

array([], dtype=float64)

<h4>2) Using dtype

In [ ]:
arr1 = np.empty(5, dtype=int)
arr2 = np.empty(5, dtype=bool)
print(arr1)
print(arr2)

[4607182418800017408 4607182418800017408 4607182418800017408
 4607182418800017408 4607182418800017408]
[False False False False False]


| Feature | `np.zeros()` | `np.empty()` |
|---------|-------------|-------------|
| Values | All `0` | Uninitialised (leftover memory) |
| Speed | Slightly slower | Faster |
| Safe to read immediately | ✅ Yes | ❌ No |
| Use when | You want a clean starting array | You will overwrite every element before reading |

---
<a id="5-npones"></a>

## 5. `np.ones()`

> Creates an array filled entirely with `1`. Identical signature to `np.zeros()`.

<div style="border:2px solid #8B5CF6; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#7C3AED; padding:8px 16px; display:flex; align-items:center; gap:8px;">
<span style="font-size:1.1em;">🤖</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">AI Insight</span>
</div>
<div style="background:#F5F3FF; padding:14px 18px; color:#3B0764; font-size:0.97em; line-height:1.6;">
A common pattern: <code>np.ones((m, n)) * value</code> is equivalent to <code>np.full((m, n), value)</code>. Ones arrays are also used as initial attention masks in transformer models.
</div>
</div>

<h4> 1) Different Shapes

In [83]:
one_d= np.ones(5)
two_d= np.ones((2,3)) #tuple required for multidimentional shape
three_d= np.ones((2,2,3))
print(one_d)
print()
print(two_d)
print()
print(three_d)

[1. 1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]]

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


<h4> 2) Specifying dtype

In [84]:
arr = np.ones(5, dtype=int)
arr1= np.ones(5,dtype=bool)
arr2=np.ones(5, dtype=complex)
print(arr)
print(arr1)
print(arr2)

[1 1 1 1 1]
[ True  True  True  True  True]
[1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]


---
<a id="6-npfull"></a>

## 6. `np.full()`

> Creates an array of a given shape where every element has the **same specified value**.

**Syntax:**
```python
np.full(shape, fill_value, dtype=None, order='C')
```

| Function | Equivalent shorthand |
|----------|----------------------|
| `np.zeros(shape)` | `np.full(shape, 0)` |
| `np.ones(shape)` | `np.full(shape, 1)` |
| `np.full(shape, v)` | Fill with **any** value `v` |

<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;">
<span style="font-size:1.1em;">💡</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Tip — Initialising placeholder arrays</span>
</div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
Use <code>np.full(shape, np.nan)</code> to create a float array where every element signals 'not yet computed'. This makes missing values visible rather than hiding them as zeros.
</div>
</div>

In [95]:
#np.full(shape, fill_value, dtype=None, order='C')

Creates an array where every element is the same specified value.

In [ ]:
#Think of it as a generalized version of:

#np.zeros() → fills with 0
#np.ones() → fills with 1
#np.full() → fills with any value

<h4> 1) Different Shapes

In [100]:
fill= np.full(2,3)        #1D
fill2= np.full((2,3),5)   #2D
fill3= np.full((2,3,4),"AI") #3D

print(fill)
print()
print(fill2)
print()
print(fill3)

[3 3]

[[5 5 5]
 [5 5 5]]

[[['AI' 'AI' 'AI' 'AI']
  ['AI' 'AI' 'AI' 'AI']
  ['AI' 'AI' 'AI' 'AI']]

 [['AI' 'AI' 'AI' 'AI']
  ['AI' 'AI' 'AI' 'AI']
  ['AI' 'AI' 'AI' 'AI']]]


<h4>2) Using Dtype

In [105]:
flo= np.full((2,2),3, dtype=float)
print(flo)
boo= np.full((2,2),1, dtype=bool)
print(boo)

[[3. 3.]
 [3. 3.]]
[[ True  True]
 [ True  True]]


<h4>3) Filling with np.nan

In [147]:
nan= np.full((2,3),np.nan)
print(nan)

[[nan nan nan]
 [nan nan nan]]


---
<a id="7-npeye--npidentity"></a>

## 7. `np.eye()` and `np.identity()`

> Both create arrays with **1s on a diagonal and 0s everywhere else**.

**Syntax:**
```python
np.eye(N, M=None, k=0, dtype=float)   # flexible
np.identity(n, dtype=float)            # square only
```

| Parameter | `np.eye()` | `np.identity()` |
|-----------|-----------|----------------|
| Shape | N×M (can be rectangular) | n×n (always square) |
| Diagonal offset `k` | Supported | Not supported |

<div style="border:2px solid #8B5CF6; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#7C3AED; padding:8px 16px; display:flex; align-items:center; gap:8px;">
<span style="font-size:1.1em;">🤖</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">AI Insight — Identity Matrices in ML</span>
</div>
<div style="background:#F5F3FF; padding:14px 18px; color:#3B0764; font-size:0.97em; line-height:1.6;">
Identity matrices appear throughout ML: <b>no-op linear transform</b> (I × A = A), initialising recurrent weight matrices in RNNs, residual shortcut connections in ResNets, and covariance matrix baselines.
</div>
</div>

In [108]:
#np.eye(N, M=None, k=0, dtype=float, order='C')

# Parameter 	  Meaning
# N   	    Number of rows
# M	        Number of columns (default = N)
# k	        Diagonal offset
# dtype    	Data type

Creates a 2D array with 1s on a specified diagonal and 0s everywhere else.

<h4>1) Identity Matrix --np.eye(x)

In [110]:
arr = np.eye(3)
print(arr) #Creates a 3 × 3 identity-like matrix.

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<h4>2) Rectangular Matrix

In [112]:
arr = np.eye(3,5)
print(arr) #This is the biggest difference from np.identity().

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


<h4>3) Upper Diagonal (k=1)

In [ ]:
upp= np.eye(4, k=1)
print(upp) #Diagonal shifts one column to the right.

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


<h4> 4) Lower Diagnol (K=-1)

In [116]:
low= np.eye(4, k=-1)
print(low) #Diagonal shifts one row down

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


<h4> 5) Larger Offset

In [ ]:
lof= np.eye(10, k=4)
print(lof) # k: ofset-  rows with not having 1 in rows, then start from last row from bottom till up and assign 1 diagonally and you notice same no of cols miss 1

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


<h4> 6) If K is large  ---- all 0

In [123]:
k= np.eye(3,k=5)
print(k)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


---
### `np.identity()`

> A strict square identity matrix — simpler interface than `np.eye()`, with no rectangular shape or diagonal offset support.

Creates a square identity matrix with 1s on the main diagonal and 0s elsewhere.

It is basically a simplified version of np.eye().

<h4> 1) Using dtypes

In [139]:
ind1= np.identity(3)
print(ind1.dtype)
print(ind1)
print()
ind2 = np.identity(4, dtype=bool)
print(ind2)


float64
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]


<h4> 2) np.eye() vs np.identity()

In [141]:
#Parameters
# eye()---N, M, k, dtype
# identity() ---- n, dtype

---
<a id="8-nprandom"></a>

## 8. `np.random`

> The `np.random` module provides random number generation — essential for initialising weights, sampling mini-batches, and data augmentation.

<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;">
<span style="font-size:1.1em;">💡</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Tip — Reproducibility</span>
</div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
Always call <code>np.random.seed(n)</code> before any random operation in experiments or notebooks. This guarantees the <b>same random numbers every run</b> — critical for reproducible ML research.
</div>
</div>

<div style="background:#C2410C; border-radius:8px; padding:10px 18px; margin:20px 0 10px 0; display:flex; align-items:center; gap:10px; font-family:'Segoe UI',sans-serif;"><span style="color:#FCD34D; font-size:1.3em;">▶</span><span style="color:#FFFFFF; font-weight:700; font-size:1.08em;">1. np.random.rand()</span></div>

Generates random numbers from a uniform distribution in [0, 1).

<h4>1) Different shapes

In [207]:
empty =np.random.rand(0)
a= np.random.rand() # Returns a single random float uniformly distributed in the range [0, 1).
b= np.random.rand(5)  #Creates a 1D NumPy array containing 5 random float values between 0 (inclusive) and 1 (exclusive).
c= np.random.rand(2,3,4) # Creates a 2 × 3 array where every element is a random float between 0 and 1.
print(empty,"\n")
print(a, "\n")              #  *******rand(no of output/ shape)*********** 
print(b, "\n") 
print(c ,'\n')



[] 

0.06819117567502575 

[0.60390148 0.60435815 0.93983796 0.66575485 0.2188072 ] 

[[[0.2270805  0.63072935 0.48658718 0.07675883]
  [0.33574071 0.42320076 0.94445019 0.21060021]
  [0.07014436 0.36902773 0.50600037 0.52003857]]

 [[0.63890832 0.41405142 0.3196433  0.82094908]
  [0.02479055 0.60440515 0.59435427 0.2359539 ]
  [0.83684215 0.64827204 0.20829132 0.63776503]]] 



<div style="background:#C2410C; border-radius:8px; padding:10px 18px; margin:20px 0 10px 0; display:flex; align-items:center; gap:10px; font-family:'Segoe UI',sans-serif;"><span style="color:#FCD34D; font-size:1.3em;">▶</span><span style="color:#FFFFFF; font-weight:700; font-size:1.08em;">2. np.random.randn()</span></div>

Generates numbers from a standard normal distribution.

Mean = 0 and 
Standard Deviation = 1

In [ ]:
"""

Now imagine a bell-shaped hill. 

              ^
             ***
           *******                       Numbers near 0 occur most often.
         ***********                     Numbers far from 0 occur less often.
------***************------       
   -3  -2  -1  0  1  2  3               np.random.randn() 

                                         Possible outputs: 0.25    can be positive
                                                          -0.83    can be negative
                                                           1.42    can be greater than 1
                                                          -2.11
                                                           0.03    can be smaller than 1
mean = 0 and std =1:
Most numbers lie between  -1 and 1            Mean = 0 : Think of 0 as the center.
Many lie between: -2 and 2                    >>>Most generated numbers will be close to 0.     
Very few are beyond: -3 or 3
                                             Standard Deviation = 1:  This simply tells how spread out the numbers are.

                                                     

"""

''

In [ ]:
a= np.random.randn() #Returns one random number from the standard normal (Gaussian) distribution with mean = 0 and standard deviation = 1.
print(a)
b=np.random.randn(3) #Creates a 1D array of 3 normally distributed random numbers. Values may be negative, positive, or greater than 1.
print(b)
c= np.random.randn(2,3) #Creates a 2 × 2 array filled with random numbers from the standard normal distribution.
print(c)

-0.22618617225773746
[-0.2350275  -0.75884611 -0.89838365]
[[ 0.20275014  0.24446163 -0.18627933]
 [-1.99890571 -0.39571907  0.68729146]]


<div style="background:#C2410C; border-radius:8px; padding:10px 18px; margin:20px 0 10px 0; display:flex; align-items:center; gap:10px; font-family:'Segoe UI',sans-serif;"><span style="color:#FCD34D; font-size:1.3em;">▶</span><span style="color:#FFFFFF; font-weight:700; font-size:1.08em;">3. np.random.randint()</span></div>

Without Size attribute - 1D

In [ ]:
x= np.random.randint(10) # Returns a single random integer from 0 to 9 (10 is excluded).
y= np.random.randint(1,10,2)  #Returns two random integer from 1 to 9. The upper limit (10) is never included.

print(x)
print(y)

[0 3]
9
[4 4]


With Size

In [166]:
z= np.random.randint(1,10,size=(2,3)) #reates a 2 × 3 array containing random integers between 1 and 9.
print(z)

[[4 1 4]
 [2 7 1]]


<div style="background:#C2410C; border-radius:8px; padding:10px 18px; margin:20px 0 10px 0; display:flex; align-items:center; gap:10px; font-family:'Segoe UI',sans-serif;"><span style="color:#FCD34D; font-size:1.3em;">▶</span><span style="color:#FFFFFF; font-weight:700; font-size:1.08em;">4. np.random.choice()</span></div>

Single Selection

In [167]:
one=np.random.choice([10,20,30]) #Randomly selects one element from the given list.
print(one)

10


Multiple Selections- with repeatation allowed

In [175]:
mul=np.random.choice(10,2) #Randomly selects 5 values from the range 0–9 with replacement.
multiple= np.random.choice([10,20,30],3) #Randomly selects 3 elements from the list. By default, elements can repeat because replace=True.
print(mul)
print(multiple)

[5 3]
[20 30 30]


Multiple selections with no repeatation allowed

In [172]:
#choice(x:0 to [x-1]/ list , no of choices, replace  )

In [ ]:
mult= np.random.choice([10,20,30,40,50,60],2, replace=False )
print(mult)

[3 8]
[30 60]


Selection with probability  , p attribute

In [189]:
prob= np.random.choice([1,2,3], p=[0.2,0.3,0.5])  # Randomly selects one element where 3 has the highest probability (50%), 2 has 30%, and 1 has 20%.
print(prob)

3


<div style="background:#C2410C; border-radius:8px; padding:10px 18px; margin:20px 0 10px 0; display:flex; align-items:center; gap:10px; font-family:'Segoe UI',sans-serif;"><span style="color:#FCD34D; font-size:1.3em;">▶</span><span style="color:#FFFFFF; font-weight:700; font-size:1.08em;">5. np.random.seed()</span></div>

### 5. `np.random.seed()`

Sets the **global random seed** so all subsequent `np.random` calls produce the same number sequence.

```python
np.random.seed(42)
np.random.rand(3)
# Always: [0.37454012, 0.95071431, 0.73199394]
```

<div style="border:2px solid #16A34A; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#15803D; padding:8px 16px; display:flex; align-items:center; gap:8px;">
<span style="font-size:1.1em;">ℹ️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Info — Modern API</span>
</div>
<div style="background:#F0FDF4; padding:14px 18px; color:#14532D; font-size:0.97em; line-height:1.6;">
For new code, prefer the Generator API: <code>rng = np.random.default_rng(42)</code>. It is faster, thread-safe, and supports richer distributions.
</div>
</div>

<div style="background:#C2410C; border-radius:8px; padding:10px 18px; margin:20px 0 10px 0; display:flex; align-items:center; gap:10px; font-family:'Segoe UI',sans-serif;"><span style="color:#FCD34D; font-size:1.3em;">▶</span><span style="color:#FFFFFF; font-weight:700; font-size:1.08em;">6. np.random.shuffle()</span></div>    

<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;">
<span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Warning — shuffle modifies in-place</span>
</div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
<code>np.random.shuffle()</code> returns <code>None</code> and <b>modifies the original array directly</b>. To keep the original intact, use <code>np.random.permutation()</code> instead.
</div>
</div>

Original array itself is modified.

In [203]:
#Creating 2 arrays orignal and orignal1
orignal=np.array([1,2,3,4,5])
orignal1= np.arange(10)
print(orignal)
print(orignal1)

#shuffling both the arrays
new_shuffled= np.random.shuffle(orignal)
new_shuffled= np.random.shuffle(orignal1)

print(new_shuffled)# Gives None because there is just a method called, changes done in orignal one onlu.
print(orignal)
print(orignal1)




[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]
None
[4 1 3 2 5]
[9 6 0 1 3 2 7 4 5 8]


<div style="background:#C2410C; border-radius:8px; padding:10px 18px; margin:20px 0 10px 0; display:flex; align-items:center; gap:10px; font-family:'Segoe UI',sans-serif;"><span style="color:#FCD34D; font-size:1.3em;">▶</span><span style="color:#FFFFFF; font-weight:700; font-size:1.08em;">7. np.random.permutation()</span></div>

<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;">
<span style="font-size:1.1em;">💡</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Tip — shuffle vs permutation</span>
</div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
<ul style='margin:4px 0 0 0;padding-left:18px;'><li><code>np.random.shuffle(arr)</code> — in-place, returns None, original changed</li><li><code>np.random.permutation(arr)</code> — returns a new copy, original unchanged</li><li>Both are standard for shuffling training data before each epoch.</li></ul>
</div>
</div>

Returns a new shuffled array, while the original  remains unchanged

In [200]:
# creating array
a= np.arange(8)
print(a)

#shuffling without changing orignal value
b=np.random.permutation(a)
print(b)
print(a is b)

[0 1 2 3 4 5 6 7]
[0 6 7 3 2 1 4 5]
False


Number itself a range- ( 0 to Number-1 )

In [204]:
x=np.random.permutation(5)
print(x)

[4 0 1 3 2]


---
<a id="interview-questions"></a>

## 🎤 Interview Questions

---

### 🟢 Beginner

**Q1.** What is the difference between `np.array([1, 2, 3])` and `np.arange(3)`?  
<details><summary>▶ Answer</summary>
<code>np.array([1, 2, 3])</code> creates an array from an explicit list: <code>[1, 2, 3]</code>.  
<code>np.arange(3)</code> generates a range starting from 0: <code>[0, 1, 2]</code>.  
They produce <b>different values</b>; only the shape is the same.
</details>

**Q2.** What dtype does NumPy assign to `np.array(['apple', 'mango'])`? Why?  
<details><summary>▶ Answer</summary>
<code>&lt;U5</code> — Unicode string of max length 5 (the length of <code>'apple'</code>). NumPy sets the width to the longest string in the array.
</details>

**Q3.** What is the output of `np.array([]).dtype`?  
<details><summary>▶ Answer</summary>
<code>float64</code> — empty arrays default to float64.
</details>

---

### 🟡 Intermediate

**Q4.** What is upcasting in NumPy? Give an example.  
<details><summary>▶ Answer</summary>
NumPy promotes all elements to the most general dtype when types are mixed.  
Example: <code>np.array([1, 2.5, 3])</code> → all elements become <code>float64</code> because 2.5 requires float.  
Promotion order: <code>bool → int → float → complex → str → object</code>
</details>

**Q5.** What is the difference between `np.zeros()` and `np.empty()`?  
<details><summary>▶ Answer</summary>
<code>np.zeros()</code> initialises every element to 0 (safe to read immediately).  
<code>np.empty()</code> allocates memory without writing any values — faster, but unsafe to read before filling.
</details>

**Q6.** When would you use `np.linspace()` instead of `np.arange()`?  
<details><summary>▶ Answer</summary>
When you need an exact count of points between two values.  
<code>np.arange()</code> can produce unexpected element counts with float steps due to floating-point precision.  
<code>np.linspace()</code> guarantees exactly <code>num</code> elements.
</details>

---

### 🔴 Advanced

**Q7.** What is the difference between `np.random.shuffle()` and `np.random.permutation()`?  
<details><summary>▶ Answer</summary>
<code>shuffle()</code> modifies the array <b>in-place</b> and returns <code>None</code>.  
<code>permutation()</code> returns a <b>new shuffled copy</b> and leaves the original unchanged.
</details>

**Q8.** Why does `np.array({'a': 1, 'b': 2})` produce a 0-D object array instead of a 1-D array?  
<details><summary>▶ Answer</summary>
NumPy does not iterate over dictionaries (or sets). It wraps the entire dict as a single Python object, producing a 0-D array with <code>dtype=object</code>.  
Use <code>list(d.values())</code> to get a proper 1-D numeric array.
</details>

**Q9.** What is `np.logspace(0, 3, 4)` equivalent to, and when would you use it?  
<details><summary>▶ Answer</summary>
Equivalent to <code>10 ** np.linspace(0, 3, 4)</code> → <code>[1., 10., 100., 1000.]</code>  
Used for log-scale hyperparameter grids — e.g. sweeping learning rates from 1e-4 to 1e-1.
</details>

---

---
<a id="practice-questions"></a>

## 📝 Practice Questions

*(Try solving each question before running any code.)*

---

### 🟢 Easy

1. Create a 1-D array containing integers 1 through 10 using `np.arange()`.
2. Create a 3×4 array filled entirely with zeros using `np.zeros()`.
3. Create an array `['python', 'numpy', 'pandas']` and print its `dtype`. What is it, and why?
4. Create a 4×4 identity matrix using `np.eye()`.
5. Generate 5 random floats between 0 and 1 using `np.random.rand()`.

---

### 🟡 Medium

6. Create 7 evenly spaced values between 0 and π (`np.pi`). Print the step size using `retstep=True`.
7. Create `np.array([1, 2.5, 3+2j, True])` and explain what dtype NumPy assigns and why.
8. Using `np.random.seed(0)`, generate a 3×3 matrix of random integers between 10 and 50. Verify it's reproducible.
9. Create a 2×5 array filled with `np.nan` using `np.full()`.
10. Demonstrate the difference between `np.random.shuffle()` and `np.random.permutation()` on the same input array.

---

### 🔴 Hard

11. Create a 10×10 matrix where the diagonal is shifted by `k=3` contains ones and everything else is zero.
12. Starting from `{'a': 10, 'b': 20, 'c': 30}`, extract keys and values into separate NumPy arrays.
13. Explain — with code — why `np.array([1, 2, None])` has `dtype=object` while `np.array([1, 2, np.nan])` has `dtype=float64`. What are the performance implications?
14. Use `np.random.choice()` to simulate drawing 10 cards from a standard 52-card deck *without replacement*.
15. Replicate `np.logspace(0, 4, 5)` using only `np.linspace()` and the `**` operator. Verify equality with `np.allclose()`.

---

---
<a id="mini-challenge"></a>

## 🏆 Mini Challenge — Putting It All Together

You are building a small data simulation pipeline for a supervised machine learning experiment.

**Complete all 8 steps:**

1. **Seed** the random number generator with `42` for reproducibility.
2. **Create** a feature matrix of shape `(100, 5)` sampled from the standard normal distribution using `randn`.
3. **Create** a weight vector of shape `(5,)` using `np.linspace(0.1, 0.9, 5)`.
4. **Create** a bias vector of shape `(100,)` filled with `0.1` using `np.full()`.
5. **Compute** predictions: `predictions = features @ weights + bias` (use the `@` matrix multiplication operator).
6. **Create** a 100×100 identity matrix representing the "no mixing" covariance baseline.
7. **Shuffle** a *copy* of your `predictions` array using `permutation()` — do not modify the original.
8. **Verify** the original `predictions` array is unchanged after step 7.

> **Bonus:** Replace step 4 with `np.zeros()` and explain how the predictions change.

---

---
<a id="summary"></a>

## 📌 Summary

### Key Takeaways

- **`np.array()`** is the universal constructor — it accepts lists, tuples, arrays, and scalars. It always makes a deep copy by default.
- **NumPy enforces a single dtype** per array. Mixing types triggers automatic upcasting: `bool → int → float → complex → str → object`.
- **`np.arange()`** works like `range()` but returns an ndarray and supports float steps — use with care due to floating-point precision.
- **`np.linspace()`** is the safe choice when you need an exact count of evenly spaced float values.
- **`np.logspace()`** creates logarithmically spaced sequences — essential for hyperparameter grids.
- **`np.zeros()`, `np.ones()`, `np.full()`** create pre-filled arrays for initialising weights and biases.
- **`np.empty()`** is faster but dangerous — never read before writing every element.
- **`np.eye()`** supports rectangular and offset diagonals; `np.identity()` is its simpler square-only version.
- **`np.random`** functions power stochastic ML workflows — always `seed()` for reproducibility.

---

### 📋 Function Quick Reference

| Function | Shape arg | Default fill | Float steps |
|----------|-----------|-------------|-------------|
| `np.array(data)` | inferred from data | from data | ✅ |
| `np.arange(stop)` | 1-D | range values | ✅ (with caution) |
| `np.linspace(a, b, n)` | 1-D (n points) | n equal values | ✅ (safe) |
| `np.zeros(shape)` | tuple | 0 | ✅ |
| `np.ones(shape)` | tuple | 1 | ✅ |
| `np.full(shape, v)` | tuple | any value `v` | ✅ |
| `np.eye(N)` | N×N | 0/1 diagonal | ✅ |
| `np.random.rand(d)` | positional dims | uniform [0, 1) | ✅ |
| `np.random.randn(d)` | positional dims | normal μ=0, σ=1 | ✅ |
| `np.random.randint(lo, hi, n)` | n elements | integers | ❌ |

---

### 🗺️ What's Next on the AI Engineer Roadmap

1. **Array Indexing & Slicing** — accessing rows, columns, and sub-arrays
2. **Array Reshaping** — `reshape()`, `ravel()`, `flatten()`, `transpose()`
3. **Array Operations** — arithmetic, broadcasting, aggregation (`sum`, `mean`, `std`)
4. **Boolean Masking & Fancy Indexing** — filtering arrays with conditions

---

---
<a id="references"></a>

## 📚 References

### Official Documentation

- 📖 [NumPy Array Creation Routines](https://numpy.org/doc/stable/reference/routines.array-creation.html) — Official reference for all functions covered here
- 📖 [NumPy Data Types](https://numpy.org/doc/stable/reference/arrays.dtypes.html) — Full dtype reference and type promotion rules
- 📖 [NumPy Random Module](https://numpy.org/doc/stable/reference/random/index.html) — `np.random` complete API guide

### Recommended Reading

- 📘 *Python for Data Analysis* — Wes McKinney — the definitive NumPy + pandas primer for practitioners
- 📘 *Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow* — Aurélien Géron — NumPy in real ML pipelines

### Useful Resources

- 🔗 [NumPy Cheat Sheet (DataCamp)](https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python)
- 🔗 [100 NumPy Exercises (GitHub)](https://github.com/rougier/numpy-100) — Excellent practice repository
- 🔗 [GitHub: HarshAIWorks](https://github.com/HarshAIWorks) — Author's AI engineer portfolio

---

<div style="background: linear-gradient(135deg, #1a237e, #01579b); padding: 20px 24px; border-radius: 8px; color: white; text-align: center; font-family: 'Segoe UI', sans-serif;">
<b>📘 End of Notebook — NumPy Array Creation</b><br>
<span style="opacity: 0.8; font-size: 0.9em;">Created by Harsh Thakur &nbsp;|&nbsp; GitHub: HarshAIWorks &nbsp;|&nbsp; AI Engineer Roadmap</span>
</div>