<div style="background: linear-gradient(135deg, #1a237e 0%, #0d47a1 50%, #01579b 100%); padding: 48px 40px; border-radius: 12px; color: white; font-family: 'Segoe UI', sans-serif; text-align: center;">

<h1 style="font-size: 2.6em; font-weight: 800; margin: 0 0 8px 0; letter-spacing: 1px;">📐 NumPy Array Attributes</h1>
<p style="font-size: 1.2em; margin: 0 0 32px 0; opacity: 0.85;">Complete Guide — shape · ndim · size · dtype · itemsize · nbytes · T</p>

<hr style="border: 1px solid rgba(255,255,255,0.3); margin-bottom: 28px;">

<table style="margin: 0 auto; border-collapse: collapse; color: white; font-size: 0.95em;">
<tr>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Author</b>
  Harsh Thakur
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">GitHub</b>
  HarshAIWorks
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topic</b>
  Array Attributes
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Difficulty Level</b>
 Easy
</td>
<td style="padding: 8px 28px;">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">No of Topics</b>
  ~7
</td>
</tr>
</table>
</div>

## 📑 Table of Contents

| # | Section |
|---|---------|
| 1 | [`shape`](#1-shape) |
| 2 | [`ndim`](#2-ndim) |
| 3 | [`size`](#3-size) |
| 4 | [`dtype`](#4-dtype) |
| 5 | [`itemsize`](#5-itemsize) |
| 6 | [`nbytes`](#6-nbytes) |
| 7 | [`T` (Transpose)](#7-transpose) |
| 8 | [🎤 Interview Questions](#interview-questions) |
| 9 | [📝 Practice Questions](#practice-questions) |
| 10 | [🏆 Mini Challenge](#mini-challenge) |
| 11 | [📌 Summary](#summary) |
| 12 | [📚 References](#references) |

## 🧩 What Are Array Attributes?


Array attributes are properties of a NumPy array that tell you information about it.
<br>
<br>
Think of them as the identity card of an array.
<br>

For example, they answer questions like:
<br>
How many rows and columns does it have?
<br>
How many values are inside?
<br>
What type of data is stored?
<br>
How much memory does it use?

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Attributes vs. Functions</span></div>


✅ arr.shape <br>❌ Not: arr.shape()

<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">💡</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Tip</span></div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
Attributes describe the array (no parentheses, no computation) — e.g. <code>arr.shape</code>. Methods/functions <b>do</b> something and are called with parentheses — e.g. <code>arr.reshape(2,2)</code>.
</div>
</div>

In [2]:
import numpy as np

arr0=np.array(2)  #Creating 0-D array

arr1 = np.arange(4) #Creating 1-D array


arr2 = np.array([  #Creating 2-D array
    [25, 50000], 
    [30, 60000],
    [35, 75000]
])

arr3= np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) #Creating 3-D array
print(arr0, "\n")
print(arr1, "\n")
print(arr2, "\n")
print(arr3, "\n")


2 

[0 1 2 3] 

[[   25 50000]
 [   30 60000]
 [   35 75000]] 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 



<a id="1-shape"></a>

<div style="background:#1E2235; border-radius:10px; padding:18px 24px; margin:32px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:16px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="color:#FFFFFF; font-size:1.4em; font-weight:800; min-width:32px;">1.</span>
<div style="display:flex; align-items:center; gap:8px; flex-wrap:wrap;"><code style="background:#2A2F47; color:#E8A84A; font-size:1.15em; font-weight:700; padding:5px 14px; border-radius:6px; letter-spacing:0.3px; font-family:'Courier New',monospace;">arr.shape</code></div>
</div>

> Returns a **tuple** describing the array's dimensions — how many axes it has and how many elements sit along each axis.

| Attribute | Returns | Notes |
|---|---|---|
| `arr.shape` | Tuple of ints | Length of tuple = number of dimensions (ndim) |


() - 0D<br>
(x, ) - 1d<br>
(x , y) - 2d<br>
(x , y , z) - 3d

In [67]:
print(arr0.shape)  #0d
print(arr1.shape)  #1d
print(arr2.shape)  #2d
print(arr3.shape)  #3d


()
(4,)
(3, 2)
(2, 2, 2)


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ What does (4,) mean?</span></div>

It means:

1 dimension
4 elements<br>
There are: no Rows ❌
no Columns ❌
<br>There is only one axis.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ What does (3, 2) mean?</span></div>

Rows = 3
Columns = 2<br><br> Visualize it:       <br><br>   Columns<br>
      &nbsp;&nbsp;  ┌────┬──────┐<br>
Row 1 &nbsp;&nbsp;  │25  │50000 │<br>
       &nbsp;&nbsp; ├────┼──────┤<br>
Row 2  &nbsp;&nbsp; │30  │60000 │<br>
       &nbsp;&nbsp; ├────┼──────┤<br>
Row 3  &nbsp;&nbsp; │35  │75000 │<br>
       &nbsp;&nbsp; └────┴──────┘<br>

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ What does (2, 2, 2) mean?</span></div>

2 layers<br>

Each layer has:
2 rows and
2 columns

<div style="border:2px solid #16A34A; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#15803D; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">ℹ️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Info — reading shape tuples</span></div>
<div style="background:#F0FDF4; padding:14px 18px; color:#14532D; font-size:0.97em; line-height:1.6;">
Read a shape tuple <b>left to right, outside-in</b>: the first number is the outermost grouping (e.g. "layers" or "rows"), the last number is the innermost (columns/elements per row).
</div>
</div>

<a id="2-ndim"></a>

<div style="background:#1E2235; border-radius:10px; padding:18px 24px; margin:32px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:16px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="color:#FFFFFF; font-size:1.4em; font-weight:800; min-width:32px;">2.</span>
<div style="display:flex; align-items:center; gap:8px; flex-wrap:wrap;"><code style="background:#2A2F47; color:#E8A84A; font-size:1.15em; font-weight:700; padding:5px 14px; border-radius:6px; letter-spacing:0.3px; font-family:'Courier New',monospace;">arr.ndim</code></div>
</div>

> Returns an **integer** — the number of dimensions (axes) in the array. Always equals `len(arr.shape)`.

| Attribute | Returns | Notes |
|---|---|---|
| `arr.ndim` | int | Same as `len(arr.shape)` |


No of Dimensions

In [3]:
print(arr0.ndim) #0d
print(arr1.ndim) #1d
print(arr2.ndim) #2d
print(arr3.ndim) #3d


0
1
2
3


<a id="3-size"></a>

<div style="background:#1E2235; border-radius:10px; padding:18px 24px; margin:32px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:16px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="color:#FFFFFF; font-size:1.4em; font-weight:800; min-width:32px;">3.</span>
<div style="display:flex; align-items:center; gap:8px; flex-wrap:wrap;"><code style="background:#2A2F47; color:#E8A84A; font-size:1.15em; font-weight:700; padding:5px 14px; border-radius:6px; letter-spacing:0.3px; font-family:'Courier New',monospace;">arr.size</code></div>
</div>

> Returns an **integer** — the total number of elements in the array (product of all shape values).

| Attribute | Returns | Notes |
|---|---|---|
| `arr.size` | int | Equals the product of every value in `arr.shape` |


No of elements

In [23]:
print(arr0.size) # 4 
print(arr1.size) # [0 1 2 3] 


print(arr2.size) #           [[   25 50000]
                #             [   30 60000]
                #             [   35 75000]] 



print(arr3.size) #    [[[1 2]
                 #     [3 4]]

                 #    [[5 6]
                 #    [7 8]]]

1
4
6
8


<a id="4-dtype"></a>

<div style="background:#1E2235; border-radius:10px; padding:18px 24px; margin:32px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:16px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="color:#FFFFFF; font-size:1.4em; font-weight:800; min-width:32px;">4.</span>
<div style="display:flex; align-items:center; gap:8px; flex-wrap:wrap;"><code style="background:#2A2F47; color:#E8A84A; font-size:1.15em; font-weight:700; padding:5px 14px; border-radius:6px; letter-spacing:0.3px; font-family:'Courier New',monospace;">arr.dtype</code></div>
</div>

> Returns the **data type** of the array's elements (e.g. `int64`, `float64`, `<U6`, `object`).

| Attribute | Returns | Notes |
|---|---|---|
| `arr.dtype` | numpy.dtype | All elements in an array share exactly one dtype |


Datatype of an Array

In [35]:
print(arr0.dtype)
print(np.array([]).dtype) #empty - float64
print(np.arange(5.5),np.arange(5.5).dtype)
print(np.arange(5.5+0j,step=1.5+0j).dtype)

int64
float64
[0. 1. 2. 3. 4. 5.] float64
complex128


<div style="border:2px solid #8B5CF6; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#7C3AED; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">🤖</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">AI Insight — float32 in Deep Learning</span></div>
<div style="background:#F5F3FF; padding:14px 18px; color:#3B0764; font-size:0.97em; line-height:1.6;">
Frameworks like PyTorch and TensorFlow default to <code>float32</code> because it halves the memory of <code>float64</code> and runs faster on GPU tensor cores, with minimal accuracy loss for most models.
</div>
</div>

<a id="5-itemsize"></a>

<div style="background:#1E2235; border-radius:10px; padding:18px 24px; margin:32px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:16px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="color:#FFFFFF; font-size:1.4em; font-weight:800; min-width:32px;">5.</span>
<div style="display:flex; align-items:center; gap:8px; flex-wrap:wrap;"><code style="background:#2A2F47; color:#E8A84A; font-size:1.15em; font-weight:700; padding:5px 14px; border-radius:6px; letter-spacing:0.3px; font-family:'Courier New',monospace;">arr.itemsize</code></div>
</div>

> Returns an **integer** — the memory (in bytes) used by a single element of the array.

| Attribute | Returns | Notes |
|---|---|---|
| `arr.itemsize` | int (bytes) | Depends on dtype — e.g. `int64` → 8, `float32` → 4, `<U6` → 24 |


Memory used by one element

In [ ]:
array1=np.arange(2) #int
array2=np.array([[1,"hello"],[3,4]]) # unicode
array2s=np.array([[1,"hello"],[3,4]],dtype=object) #obj
array3=np.arange(10) #int


print(array1,arr1.dtype, "and Size: ",array1.itemsize)
print()
print(array2, array2.dtype,"and Size: ",array2.itemsize)
print()
print(array2s, array2s.dtype,"and Size: ",array2s.itemsize)

print()
print(array3,array3.dtype, "and Size: ",array3.itemsize)


[0 1] int64 and Size:  8

[['1' 'hello']
 ['3' '4']] <U21 and Size:  84

[[1 'hello']
 [3 4]] object and Size:  8

[0 1 2 3 4 5 6 7 8 9] int64 and Size:  8


<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Warning — mixed types force object/unicode dtype</span></div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
Mixing numbers and strings in one array (like <code>[[1,"hello"],[3,4]]</code>) forces NumPy to upcast everything to a <b>unicode string</b> dtype, dramatically increasing <code>itemsize</code>. Use <code>dtype=object</code> only when truly necessary — it disables vectorized speed.
</div>
</div>

<a id="6-nbytes"></a>

<div style="background:#1E2235; border-radius:10px; padding:18px 24px; margin:32px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:16px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="color:#FFFFFF; font-size:1.4em; font-weight:800; min-width:32px;">6.</span>
<div style="display:flex; align-items:center; gap:8px; flex-wrap:wrap;"><code style="background:#2A2F47; color:#E8A84A; font-size:1.15em; font-weight:700; padding:5px 14px; border-radius:6px; letter-spacing:0.3px; font-family:'Courier New',monospace;">arr.nbytes</code></div>
</div>

> Returns an **integer** — the *total* memory (in bytes) occupied by all elements: `size × itemsize`.

| Attribute | Returns | Notes |
|---|---|---|
| `arr.nbytes` | int (bytes) | Equals `arr.size * arr.itemsize` — does not include Python object overhead |


Total memory occupied by the array.<br> = size × itemsize

In [63]:
array=np.arange(27).reshape(3,3,3)
print(array, "\n")
print("array size: ", array.size, "X", "Item size: ", array.itemsize)
print("total size of array: ", array.nbytes)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 

array size:  27 X Item size:  8
total size of array:  216


<div style="border:2px solid #8B5CF6; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#7C3AED; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">🤖</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">AI Insight — estimating RAM before training</span></div>
<div style="background:#F5F3FF; padding:14px 18px; color:#3B0764; font-size:0.97em; line-height:1.6;">
For a dataset of shape <code>(1_000_000, 128)</code> in <code>float32</code>: <code>nbytes = 1,000,000 × 128 × 4 bytes ≈ 512 MB</code>. Always check this before loading a full dataset into memory — it prevents out-of-memory crashes mid-training.
</div>
</div>

<a id="7-transpose"></a>

<div style="background:#1E2235; border-radius:10px; padding:18px 24px; margin:32px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:16px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="color:#FFFFFF; font-size:1.4em; font-weight:800; min-width:32px;">7.</span>
<div style="display:flex; align-items:center; gap:8px; flex-wrap:wrap;"><code style="background:#2A2F47; color:#E8A84A; font-size:1.15em; font-weight:700; padding:5px 14px; border-radius:6px; letter-spacing:0.3px; font-family:'Courier New',monospace;">arr.T / np.transpose()</code></div>
</div>

> Swaps rows and columns — the axis order is reversed. For a 2-D array, `.T` flips a `(rows, cols)` array into `(cols, rows)`.

| Attribute | Returns | Notes |
|---|---|---|
| `arr.T` | ndarray (view) | Shorthand attribute — no parentheses, returns a *view*, not a copy |
| `np.transpose(arr)` | ndarray (view) | Function form — same result, also accepts an `axes` argument for N-D arrays |


Converts rows into columns and columns into rows.

In [70]:
array= np.array([[25, 50000],
 [30, 60000],
 [35, 75000]])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Method 1 — np.transpose()</span></div>

In [72]:
np.transpose(array)

array([[   25,    30,    35],
       [50000, 60000, 75000]])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Method 2 — .T attribute</span></div>

In [83]:
array.T


array([[   25,    30,    35],
       [50000, 60000, 75000]])

<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">💡</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Tip — .T returns a view, not a copy</span></div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
Modifying the transposed array can affect the original, since <code>.T</code> shares the same underlying memory buffer. Use <code>arr.T.copy()</code> if you need an independent array.
</div>
</div>

<a id="interview-questions"></a>

## 🎤 Interview Questions

---

### 🟢 Beginner

**Q1.** What is the difference between an array **attribute** and a **method**?
<details><summary>▶ Answer</summary>
Attributes describe the array and are accessed without parentheses (e.g. <code>arr.shape</code>). Methods perform an action and require parentheses (e.g. <code>arr.reshape(2,3)</code>).
</details>

**Q2.** For an array with `shape = (3, 4)`, what are `ndim` and `size`?
<details><summary>▶ Answer</summary>
<code>ndim = 2</code> (two axes: rows and columns). <code>size = 12</code> (3 × 4).
</details>

**Q3.** What does an empty tuple `()` mean as a shape?
<details><summary>▶ Answer</summary>
It means the array is <b>0-dimensional</b> — a single scalar value with no axes at all.
</details>

---

### 🟡 Intermediate

**Q4.** How is `nbytes` calculated, and why is it useful in ML workflows?
<details><summary>▶ Answer</summary>
<code>nbytes = size × itemsize</code>. It's used to estimate total RAM/VRAM required before loading a dataset or batch, preventing out-of-memory errors.
</details>

**Q5.** Why does mixing strings and numbers in one array increase `itemsize` dramatically?
<details><summary>▶ Answer</summary>
NumPy needs one dtype for the whole array, so it upcasts everything to a fixed-width unicode string type sized to the longest string — often far larger per element than a number would need.
</details>

**Q6.** Does `arr.T` create a copy of the array?
<details><summary>▶ Answer</summary>
No — it returns a <b>view</b> sharing the same memory. Changing the transposed array can change the original unless you call <code>.copy()</code>.
</details>

---

### 🔴 Advanced

**Q7.** Why might `float32` be preferred over `float64` for large datasets in Deep Learning?
<details><summary>▶ Answer</summary>
<code>float32</code> uses half the memory (4 bytes vs. 8), moves through GPU memory bandwidth faster, and modern GPU tensor cores are optimized for it — with acceptable precision loss for most training tasks.
</details>

**Q8.** How does `np.transpose()` generalize to arrays with more than 2 dimensions?
<details><summary>▶ Answer</summary>
It accepts an <code>axes</code> tuple specifying the new order of axes, e.g. <code>np.transpose(arr, axes=(2,0,1))</code> moves axis 2 to position 0, axis 0 to position 1, etc. Without <code>axes</code>, it reverses the axis order by default.
</details>

**Q9.** If `arr.shape == (2, 2, 2)`, what does each axis represent conceptually, and what is `arr.ndim`?
<details><summary>▶ Answer</summary>
<code>ndim = 3</code>. Conceptually: axis 0 = number of "layers"/blocks, axis 1 = rows within each layer, axis 2 = columns within each row.
</details>

<a id="practice-questions"></a>

## 📝 Practice Questions

*(Try solving each question before running any code.)*

---

### 🟢 Easy

1. Create a 1-D array of 6 integers and print its `shape`, `ndim`, and `size`.
2. Create a 2×3 array of zeros and predict its `nbytes` before running the code (assume `float64`).
3. What is `np.array(5).ndim`? Explain why.
4. Create an array of dtype `int8` and print its `itemsize`.

### 🟡 Medium

5. Create a 3-D array of shape `(2, 3, 4)` using `np.arange(24).reshape(2,3,4)`. Print all six attributes covered in this notebook.
6. Create a 4×4 array and transpose it two different ways. Confirm both results are identical using `np.array_equal()`.
7. Create an array with dtype `object` containing mixed types (int, str, list). Print its `itemsize` and explain the result.
8. Given `arr.nbytes = 800` and `arr.itemsize = 8`, what is `arr.size`?

### 🔴 Hard

9. Write a function `memory_report(arr)` that prints shape, dtype, itemsize, and nbytes in a formatted table using an f-string.
10. Create two arrays with the same `size` but different `shape` (e.g. `(4,6)` and `(2,2,6)`). Confirm they have the same `nbytes` but different `ndim`.
11. Transpose a 3-D array of shape `(2,3,4)` using `np.transpose(arr, axes=(1,2,0))`. Predict the resulting shape before running the code.
12. Estimate the RAM (in GB) needed to hold a `float32` array of shape `(50_000, 512)` without running any code — then verify with `nbytes`.

<a id="mini-challenge"></a>

## 🏆 Mini Challenge — Array Inspector

You're building a small utility that inspects any array before it enters an ML pipeline.

**Complete all 6 steps:**

1. **Create** a random 3-D array of shape `(4, 5, 6)` using `np.random.rand()`.
2. **Print** its `shape`, `ndim`, and `size`.
3. **Convert** it to `dtype='float32'` using `.astype()` and print the new `dtype` and `itemsize`.
4. **Calculate** its `nbytes` and convert the result to megabytes (`nbytes / (1024**2)`).
5. **Transpose** the array so its shape becomes `(6, 5, 4)` — figure out which `axes` argument achieves this.
6. **Print** a one-line memory report: `"Array: shape={shape}, dtype={dtype}, memory={mb:.4f} MB"`.

*(Solutions intentionally omitted — this is a self-check exercise.)*

<a id="summary"></a>

## 📌 Summary

### Key Takeaways

- **Attributes describe, methods act** — attributes never use parentheses (`arr.shape`, not `arr.shape()`).
- **`shape`** is a tuple; its length is the number of dimensions and its values are elements-per-axis.
- **`ndim`** is always `len(arr.shape)`.
- **`size`** is the product of every value in `shape` — the total element count.
- **`dtype`** is shared by every element; mixing types forces upcasting (often to `object` or unicode string).
- **`itemsize`** (bytes per element) × **`size`** = **`nbytes`** (total memory) — critical for RAM/VRAM planning.
- **`.T`** / **`np.transpose()`** reverses axis order and returns a **view**, not a copy.

### Function Quick Reference

| Attribute | Returns | One-line meaning |
|---|---|---|
| `.shape` | tuple | Size along each axis |
| `.ndim` | int | Number of axes |
| `.size` | int | Total element count |
| `.dtype` | dtype | Shared element data type |
| `.itemsize` | int | Bytes per element |
| `.nbytes` | int | Total bytes (`size × itemsize`) |
| `.T` | ndarray view | Axis order reversed |

### What's Next

Continue to array **indexing & slicing**, **reshaping**, and **broadcasting** — the attributes covered here are the foundation for reasoning about all of them.

<a id="references"></a>

## 📚 References

### Official Documentation

- 📖 [NumPy ndarray Attributes](https://numpy.org/doc/stable/reference/arrays.ndarray.html#array-attributes) — Full attribute reference
- 📖 [NumPy Data Types](https://numpy.org/doc/stable/reference/arrays.dtypes.html) — dtype and memory layout rules
- 📖 [numpy.transpose](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html) — Full transpose API including the `axes` argument

### Recommended Reading

- 📘 *Python for Data Analysis* — Wes McKinney
- 📘 *Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow* — Aurélien Géron

### Useful Resources

- 🔗 [NumPy Cheat Sheet (DataCamp)](https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python)

---

<div style="background: linear-gradient(135deg, #1a237e 0%, #01579b 100%); padding: 24px; border-radius: 10px; text-align:center; color:white; font-family:'Segoe UI',sans-serif;">
<b>Thanks for reading!</b> ⭐ Star the repo if this helped — feedback and PRs welcome.
</div>