<div style="background: linear-gradient(135deg, #1a237e 0%, #0d47a1 50%, #01579b 100%); padding: 48px 40px; border-radius: 12px; color: white; font-family: 'Segoe UI', sans-serif; text-align: center;">

<h1 style="font-size: 2.6em; font-weight: 800; margin: 0 0 8px 0; letter-spacing: 1px;">🔧 NumPy Array Operations</h1>
<p style="font-size: 1.2em; margin: 0 0 32px 0; opacity: 0.85;">Complete Guide — Scalar · Vector · Comparison · Logical Operations</p>

<hr style="border: 1px solid rgba(255,255,255,0.3); margin-bottom: 28px;">

<table style="margin: 0 auto; border-collapse: collapse; color: white; font-size: 0.95em;">
<tr>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Author</b>
  Harsh Thakur
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">GitHub</b>
  <a href="https://github.com/HarshAIWorks" style="color:#90CAF9;">HarshAIWorks</a>
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topic</b>
  Array Operations
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Difficulty Level</b>
  Easy
</td>
<td style="padding: 8px 28px;">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topics</b>
  4 Parts
</td>
</tr>
</table>
</div>

## 📑 Table of Contents

| # | Section |
|---|---------|
| 1 | [Part 1 — Scalar Operations](#part1) |
| 2 | [Part 2 — Array-to-Array Operations](#part2) |
| 3 | [Part 3 — Comparison Operations](#part3) |
| 4 | [Part 4 — Logical Operations](#part4) |
| 5 | [⚠️ Common Beginner Mistakes](#mistakes) |
| 6 | [🎤 Interview Questions](#interview-questions) |
| 7 | [📝 Practice Questions](#practice-questions) |
| 8 | [🏆 Mini Challenge](#mini-challenge) |
| 9 | [📌 Summary](#summary) |
| 10 | [📚 References](#references) |

## 🧩 What Are Array Operations?

Array operations allow you to perform calculations directly on NumPy arrays without writing loops

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Without vectorization — the slow way</span></div>

In [4]:
import numpy as np
array= np.arange(4)
print(array)
result= []
for i in array:
    result.append(i+10)

print(result)    

[0 1 2 3]
[np.int64(10), np.int64(11), np.int64(12), np.int64(13)]


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ With vectorization — the NumPy way</span></div>

In [6]:
result = array+10
print(result)

[10 11 12 13]


This is called vectorized computation.<br>Without array operations, AI would be much slower.

<div style="border:2px solid #8B5CF6; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#7C3AED; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">🤖</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">AI Insight — why vectorization matters</span></div>
<div style="background:#F5F3FF; padding:14px 18px; color:#3B0764; font-size:0.97em; line-height:1.6;">
Vectorized operations run in optimized C loops under the hood, avoiding Python's per-element interpreter overhead. This is the difference between training on millions of rows in seconds vs. minutes.
</div>
</div>

<a id="part1"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #E8A84A; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="color:#E8A84A; font-size:1.15em; font-weight:800;">PART 1</span>
<span style="color:#FFFFFF; font-weight:700; font-size:1.15em;">Scalar Operations (Array ± × ÷ Scalar)</span>
</div>

```
      [x   y   z]      
           +         
           5            
           │           
           ▼           
   [x+5  y+5  z+5]      
```

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Base Array</span></div>

We'll use this array throughout the lesson.

In [9]:
array= np.array([10,20,30,40])
print(array)

[10 20 30 40]


<div  style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;"> <h3> ▸1) Addition (+)</span></div>

In [12]:
add= array +5
print(add)


[15 25 35 45]


Every element gets 5 added.<br> <br> 10 + 5 = 15<br>
20 + 5 = 25<br>
30 + 5 = 35<br>
40 + 5 = 45<br><br> Example: Increase every student's score by 5 bonus marks.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;"><h3>▸ 2) Subtraction (-)</span></div>

In [15]:
sub= array-5
print(sub)

[ 5 15 25 35]


Example: Subtract the mean during feature scaling.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;"><h3>▸ 3) Multiplication (*)</span></div>

In [16]:
array * 2

array([20, 40, 60, 80])

Example: Scale values or adjust image brightness.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;"><h3>▸ 4) Division (/)</span></div>

In [19]:
array/2

array([ 5., 10., 15., 20.])

Notice the output becomes float.<br> Example: Normalize image pixels.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;"><h3>▸ 5) Floor Division (//)</span></div>

In [23]:
print("by division:", array/15)
print("by floor division: ",array//15)

by division: [0.66666667 1.33333333 2.         2.66666667]
by floor division:  [0 1 2 2]


Decimals are discarded.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;"><h3>▸ 6) Modulus (%)</span></div>

In [24]:
array%3

array([1, 2, 0, 1])

Returns the remainder.<br> <br> 10 % 3 = 1   (3X3+[1])<br>
20 % 3 = 2   (3X6+[2])<br>
30 % 3 = 0   (3X10+[0])<br>
40 % 3 = 1   (3X13+[1])<br><br> 

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;"><h3>▸ 7) Power (**)</span></div>

In [25]:
array**2


array([ 100,  400,  900, 1600])

<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">💡</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Tip — scalar ops broadcast automatically</span></div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
Every scalar operation above uses NumPy's <b>broadcasting</b> rule: the scalar is conceptually "stretched" to match the array's shape, then applied element-wise — with zero extra memory cost.
</div>
</div>

<a id="part2"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #E8A84A; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="color:#E8A84A; font-size:1.15em; font-weight:800;">PART 2</span>
<span style="color:#FFFFFF; font-weight:700; font-size:1.15em;">Array-to-Array (Vectorized) Operations</span>
</div>

```
[x₁  y₁  z₁]
      +
[x₂  y₂  z₂]
      │
      ▼
[x₁+x₂  y₁+y₂  z₁+z₂]
```

Here, both operands are NumPy arrays.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Base arrays</span></div>

In [27]:
a = np.array([10,20,30])

b = np.array([5,10,15])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;"><h3>▸ Addition</span></div>

In [28]:
a+b

array([15, 30, 45])

(a) &nbsp; &nbsp;(b)<br>10+5<br>
20+10<br>
30+15

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;"><h3>▸ Other operations</span></div>

In [33]:
sub=a-b #Subtraction
mul= a*b # Multiplication
div= a/b #Division
flr= a//b #floor division
mod= a%b  #Modulus

print("array1: ",a)
print("array2: ",b,"\n")

print("sub: ",sub)
print("mul: ",mul)
print("div: ",div)
print("flr: ",flr)
print("mod: ",mod)



array1:  [10 20 30]
array2:  [ 5 10 15] 

sub:  [ 5 10 15]
mul:  [ 50 200 450]
div:  [2. 2. 2.]
flr:  [2 2 2]
mod:  [0 0 0]


<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Warning — element-wise, not matrix multiplication</span></div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
The <code>*</code> operator performs <b>element-wise</b> multiplication. For true matrix multiplication use <code>@</code> or <code>np.matmul()</code> — mixing these up is a very common beginner bug.
</div>
</div>

<a id="part3"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #E8A84A; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="color:#E8A84A; font-size:1.15em; font-weight:800;">PART 3</span>
<span style="color:#FFFFFF; font-weight:700; font-size:1.15em;">Comparison Operations</span>
</div>

These return Boolean arrays.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Base array</span></div>

In [34]:
arr = np.array([10,20,30,40])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;"><h3>▸ 1. Greater Than (>)</span></div>

In [35]:
arr > 20

array([False, False,  True,  True])

Explaination: <br><br>10 > 20 → False<br>

20 > 20 → False<br>

30 > 20 → True<br>

40 > 20 → True<br>

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;"><h3>▸ 2. Less Than (<)</span></div>

In [36]:
arr < 20

array([ True, False, False, False])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;"><h3>▸ 3. Equal To (==)</span></div>

In [37]:
arr == 20

array([False,  True, False, False])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;"><h3>▸ 4. Not Equal (!=)</span></div>

In [38]:
arr != 20

array([ True, False,  True,  True])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;"><h3>▸ 5. Greater Than or Equal (>=)</span></div>

In [39]:
arr >= 20

array([False,  True,  True,  True])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;"><H3> ▸6. Less Than or Equal (<=)</span></div>

In [41]:
arr <= 20

array([ True,  True, False, False])

<div style="border:2px solid #16A34A; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#15803D; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">ℹ️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Info — comparisons return Boolean arrays</span></div>
<div style="background:#F0FDF4; padding:14px 18px; color:#14532D; font-size:0.97em; line-height:1.6;">
Every comparison above returns an array of <code>True</code>/<code>False</code> values, the same shape as the input. This is the foundation of <b>Boolean masking</b>, heavily used for filtering datasets: <code>arr[arr &gt; 20]</code>.
</div>
</div>

<a id="part4"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #E8A84A; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="color:#E8A84A; font-size:1.15em; font-weight:800;">PART 4</span>
<span style="color:#FFFFFF; font-weight:700; font-size:1.15em;">Logical Operations</span>
</div>

Used with Boolean arrays.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Base array</span></div>

In [44]:
Array= np.array(np.arange(10,2))
print(array)

[10 20 30 40]


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;"><H3>▸ 1. AND (&)</span></div>

In [45]:
(arr > 10) & (arr < 40)

array([False,  True,  True, False])

Now compare them element by element.<br><br>

(arr > 10) &emsp;(arr < 40)	&emsp;Result<br><br>
False	&emsp;&emsp;&emsp;&nbsp;True&emsp;&emsp;&emsp;&nbsp;&nbsp;&nbsp;	False<br>
True&nbsp;&nbsp;&nbsp;&emsp;&emsp;	&emsp;True&nbsp;&emsp;&emsp;&emsp;	&nbsp;&nbsp;True<br>
True&nbsp;&nbsp;&nbsp;	&emsp;&emsp;&emsp;True&nbsp;&emsp;	&emsp;&emsp;&nbsp;&nbsp;True<br>
True&nbsp;&nbsp;&nbsp;&emsp;&emsp;&emsp;	False&nbsp;&emsp;&emsp;&emsp;&nbsp;&nbsp;	False

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;"><H3>▸ 2. OR (|)</span></div>

In [46]:
(arr > 10) | (arr < 40)

array([ True,  True,  True,  True])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;"><H3>▸ 3. NOT (~)</span></div>

In [47]:
~(arr > 20)

array([ True,  True, False, False])

<a id="mistakes"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #E8A84A; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="color:#E8A84A; font-size:1.15em; font-weight:800;"><H4>PART ⚠️</span>
<span style="color:#FFFFFF; font-weight:700; font-size:1.15em;"><H3>Common Beginner Mistakes</span>
</div>

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ ❌ Using Python "and" / "or"</span></div>

Wrong:

In [48]:
(arr > 10) and (arr < 40)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Correct: 

In [50]:
(arr > 10) & (arr < 40)

array([False,  True,  True, False])

<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Warning — and/or vs &/|</span></div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
Python's <code>and</code>/<code>or</code> expect a single Boolean, but a NumPy comparison returns an <b>array</b> of Booleans — raising a <code>ValueError: truth value is ambiguous</code>. Always use the bitwise operators <code>&amp;</code> and <code>|</code> on arrays instead.
</div>
</div>

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ ❌ Forgetting Parentheses</span></div>

Wrong: 

In [52]:
arr > 10 & arr < 40

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Correct: 

In [53]:
(arr > 10) & (arr < 40)

array([False,  True,  True, False])

The parentheses ensure each comparison is evaluated before applying the logical operator.

<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">💡</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Tip — operator precedence trap</span></div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
Bitwise operators (<code>&amp;</code>, <code>|</code>) have <b>higher precedence</b> than comparison operators in Python. Without parentheses, <code>arr &gt; 10 &amp; arr &lt; 40</code> is evaluated as <code>arr &gt; (10 &amp; arr) &lt; 40</code> — always wrap each comparison: <code>(arr &gt; 10) &amp; (arr &lt; 40)</code>.
</div>
</div>

<a id="interview-questions"></a>

## 🎤 Interview Questions

---

### 🟢 Beginner

**Q1.** What is a vectorized operation, and why is it faster than a Python loop?
<details><summary>▶ Answer</summary>
A vectorized operation applies a calculation to every array element simultaneously using optimized, compiled C code under the hood — avoiding the overhead of Python's per-iteration interpreter loop.
</details>

**Q2.** What type of array does a comparison operation like <code>arr > 20</code> return?
<details><summary>▶ Answer</summary>
A Boolean array of the same shape, with <code>True</code>/<code>False</code> at each position based on the comparison.
</details>

**Q3.** What does <code>array / 2</code> return if <code>array</code> is an integer array?
<details><summary>▶ Answer</summary>
A <b>float</b> array — division always promotes the result to floating point, even if inputs are integers.
</details>

---

### 🟡 Intermediate

**Q4.** Why does <code>(arr > 10) and (arr < 40)</code> raise an error?
<details><summary>▶ Answer</summary>
Python's <code>and</code> requires a single Boolean value, but each side is an <b>array</b> of Booleans — NumPy can't collapse an array to one truth value, so it raises <code>ValueError: truth value is ambiguous</code>. Use <code>&amp;</code> instead.
</details>

**Q5.** What's the difference between <code>*</code> and <code>@</code> for two 2-D arrays?
<details><summary>▶ Answer</summary>
<code>*</code> is element-wise multiplication (Hadamard product) — shapes must match or broadcast. <code>@</code> (or <code>np.matmul()</code>) is true matrix multiplication, following linear algebra rules.
</details>

**Q6.** Why must comparisons be wrapped in parentheses before combining with <code>&amp;</code> or <code>|</code>?
<details><summary>▶ Answer</summary>
Bitwise operators have higher precedence than comparison operators in Python, so without parentheses the expression is grouped incorrectly, often producing wrong results or an error.
</details>

---

### 🔴 Advanced

**Q7.** How would you use Boolean masking to replace all negative values in an array with 0?
<details><summary>▶ Answer</summary>
<code>arr[arr &lt; 0] = 0</code> — the Boolean mask selects only the negative positions, and assignment updates them in place.
</details>

**Q8.** Why does floor division (<code>//</code>) discard decimals instead of rounding?
<details><summary>▶ Answer</summary>
Floor division always rounds <b>toward negative infinity</b> (truncates the fractional part downward), which differs from standard rounding — important for indices or counts where you always want a whole number ≤ the true quotient.
</details>

**Q9.** What happens when you apply <code>~</code> (NOT) to a Boolean array — does it use Python's <code>not</code> semantics?
<details><summary>▶ Answer</summary>
No — <code>~</code> is the bitwise NOT, which NumPy overloads to flip each Boolean element-wise. Python's <code>not</code> only works on a single value and would error on an array, just like <code>and</code>/<code>or</code>.
</details>

<a id="practice-questions"></a>

## 📝 Practice Questions

*(Try solving each question before running any code.)*

---

### 🟢 Easy

1. Create an array `[1,2,3,4,5]` and add 100 to every element in one line.
2. Create two arrays of the same shape and compute their element-wise product.
3. Given `arr = np.array([5, 15, 25, 35])`, write the comparison that returns `[False, True, True, False]` for values between 10 and 30 (exclusive).
4. What does `np.array([7, 8, 9]) % 2` return, and why?

### 🟡 Medium

5. Fix this broken code: `mask = arr > 5 and arr < 15`.
6. Given `a = np.array([2,4,6])` and `b = np.array([1,2,3])`, compute `a // b` and explain each result.
7. Write a Boolean mask that selects values that are **either** less than 10 **or** greater than 90 in an array `arr`.
8. Explain why `arr ** 2` and `arr * arr` give the same result but `arr @ arr` might not (for a 1-D array, are they the same or different?).

### 🔴 Hard

9. Given a 2-D array of exam scores, write a one-liner using comparison + logical operators to count how many students scored between 60 and 90 inclusive.
10. Create two arrays with different but broadcast-compatible shapes (e.g. `(3,1)` and `(1,4)`) and add them. Predict the resulting shape before running.
11. Using only vectorized operations (no loops), normalize an array to the 0–1 range: `(arr - arr.min()) / (arr.max() - arr.min())`.
12. Explain, using operator precedence rules, why `arr > 10 & arr < 40` fails but `(arr > 10) & (arr < 40)` works — trace through Python's evaluation order.

<a id="mini-challenge"></a>

## 🏆 Mini Challenge — Grade Filter Pipeline

You're building a small grading utility for a class of students.

**Complete all 6 steps:**

1. **Create** an array of 20 random integer scores between 0 and 100 using `np.random.randint(0, 101, 20)`.
2. **Add** a 5-point curve to every score using scalar addition, capping at 100 with `np.clip()`.
3. **Build** a Boolean mask for students who passed (score ≥ 50).
4. **Build** a second mask for students who scored a distinction (score ≥ 85).
5. **Combine** both masks with `&`/`|` to count students who passed but did *not* get a distinction.
6. **Print** a one-line summary: `"Pass rate: {pct:.1f}%, Distinctions: {n}"`.

*(Solutions intentionally omitted — this is a self-check exercise.)*

<a id="summary"></a>

## 📌 Summary

### Key Takeaways

- **Vectorized operations** apply to every array element at once — no explicit loop needed, and they run in optimized C code.
- **Scalar operations** (`+`, `-`, `*`, `/`, `//`, `%`, `**`) broadcast the scalar across every element.
- **Array-to-array operations** apply element-wise when shapes match (or are broadcast-compatible).
- **`*` is element-wise multiplication** — use `@` / `np.matmul()` for true matrix multiplication.
- **Comparison operators** (`>`, `<`, `==`, `!=`, `>=`, `<=`) return Boolean arrays — the basis of masking/filtering.
- **Logical operators must be `&`, `|`, `~`** on arrays — Python's `and`/`or`/`not` will raise errors.
- **Always parenthesize** each comparison before combining with `&`/`|` — bitwise operators bind tighter than comparisons.

### Function Quick Reference

| Category | Operators | Returns |
|---|---|---|
| Scalar arithmetic | `+ - * / // % **` | Array (broadcast) |
| Array-to-array | `+ - * / // %` | Array (element-wise) |
| Comparison | `> < == != >= <=` | Boolean array |
| Logical | `& \| ~` | Boolean array |

### What's Next

Continue to **Boolean masking & fancy indexing**, **broadcasting rules**, and **aggregate functions** (`sum`, `mean`, `std`) — all built directly on the operations covered here.

<a id="references"></a>

## 📚 References

### Official Documentation

- 📖 [NumPy Broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html) — Official broadcasting rules
- 📖 [NumPy Boolean Array Indexing](https://numpy.org/doc/stable/user/basics.indexing.html#boolean-array-indexing) — Masking reference
- 📖 [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) — Matrix multiplication vs. `*`

### Recommended Reading

- 📘 *Python for Data Analysis* — Wes McKinney
- 📘 *Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow* — Aurélien Géron

### Useful Resources

- 🔗 [NumPy Cheat Sheet (DataCamp)](https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python)

---

<div style="background: linear-gradient(135deg, #1a237e 0%, #01579b 100%); padding: 24px; border-radius: 10px; text-align:center; color:white; font-family:'Segoe UI',sans-serif;">
<b>Thanks for reading!</b> ⭐ Star the repo if this helped — feedback and PRs welcome.
</div>