<div style="background: linear-gradient(135deg, #1a237e 0%, #0d47a1 50%, #01579b 100%); padding: 48px 40px; border-radius: 12px; color: white; font-family: 'Segoe UI', sans-serif; text-align: center;">

<h1 style="font-size: 2.6em; font-weight: 800; margin: 0 0 8px 0; letter-spacing: 1px;">🎯 NumPy Indexing & Slicing</h1>
<p style="font-size: 1.2em; margin: 0 0 32px 0; opacity: 0.85;">Complete Guide — 1D/2D/3D Access Patterns · Common Mistakes · Interview Questions</p>

<hr style="border: 1px solid rgba(255,255,255,0.3); margin-bottom: 28px;">

<table style="margin: 0 auto; border-collapse: collapse; color: white; font-size: 0.95em;">
<tr>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Author</b>
  Harsh Thakur
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">GitHub</b>
  <a href="https://github.com/HarshAIWorks" style="color:#90CAF9;">HarshAIWorks</a>
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topic</b>
  Indexing & Slicing
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">AI Importance </b>
   ⭐⭐⭐⭐⭐
</td>
<td style="padding: 8px 28px;">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topics</b>
  2 Parts
</td>
</tr>
</table>
</div>

## 📑 Table of Contents

| # | Section |
|---|---------|
| 1 | [Part 1 — Indexing](#part1) |
| 2 | [Part 2 — Slicing](#part2) |
| 3 | [⚠️ Common Mistakes](#mistakes) |
| 4 | [✅ Best Practices](#best-practices) |
| 5 | [🎤 Interview Questions](#interview-questions) |
| 6 | [📝 Practice Questions](#practice-questions) |
| 7 | [🏆 Mini Challenge](#mini-challenge) |
| 8 | [📌 Summary](#summary) |
| 9 | [📚 References](#references) |

## 🧩 What Is Indexing?

process of accessing a single element from a NumPy array using its position (index).<br>
Indexing in Python starts from 0, not 1.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Why Is It Important?</span></div>

```
In AI, we constantly access:

A particular feature
A specific pixel
A token in a sentence
A row in a dataset
A value in a tensor

Without indexing, working with data would be impossible.
```

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Where Is It Used in AI?</span></div>

```
✅ Machine Learning datasets
✅ Deep Learning tensors
✅ Computer Vision images
✅ NLP token sequences
✅ LLM embeddings
✅ AI Agent memory
```

<div style="border:2px solid #8B5CF6; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#7C3AED; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">🤖</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">AI Insight</span></div>
<div style="background:#F5F3FF; padding:14px 18px; color:#3B0764; font-size:0.97em; line-height:1.6;">
Every tensor operation in PyTorch/TensorFlow, every pandas <code>.iloc[]</code> call, and every image-crop in OpenCV builds on the exact same indexing/slicing rules you are about to learn in NumPy.
</div>
</div>

<a id=<h1> ></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #E8A84A; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="color:#E8A84A; font-size:1.15em; font-weight:800;">PART 1: </span>
<span style="color:#FFFFFF; font-weight:700; font-size:1.15em;">Indexing</span>
</div>

<div style="background:#1E2235; border-radius:10px; padding:14px 22px; margin:28px 0 14px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:12px; border-left:5px solid #3D6FDB;">
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">1D Array Indexing — arr[index]</code>
</div>

In [4]:
import numpy as np

In [5]:
array_1d=np.arange(10,60, step=10)
array_1d

array([10, 20, 30, 40, 50])

```                                 
Index                                 Negative Indexing  
                                                         
 0   1  2  3  4                      -5  -4  -3 - 2  -1  
 ↓   ↓  ↓  ↓  ↓                       ↓   ↓   ↓   ↓   ↓  
[10 20 30 40 50]                     [10  20  30  40  50]
```

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ First and Last Elements</span></div>

In [6]:
first_element= array_1d[0] #0r first_element= array_1d[-5]
last_element= array_1d[-1] #0r last_element= array_1d[4]
print("first: ",first_element)
print("last_element: ",last_element)


first:  10
last_element:  50


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Other Elements — nth element has index n-1</span></div>

In [7]:
second_element= array_1d[1] #0r second_element= array_1d[-4]
third_element= array_1d[2]  #0r third_element= array_1d[-3]
print("second_element: ",second_element)
print("third_element: ",third_element)


second_element:  20
third_element:  30


<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Warning — out-of-range index</span></div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
Accessing an index beyond the array's length raises <code>IndexError</code>. The cell below intentionally demonstrates this — a teaching example.
</div>
</div>

In [8]:
array_1d[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

Because the valid indices are: 0 1 2 3 4

<div style="background:#1E2235; border-radius:10px; padding:14px 22px; margin:28px 0 14px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:12px; border-left:5px solid #3D6FDB;"><h3>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">2D Array Indexing — arr[row, column]</code>
</div>

In [ ]:
array_2d=np.array([[10,20,30],[40,50,60],[70,80,90]])
array_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

```
         Column       
        0   1   2     
      ┌─────────────┐ 
Row 0 │10  20  30 │   
Row 1 │40  50  60 │   
Row 2 │70  80  90 │   
      └─────────────┘ 


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ First Element and Last Element</span></div>

In [ ]:
first=array_2d[0,0]
last=array_2d[-1,-1]

print("First element: ",first)
print("Last element: ",last)


First element:  10
Last element:  90


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Accessing Entire Rows ⭐⭐⭐⭐⭐arr[row] (Most Importanat)</span></div>

In [11]:
row1=array_2d[0] #first row
row2=array_2d[1] #second row

print("row 1: ",row1)
print("row 2: ",row2)


row 1:  [10 20 30]
row 2:  [40 50 60]


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Accessing Entire Columns ⭐⭐⭐⭐⭐ — arr[:, col] (most important)</span></div>

In [13]:
col1= array_2d[:,0] #you will learn in slicing about : this [:] - it means something all 
col_last=array_2d[:,-1]

print("First colums: ",col1)
print("Last colums: ",col_last)

First colums:  [10 40 70]
Last colums:  [30 60 90]


<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">💡</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Tip</span></div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
The <code>:</code> symbol means "all elements along this axis" — you will use it constantly once you reach slicing.
</div>
</div>

<div style="background:#1E2235; border-radius:10px; padding:14px 22px; margin:28px 0 14px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:12px; border-left:5px solid #3D6FDB;"><h3>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">3D Array Indexing — arr[layer, row, column]</code>
</div>

In [ ]:
array_3d= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

```
Layer 0

      col0  col1
row0   1     2
row1   3     4

Layer 1

      col0 col1
row0   5    6
row2   7    8


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ First and Last Element</span></div>

In [ ]:
first=array_3d[0,0,0]
array_3d.shape #(2,2,2) 2 layers, 2 rows, 2 colums.
               # last element: layer 2(index1), row2(index1), col2(index1) ***always index==position-1
last=array_3d[1,1,1]
print("First element: ",first)
print("Last element: ",last)


First element:  1
Last element:  8


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Specific Value</span></div>

Value 4 and Value 6

In [ ]:
# 4 is at layer1 and 2 col, 2 row  *** dont prefer above image of row,col,layer- its already in index form
print(array_3d[0,1,1])
#6 is at layer 2, row 1 and second col
print(array_3d[1,0,1])

4
6


<H3>Common Mistakes

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ ❌ Forgetting That Indexing Starts at 0</span></div>

<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Warning</span></div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
Thinking <code>arr[1]</code> returns the <b>first</b> element. Actually, since indexing starts at <code>0</code>, <code>arr[1]</code> returns the <b>second</b> element.
</div>
</div>

<a id="part2"></a>
<h2>
<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #E8A84A; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="color:#E8A84A; font-size:1.15em; font-weight:800;">PART 2</span>
<span style="color:#FFFFFF; font-weight:700; font-size:1.15em;">Slicing</span>
</div>

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ What Is Slicing?</span></div>

Process of extracting **multiple elements** (a portion of an array) from an existing array.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Why Is It Important?</span></div>

In AI, we rarely work with an entire dataset at once.<br>

We often need to:<br>

Select specific rows<br>
Select specific columns<br>
Crop images<br>
Extract feature columns<br>
Create training and testing datasets<br>
Process batches of data<br>

All of these use slicing.

**Slicing Syntax:**
```
array[start : stop : step]
```

<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">💡</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Golden Rule</span></div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
<b>Start</b> → Included ✅ &nbsp;&nbsp;|&nbsp;&nbsp; <b>Stop</b> → Excluded ❌
</div>
</div>

<div style="background:#1E2235; border-radius:10px; padding:14px 22px; margin:28px 0 14px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:12px; border-left:5px solid #3D6FDB;"><h3>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">1D Array Slicing</code>
</div>

In [2]:
import numpy as np
arr= np.arange(10,70,10)
arr

array([10, 20, 30, 40, 50, 60])

```
0   1   2   3   4   5 : Index
↓   ↓   ↓   ↓   ↓   ↓

10  20  30  40  50  60 : items

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 1. Basic Slicing</span></div>

In [3]:
arr[1:4] #include index 1,2,3 {4; will excluded}

array([20, 30, 40])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 2. From Beginning</span></div>

In [4]:
arr[:4]

array([10, 20, 30, 40])

Since start is omitted: <br>```Start = 0```

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 3. Till End</span></div>

In [5]:
arr[2:]

array([30, 40, 50, 60])

Since stop is omitted:<br>```Go until the last element.```

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 4. Entire Array</span></div>

In [6]:
arr[:]

array([10, 20, 30, 40, 50, 60])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 5. Using Step</span></div>

In [8]:
arr[::2]

array([10, 30, 50])

```Take every 2nd element.```<br><br>Selected indices:
```
   0  
   2  
   4  

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 6. Reverse Array ⭐⭐⭐⭐⭐ (Important) </span></div>

In [11]:
arr[::-1]

array([60, 50, 40, 30, 20, 10])

```
Step = -1
```
Move backwards.

Reverse every second element:

In [14]:
arr[::-2]

array([60, 40, 20])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 7. Negative Slicing</span></div>

```
-6 -5 -4 -3 -2 -1

10 20 30 40 50 60

In [15]:
arr[-4:-1]

array([30, 40, 50])

<div style="background:#1E2235; border-radius:10px; padding:14px 22px; margin:28px 0 14px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:12px; border-left:5px solid #3D6FDB;"><h3>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">2D Array Slicing — arr[row_slice, column_slice]</code>
</div>

In [17]:
arr= np.arange(10,100,10).reshape(3,3)
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

```
          Column       

         0   1   2
       ┌────────────┐
row 0    │10 20 30│
row 1    │40 50 60│
row 2    │70 80 90│
       └────────────┘`

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 1. Rows Only ⭐⭐⭐⭐⭐ (Important) </span></div>

— First Two Rows

In [18]:
arr[:2]

array([[10, 20, 30],
       [40, 50, 60]])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 2. Columns Only ⭐⭐⭐⭐⭐ (Important)</span></div>

First Column

In [19]:
arr[:,0]

array([10, 40, 70])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 3. With Steps</span></div>

a) First and last columns

In [30]:
arr[:,0:3:2]

array([[10, 30],
       [40, 60],
       [70, 90]])

b) First and third row

In [22]:
arr[0:3:2]

array([[10, 20, 30],
       [70, 80, 90]])

c) Every second row

In [28]:
arr[::2]

array([[10, 20, 30],
       [70, 80, 90]])

d) Reverse columns

In [29]:
arr[:,::-1]

array([[30, 20, 10],
       [60, 50, 40],
       [90, 80, 70]])

e) Reverse entire matrix

In [31]:
arr[::-1,::-1]

array([[90, 80, 70],
       [60, 50, 40],
       [30, 20, 10]])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 4. Matrix Selection — Bottom 2×2 Matrix</span></div>

```
          Column       

         0   1   2
       ┌────────────┐
row 0    │        │
row 1    │   50 60│
row 2    │   80 90│
       └────────────┘`

In [27]:
arr[1:3,1:3]

array([[50, 60],
       [80, 90]])

<div style="background:#1E2235; border-radius:10px; padding:14px 22px; margin:28px 0 14px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:12px; border-left:5px solid #3D6FDB;"><h3>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">3D Array Slicing — arr[layer_slice, row_slice, column_slice]</code>
</div>

<div style="border:2px solid #16A34A; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#15803D; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">ℹ️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Info</span></div>
<div style="background:#F0FDF4; padding:14px 18px; color:#14532D; font-size:0.97em; line-height:1.6;">
Earlier, <code>[row_slicing]</code> alone gave you rows — but for a 3D array, that same first position now controls <b>layer</b> slicing instead.
</div>
</div>

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Defining a 3D Array</span></div>

In [42]:
arr=np.arange(1,28).reshape(3,3,3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 1. Layers Only — First Layer</span></div>

In [43]:
arr[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

First and last layer:

In [44]:
arr[0:3:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Rows From Different Layers — First Row of Every Layer</span></div>

In [45]:
arr[:,0,:]

array([[ 1,  2,  3],
       [10, 11, 12],
       [19, 20, 21]])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Columns From Layers — Second Column of Every Layer</span></div>

In [47]:
arr[:,:,1]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

Every second column from every layer:

In [48]:
arr[:,:,0:3:2]

array([[[ 1,  3],
        [ 4,  6],
        [ 7,  9]],

       [[10, 12],
        [13, 15],
        [16, 18]],

       [[19, 21],
        [22, 24],
        [25, 27]]])

<a id="mistakes"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #E8A84A; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="color:#E8A84A; font-size:1.15em; font-weight:800;">PART ⚠️</span>
<span style="color:#FFFFFF; font-weight:700; font-size:1.15em;">Common Mistakes</span>
</div>

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ ❌ Forgetting the Stop Index Is Excluded</span></div>

In [52]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [53]:
arr[1:4]

array([1, 2, 3])

<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Warning</span></div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
Returns indices <b>1, 2, 3</b> — <b>not</b> 4. The stop index is always excluded.
</div>
</div>

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ ❌ Confusing Indexing With Slicing</span></div>

In [55]:
arr[2]

np.int64(2)

One element (a scalar — indexing).

In [57]:
arr[2:3]

array([2])

<div style="border:2px solid #16A34A; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#15803D; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">ℹ️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Info</span></div>
<div style="background:#F0FDF4; padding:14px 18px; color:#14532D; font-size:0.97em; line-height:1.6;">
A sub-array containing one element (slicing). <code>arr[2]</code> returns a scalar; <code>arr[2:3]</code> returns an array — they look similar but are fundamentally different types.
</div>
</div>

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:14px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ ❌ Forgetting the Meaning of Step</span></div>

In [58]:
arr[::2]

array([0, 2, 4])

<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Warning</span></div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
<code>arr[::2]</code> does <b>not</b> mean "start at index 2." It means: take every second element, starting from the beginning.
</div>
</div>

<a id="best-practices"></a>

## ✅ Best Practices

- Use **slicing** instead of loops whenever possible — it is faster and more readable.
- Use **negative slicing** to access elements from the end without knowing the array's length.
- Learn these patterns by heart:

```
arr[:]         # entire array
arr[:5]        # first 5 elements
arr[5:]        # everything from index 5 onward
arr[::2]       # every second element
arr[::-1]      # reversed array
arr[:,0]       # first column (2D)
arr[:,:]       # entire 2D array
arr[:,::-1]    # reverse columns (2D)
```

<a id="interview-questions"></a>

## 🎤 Interview Questions

---

### 🟢 Beginner

**Q1.** What is the difference between indexing and slicing?
<details><summary>▶ Answer</summary>
Indexing accesses a <b>single element</b> and returns a scalar. Slicing extracts a <b>range of elements</b> and always returns an array (even if that array has only one element).
</details>

**Q2.** What does `arr[-1]` return?
<details><summary>▶ Answer</summary>
The <b>last</b> element of the array — negative indices count backwards from the end, starting at -1.
</details>

**Q3.** In `arr[2:5]`, which indices are included?
<details><summary>▶ Answer</summary>
Indices 2, 3, and 4. The stop index (5) is always <b>excluded</b>.
</details>

---

### 🟡 Intermediate

**Q4.** How do you select an entire column from a 2D array?
<details><summary>▶ Answer</summary>
<code>arr[:, col_index]</code> — the <code>:</code> in the row position means "all rows," combined with a single column index.
</details>

**Q5.** What does `arr[::-1]` do, and how is it different from `arr[::-2]`?
<details><summary>▶ Answer</summary>
<code>arr[::-1]</code> reverses the entire array (step -1, moving backwards one at a time). <code>arr[::-2]</code> reverses it while also skipping every other element (step -2).
</details>

**Q6.** For a 3D array, what does the first index position control?
<details><summary>▶ Answer</summary>
The <b>layer</b> (the outermost axis) — unlike a 2D array where the first position controls the row.
</details>

---

### 🔴 Advanced

**Q7.** What is the difference between `arr[2]` and `arr[2:3]` for a 1D array?
<details><summary>▶ Answer</summary>
<code>arr[2]</code> returns a <b>scalar</b> (the single value at index 2). <code>arr[2:3]</code> returns a <b>1-element array</b> — same value, different type/shape.
</details>

**Q8.** How would you select every second column from every layer of a 3D array?
<details><summary>▶ Answer</summary>
<code>arr[:, :, 0::2]</code> — all layers, all rows, then step through columns by 2.
</details>

**Q9.** Why does `arr[1:4]` on `np.arange(5)` return only 3 elements instead of 4?
<details><summary>▶ Answer</summary>
Because the stop index is exclusive: it returns indices 1, 2, 3 — three elements — not index 4.
</details>

<a id="practice-questions"></a>

## 📝 Practice Questions

*(Try solving each question before running any code.)*

---

### 🟢 Easy

1. Create a 1D array of 8 elements and print its first and last elements using negative indexing.
2. Given a 3×3 2D array, extract the entire second row.
3. Given a 3×3 2D array, extract the entire last column.
4. Slice a 1D array to get every element except the first and last.

### 🟡 Medium

5. Given `arr = np.arange(20)`, write a slice that returns every third element in reverse order.
6. Given a 4×4 2D array, extract the bottom-right 2×2 sub-matrix.
7. Given a 3D array of shape `(2,3,3)`, extract the first row from every layer.
8. Explain the output difference between `arr[3]` and `arr[3:4]` for any 1D array.

### 🔴 Hard

9. Given a 3D array of shape `(3,4,4)`, write a slice that reverses the layer order but keeps rows/columns unchanged.
10. Write a slice expression to extract every other column from every other row of a 2D array.
11. Given `arr = np.arange(30).reshape(5,6)`, extract a checkerboard-like sub-selection using two chained slices.
12. Explain why `arr[::2]` and `arr[0::2]` produce the same result, but `arr[1::2]` does not.

<a id="mini-challenge"></a>

## 🏆 Mini Challenge — Image Crop Simulator

You're simulating a basic image-cropping tool using a 3D NumPy array representing an RGB image.

**Complete all 6 steps:**

1. **Create** a `(6, 6, 3)` array with `np.arange(108).reshape(6,6,3)` representing a 6×6 RGB image.
2. **Extract** the top-left 3×3 pixel region (all 3 color channels).
3. **Extract** only the red channel (index 0) of the entire image using slicing.
4. **Flip** the image horizontally using a slice with a negative step.
5. **Extract** every other row and every other column (a simple "downsample").
6. **Print** the shape of each result to confirm your slices worked as expected.



### Function Quick Reference

| Pattern | Meaning |
|---|---|
| `arr[i]` | Single element at index i |
| `arr[i:j]` | Elements from i (included) to j (excluded) |
| `arr[::k]` | Every kth element |
| `arr[::-1]` | Reversed array |
| `arr[:, c]` | Entire column c (2D) |
| `arr[r, :]` | Entire row r (2D) |
| `arr[l, :, :]` | Entire layer l (3D) |

<a id="references"></a>

## 📚 References

### Official Documentation

- 📖 [NumPy Indexing on ndarrays](https://numpy.org/doc/stable/user/basics.indexing.html) — Official indexing & slicing reference
- 📖 [Basic Slicing and Indexing](https://numpy.org/doc/stable/reference/arrays.indexing.html) — Full API details

### Recommended Reading

- 📘 *Python for Data Analysis* — Wes McKinney
- 📘 *Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow* — Aurélien Géron

### Useful Resources

- 🔗 [NumPy Cheat Sheet (DataCamp)](https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python)

---

<div style="background: linear-gradient(135deg, #1a237e 0%, #01579b 100%); padding: 24px; border-radius: 10px; text-align:center; color:white; font-family:'Segoe UI',sans-serif;">
<b>Thanks for reading!</b> ⭐ Star the repo if this helped — feedback and PRs welcome.
</div>