<div style="background: linear-gradient(135deg, #1a237e 0%, #0d47a1 50%, #01579b 100%); padding: 48px 40px; border-radius: 12px; color: white; font-family: 'Segoe UI', sans-serif; text-align: center;">

<h1 style="font-size: 2.6em; font-weight: 800; margin: 0 0 8px 0; letter-spacing: 1px;">🧠 NumPy Copy vs View</h1>
<p style="font-size: 1.2em; margin: 0 0 32px 0; opacity: 0.85;">Understanding shared memory, independent copies, and when each appears</p>

<hr style="border: 1px solid rgba(255,255,255,0.3); margin-bottom: 28px;">

<table style="margin: 0 auto; border-collapse: collapse; color: white; font-size: 0.95em;">
<tr>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Author</b>
  Harsh Thakur
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">GitHub</b>
  <a href="https://github.com/HarshAIWorks" style="color:#90CAF9;">HarshAIWorks</a>
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topic</b>
  Copy vs View
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Difficulty</b>
  Beginner → Intermediate
</td>
<td style="padding: 8px 28px;">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topics</b>
  Memory Fundamentals
</td>
</tr>
</table>
</div>

## 📑 Table of Contents

| # | Section |
|---|---------|
| 1 | [View — Shared Memory](#fn-1) |
| 2 | [Copy — Independent Memory](#fn-2) |
| 3 | [Operations: View vs Copy](#fn-3) |
| 4 | [🎤 Interview Questions](#interview-questions) |
| 5 | [📝 Practice Questions](#practice-questions) |
| 6 | [🏆 Mini Challenge](#mini-challenge) |
| 7 | [📌 Summary](#summary) |
| 8 | [📚 References](#references) |

<div style="border:2px solid #8B5CF6; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#7C3AED; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">🤖</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">AI Insight</span></div>
<div style="background:#F5F3FF; padding:14px 18px; color:#3B0764; font-size:0.97em; line-height:1.6;">
NumPy is built for speed and low memory usage. Understanding the copy/view distinction lets you avoid silent data corruption (modifying a view you thought was a copy) and unnecessary memory overhead (copying large arrays you could have shared).
</div>
</div>

**Copy** — two independent arrays, each with their own memory:
```
arr        copy_arr
 │              │
 ▼              ▼
[10 20 30]  [10 20 30]
```
Changing one does **not** affect the other.

**View** — two Python objects pointing at the same underlying data:
```
           ┌───────────────┐
arr ──────►│  [10 20 30]   │
view_arr ─►│               │
           └───────────────┘
```
Changing one **does** affect the other.

<a id="fn-1"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">1</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">View — Shared Memory</code>
</div>

A **view** is a new NumPy array object that shares the exact same data buffer as the original. Created with `arr.view()` or produced automatically by slicing.

In [ ]:
import numpy as np 
arr = np.array([10,20,30,40]) 
view_arr = arr.view() 
view_arr[0]=111
print(view_arr)
arr is view_arr
print(id(arr))
id(view_arr)
arr

[111  20  30  40]
2101178607792


array([111,  20,  30,  40])

```
Python Object 1 (arr)
        │
        ▼
   ┌──────────────┐
   │ Data Buffer  │  ← same memory block
   │ 10 20 30 40  │
   └──────────────┘
        ▲
        │
Python Object 2 (view_arr)
```
`arr` and `view_arr` are different Python objects (`id()` differs), but they share the same underlying data buffer.

<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Common Misconception</span></div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
<code>id(arr) != id(view_arr)</code> — they are different Python objects. <b>Don't</b> use <code>id()</code> to check memory sharing; it compares object identity, not data buffer identity.
</div>
</div>

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Proving Shared Memory</span></div>

<div style="margin:10px 0 4px 0; font-family:'Segoe UI',sans-serif;"><span style="color:#64748B; font-weight:600; font-size:0.88em; font-style:italic;">— Method 1 (Recommended) — .base</span></div>

In [ ]:
print(view_arr.base is arr)

True


`True` confirms `view_arr` is backed by `arr`'s data.

<div style="margin:10px 0 4px 0; font-family:'Segoe UI',sans-serif;"><span style="color:#64748B; font-weight:600; font-size:0.88em; font-style:italic;">— Method 2 (Definitive) — .ctypes.data buffer address</span></div>

In [ ]:
print(arr.ctypes.data)
print(view_arr.ctypes.data)

2101157607696
2101157607696


```
id()          — compares Python objects        (NOT reliable for memory check)
.ctypes.data  — compares the actual data buffer address  
.base         — tells you whether the array shares memory 
```

<a id="fn-2"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">2</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">Copy — Independent Memory</code>
</div>

A **copy** creates a brand-new array with its own allocated data buffer. Changes to the copy never affect the original, and vice versa.

In [ ]:
copy_arr = arr.copy()
copy_arr


array([111,  20,  30,  40])

```
arr           copy_arr
 │                 │
 ▼                 ▼
[10 20 500 40]  [10 200 30 40]
```
Two completely separate memory locations — modifying either has no effect on the other.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Confirming with .base</span></div>

In [ ]:
print(copy_arr.base)

None


`None` means `copy_arr` owns its own data and shares memory with nothing.

<a id="fn-3"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">3</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">Operations: View vs Copy ⭐⭐⭐⭐⭐</code>
</div>

| Operation | Returns |
|---|---|
| `arr.view()` | ✅ View |
| Basic slicing `arr[:]` | ✅ View |
| `reshape()` / `ravel()` | ✅ View *(usually — copy if layout forces it)* |
| `transpose()` / `.T` | ✅ View |
| `arr.copy()` | ✅ Copy |
| Fancy indexing `arr[[0,2]]` | ✅ Copy |
| Boolean masking `arr[arr > 5]` | ✅ Copy |
| Arithmetic `arr + 5`, `arr * 2` | ✅ Copy |
| `flatten()` | ✅ Copy |

<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">💡</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Quick Rule</span></div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
<b>Slicing → View.</b> Everything that jumps around non-contiguously (fancy indexing, boolean masking) → Copy. Arithmetic → Copy (new values).
</div>
</div>

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 1 — Slicing Returns a View</span></div>

In [ ]:
arr = np.array([10,20,30,40,50])
slc=arr[:4]
slc[0]=101
arr

array([101,  20,  30,  40,  50])

Modifying `slc[0]` changed `arr` too — proof that slicing is a view. This is by design: it lets you efficiently edit a *window* into the original.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 2 — Fancy Indexing Returns a Copy</span></div>

In [ ]:
arr = np.array([10,20,30,40])
fnc=arr[[1,3]]
fnc[1]=100
print(arr)
fnc


[10 20 30 40]


array([ 20, 100])

`arr` is unchanged — fancy indexing always returns an independent copy.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 3 — Boolean Masking Returns a Copy</span></div>

In [ ]:
fil = arr[arr > 20]
fil[0] = 999
print(arr)

[10 20 30 40]


Same result: `arr` is unchanged because boolean masking returns a copy.

<a id="interview-questions"></a>

## 🎤 Interview Questions

---

### 🟢 Beginner

**Q1.** What is the key difference between a view and a copy?
<details><summary>▶ Answer</summary>
A view shares the underlying data buffer with the original array — modifying one modifies the other. A copy has its own independent buffer — changes are isolated.
</details>

**Q2.** How do you create a view and a copy of an array?
<details><summary>▶ Answer</summary>
View: <code>arr.view()</code> or a basic slice like <code>arr[1:4]</code>. Copy: <code>arr.copy()</code>.
</details>

**Q3.** What does `copy_arr.base` return for a copy, and what does it return for a view?
<details><summary>▶ Answer</summary>
For a copy: <code>None</code> — it owns its own data. For a view: the original array it borrows data from.
</details>

---

### 🟡 Intermediate

**Q4.** Why can't you use `id()` to check whether two arrays share memory?
<details><summary>▶ Answer</summary>
<code>id()</code> returns the identity of the Python object, not the address of the underlying data buffer. A view is a <i>different</i> Python object (different <code>id</code>) that happens to point at the same raw memory.
</details>

**Q5.** Does slicing a 2D array with `arr[:2, :]` return a view or a copy?
<details><summary>▶ Answer</summary>
A view — basic slicing (using <code>:</code> notation) always returns a view in NumPy.
</details>

**Q6.** Does `arr.flatten()` return a view or a copy? How about `arr.ravel()`?
<details><summary>▶ Answer</summary>
<code>flatten()</code> always returns a copy. <code>ravel()</code> returns a view whenever possible; it falls back to a copy only if the array's memory layout prevents sharing.
</details>

---

### 🔴 Advanced

**Q7.** You slice an array and pass the slice to a function that modifies it. The original array changes unexpectedly. What happened and how do you prevent it?
<details><summary>▶ Answer</summary>
The slice is a view — in-place modifications propagate back to the original. To prevent it, explicitly pass <code>arr[1:4].copy()</code> into the function.
</details>

**Q8.** Why does fancy indexing always return a copy instead of a view?
<details><summary>▶ Answer</summary>
The selected elements may be scattered non-contiguously in memory (e.g. <code>arr[[0,5,3]]</code>). NumPy can only create a view over contiguous or regularly-strided memory; arbitrary index lists can't be described that way, so a copy is the only option.
</details>

**Q9.** How can you determine at runtime whether `b = some_operation(arr)` produced a view or a copy?
<details><summary>▶ Answer</summary>
Check <code>b.base is arr</code> — if <code>True</code>, it's a view sharing <code>arr</code>'s data. If <code>False</code> (i.e. <code>b.base is None</code> or another object), it's a copy or a view of something else.
</details>

<a id="practice-questions"></a>

## 📝 Practice Questions

*(Try solving each question before running any code.)*

---

### 🟢 Easy

1. Create a 1D array and a view of it. Modify an element in the view and confirm the original changed.
2. Create a copy of the same array. Modify an element in the copy and confirm the original did **not** change.
3. Use `.base` on both the view and the copy and note what each returns.
4. Create a slice `arr[2:5]` and verify it is a view using `.base`.

### 🟡 Medium

5. Create a `(4,4)` array. Slice rows 1–3 and modify element `[0,0]` of the slice. Does the original change?
6. Create a `(3,3)` array. Use fancy indexing `arr[[0,2]]` to get two rows. Modify the result. Does the original change?
7. Use `arr.ravel()` and check `.base` — is it a view or a copy? Then use `arr.flatten()` and check again.
8. Do `arr.reshape(1, -1)` and check `.base`. Repeat on a Fortran-contiguous array (`np.asfortranarray(arr)`) — does the result change?

### 🔴 Hard

9. Write a function `is_view(original, result)` that returns `True` if `result` is a view of `original`, using `.base` and `.ctypes.data`.
10. Explain why `arr.T` is a view but `arr.T.copy()` is obviously a copy — and why you'd need the `.copy()` when passing a transposed array to a function that expects C-contiguous memory.
11. Given a large `(10000, 10000)` array, explain when you'd prefer a view over a copy for a downstream computation, and when you'd be forced to use a copy regardless.
12. Why does `arr * 2` always produce a copy, even though `*= 2` modifies in place? How does this relate to Python's object model?

<a id="mini-challenge"></a>

## 🏆 Mini Challenge — Memory Detective

You're debugging a data pipeline where arrays are being modified unexpectedly.

**Complete all 4 steps:**

1. **Create** a `(4,4)` array `data` with values 1–16.
2. **Build** three derived arrays from it: a slice `s = data[:2, :]`, a fancy-indexed version `f = data[[0,2]]`, and a boolean-masked version `b = data[data > 8]`.
3. **Test** each one: is it a view or a copy? Print `s.base is data`, `f.base is data`, `b.base is data`.
4. **Modify** `s[0,0] = 999` and `f[0,0] = 999` — check which ones propagate back into `data`. Explain why the results differ.

*(Solutions intentionally omitted — this is a self-check exercise.)*

<a id="summary"></a>

## 📌 Summary

- A **view** shares the original array's data buffer — fast and memory-efficient, but in-place changes propagate.
- A **copy** owns independent memory — safe to modify, at the cost of extra allocation.
- Use `.base` and `.ctypes.data` to diagnose memory sharing; never rely on `id()`.

| Operation | View or Copy? |
|---|---|
| Basic slicing `arr[a:b]` | View |
| `arr.view()` | View |
| `reshape()` / `ravel()` | View *(usually)* |
| `transpose()` / `.T` | View |
| `arr.copy()` / `flatten()` | Copy |
| Fancy indexing | Copy |
| Boolean masking | Copy |
| Arithmetic `arr + n` | Copy |

**What's next:** The random module — generating reproducible data for experiments and simulations.

<a id="references"></a>

## 📚 References

### Official Documentation

- 📖 [NumPy Copies and Views](https://numpy.org/doc/stable/user/basics.copies.html)
- 📖 [ndarray.base](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.base.html)
- 📖 [ndarray.ctypes](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.ctypes.html)

### Recommended Reading

- 📘 *Python for Data Analysis* — Wes McKinney

### Useful Resources

- 🔗 [NumPy Cheat Sheet (DataCamp)](https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python)

---

<div style="background: linear-gradient(135deg, #1a237e 0%, #01579b 100%); padding: 24px; border-radius: 10px; text-align:center; color:white; font-family:'Segoe UI',sans-serif;">
<b>Thanks for reading!</b> ⭐ Star the repo if this helped — feedback and PRs welcome.
</div>