<div style="background: linear-gradient(135deg, #1a237e 0%, #0d47a1 50%, #01579b 100%); padding: 48px 40px; border-radius: 12px; color: white; font-family: 'Segoe UI', sans-serif; text-align: center;">

<h1 style="font-size: 2.6em; font-weight: 800; margin: 0 0 8px 0; letter-spacing: 1px;">🎲 NumPy Random Module</h1>
<p style="font-size: 1.2em; margin: 0 0 32px 0; opacity: 0.85;">seed · rand · randn · randint · choice · shuffle · permutation</p>

<hr style="border: 1px solid rgba(255,255,255,0.3); margin-bottom: 28px;">

<table style="margin: 0 auto; border-collapse: collapse; color: white; font-size: 0.95em;">
<tr>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Author</b>
  Harsh Thakur
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">GitHub</b>
  <a href="https://github.com/HarshAIWorks" style="color:#90CAF9;">HarshAIWorks</a>
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topic</b>
  Random Module
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Difficulty</b>
  Beginner → Intermediate
</td>
<td style="padding: 8px 28px;">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topics</b>
  7 Functions
</td>
</tr>
</table>
</div>

## 📑 Table of Contents

| # | Function |
|---|---------|
| 1 | [np.random.seed()](#fn-1) |
| 2 | [np.random.rand()](#fn-2) |
| 3 | [np.random.randn()](#fn-3) |
| 4 | [np.random.randint()](#fn-4) |
| 5 | [np.random.choice()](#fn-5) |
| 6 | [np.random.shuffle()](#fn-6) |
| 7 | [np.random.permutation()](#fn-7) |
| 8 | [Mistakes & Best Practices](#fn-8) |
| 9 | [🎤 Interview Questions](#interview-questions) |
| 10 | [📝 Practice Questions](#practice-questions) |
| 11 | [🏆 Mini Challenge](#mini-challenge) |
| 12 | [📌 Summary](#summary) |
| 13 | [📚 References](#references) |

| Function | Purpose |
|---|---|
| `np.random.seed()` | Reproducible results |
| `np.random.rand()` | Random floats in \[0, 1) |
| `np.random.randn()` | Normal distribution (mean=0, std=1) |
| `np.random.randint()` | Random integers in a range |
| `np.random.choice()` | Random sampling from an array |
| `np.random.shuffle()` | Shuffle array **in place** |
| `np.random.permutation()` | Return a shuffled **copy** |

<div style="border:2px solid #8B5CF6; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#7C3AED; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">🤖</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">AI Insight</span></div>
<div style="background:#F5F3FF; padding:14px 18px; color:#3B0764; font-size:0.97em; line-height:1.6;">
The Random module is your go-to for data augmentation, train/test splits, weight initialization, and simulating datasets. <code>seed()</code> is the one function you should call at the top of <b>every</b> ML experiment.
</div>
</div>

<a id="fn-1"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">1</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">np.random.seed()</code>
</div>

Fixes the internal random state so the same sequence of "random" numbers is generated every time the code runs — essential for reproducible experiments.

In [ ]:
import numpy as np 
np.random.seed(42) 
print(np.random.rand(5))

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Without seed — results change every run</span></div>

In [ ]:
print(np.random.rand(7))

[0.18182497 0.18340451 0.30424224 0.52475643 0.43194502 0.29122914
 0.61185289]


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ With seed(42) — same result every time</span></div>

In [ ]:
np.random.seed(42) 
print(np.random.rand(7))

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361]


<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">💡</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">How It Works</span></div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
You can pass any integer as the seed value. Using the same seed always produces the same sequence — the number itself is arbitrary; consistency is all that matters.
</div>
</div>

<a id="fn-2"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">2</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">np.random.rand()</code>
</div>

Returns random floating-point numbers **uniformly distributed between 0 and 1** (never equals 1).

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 1D Array</span></div>

In [ ]:
np.random.rand(5)

array([0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 2D Array</span></div>

In [ ]:
np.random.rand(2,3)

array([[0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465]])

<a id="fn-3"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">3</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">np.random.randn()</code>
</div>

Returns random numbers drawn from a **standard Normal (Gaussian) distribution** — mean ≈ 0, standard deviation ≈ 1.

In [ ]:
np.random.randn(5)

array([-0.7033438 , -2.13962066, -0.62947496,  0.59772047,  2.55948803])

<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">💡</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">rand vs randn</span></div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
<b>rand()</b> → flat/uniform distribution between 0 and 1 — every value equally likely.<br><b>randn()</b> → bell-curve distribution centred at 0 — values near 0 are far more likely than extreme values.
</div>
</div>

<a id="fn-4"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">4</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">np.random.randint()</code>
</div>

Returns random **integers** within a specified range.

**Syntax:** `np.random.randint(low, high, size)` — generates integers from `low` (inclusive) to `high` (exclusive).

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 1D Example</span></div>

```python
np.random.randint(1, 10, 5)   # 5 integers from 1–9
```

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 2D Example</span></div>

```python
np.random.randint(0, 100, (3, 4))   # 3×4 matrix of integers 0–99
```

<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Common Mistake</span></div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
The <code>high</code> bound is <b>exclusive</b>: <code>randint(1, 10)</code> produces integers 1–9, never 10.
</div>
</div>

<a id="fn-5"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">5</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">np.random.choice()</code>
</div>

Randomly **samples** one or more values from an existing array or integer range.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Pick One</span></div>

In [ ]:
colors = ["Red","Blue","Green"] 
np.random.choice(colors)

np.str_('Blue')

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Pick Multiple (with replacement by default)</span></div>

In [ ]:
np.random.choice(colors,3)

array(['Red', 'Blue', 'Blue'], dtype='<U5')

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Without Replacement</span></div>

In [ ]:
np.random.choice(colors,3,replace=False)

array(['Green', 'Red', 'Blue'], dtype='<U5')

<div style="border:2px solid #8B5CF6; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#7C3AED; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">🤖</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">AI Insight</span></div>
<div style="background:#F5F3FF; padding:14px 18px; color:#3B0764; font-size:0.97em; line-height:1.6;">
Use <code>choice()</code> with <code>replace=False</code> to create random train/validation splits, or to sample a mini-batch from a dataset.
</div>
</div>

<a id="fn-6"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">6</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">np.random.shuffle()</code>
</div>

Shuffles an array **in place** — the original array is modified directly; nothing is returned.

In [ ]:
arr = np.array([1,2,3,4,5]) 
np.random.shuffle(arr) 
print(arr)

[4 3 5 1 2]


In [ ]:
arr

array([4, 3, 5, 1, 2])

<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Important</span></div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
<code>shuffle()</code> modifies the original array and returns <code>None</code>. If you need to keep the original intact, use <code>permutation()</code> instead.
</div>
</div>

<a id="fn-7"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">7</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">np.random.permutation()</code>
</div>

Returns a **shuffled copy** of the array — the original is untouched.

In [ ]:
arr = np.array([1,2,3,4,5]) 
new_arr = np.random.permutation(arr) 
print(arr) 
print(new_arr)

[1 2 3 4 5]
[1 2 5 3 4]


<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">💡</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">shuffle vs permutation</span></div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
<b>shuffle(arr)</b> — modifies <code>arr</code> in place, returns <code>None</code>.<br><b>permutation(arr)</b> — returns a new shuffled copy, leaves <code>arr</code> unchanged.
</div>
</div>

<a id="fn-8"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">8</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">Mistakes & Best Practices</code>
</div>

<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Common Mistake — Forgetting seed()</span></div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
Without a seed, results change on every run — making experiments impossible to reproduce or debug.
</div>
</div>

<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Common Mistake — Expecting rand() to return integers</span></div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
<code>rand()</code> always returns floats in [0, 1). Use <code>randint()</code> for integers.
</div>
</div>

<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">✅</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Best Practices</span></div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
Use <code>seed()</code> at the top of every ML experiment for reproducibility.<br>Use <code>permutation()</code> when you need to keep the original array unchanged.<br>Use <code>shuffle()</code> only when modifying the original in place is acceptable.<br>Use <code>choice(replace=False)</code> for train/test splits and mini-batch sampling.
</div>
</div>

<a id="interview-questions"></a>

## 🎤 Interview Questions

---

### 🟢 Beginner

**Q1.** What does `np.random.seed(42)` do, and why would you use it?
<details><summary>▶ Answer</summary>
It fixes NumPy's internal random state so that all subsequent random calls produce the same sequence of numbers every time the code runs — making results reproducible and experiments debuggable.
</details>

**Q2.** What's the difference between `np.random.rand()` and `np.random.randint()`?
<details><summary>▶ Answer</summary>
<code>rand()</code> returns floats uniformly distributed in [0, 1). <code>randint(low, high)</code> returns integers in the range [low, high) — the high bound is exclusive.
</details>

**Q3.** What does `np.random.shuffle()` return?
<details><summary>▶ Answer</summary>
<code>None</code> — it shuffles the array in place and returns nothing. This is a common gotcha: writing <code>arr = np.random.shuffle(arr)</code> sets <code>arr</code> to <code>None</code>.
</details>

---

### 🟡 Intermediate

**Q4.** What's the difference between `shuffle()` and `permutation()`?
<details><summary>▶ Answer</summary>
<code>shuffle(arr)</code> modifies <code>arr</code> in place and returns <code>None</code>. <code>permutation(arr)</code> leaves <code>arr</code> unchanged and returns a new shuffled copy.
</details>

**Q5.** What distribution does `np.random.randn()` sample from, and what does that mean practically?
<details><summary>▶ Answer</summary>
It samples from a standard Normal (Gaussian) distribution with mean 0 and standard deviation 1. Practically, values near 0 are far more likely than values far from 0 — unlike <code>rand()</code>, which gives every value in [0,1) an equal chance.
</details>

**Q6.** How would you sample 3 unique items from a list using `np.random.choice()`?
<details><summary>▶ Answer</summary>
<code>np.random.choice(items, 3, replace=False)</code> — setting <code>replace=False</code> ensures no item is selected more than once.
</details>

---

### 🔴 Advanced

**Q7.** If you call `np.random.seed(0)` and then generate 5 random numbers, then call `seed(0)` again and generate 5 more, are the two sequences identical?
<details><summary>▶ Answer</summary>
Yes — resetting the seed to the same value resets the internal state to the same starting point, so every subsequent call produces the same sequence.
</details>

**Q8.** Why is calling `np.random.seed()` at the top of a notebook sometimes not enough for full reproducibility in a machine learning pipeline?
<details><summary>▶ Answer</summary>
Other libraries (Python's built-in <code>random</code>, TensorFlow, PyTorch, etc.) have separate random states. Full reproducibility requires setting seeds in each library independently, and also controlling OS-level randomness.
</details>

**Q9.** You want to randomly split a dataset of 1000 samples into 80% train / 20% test without replacement. Write the approach using `np.random.permutation()`.
<details><summary>▶ Answer</summary>
<code>indices = np.random.permutation(1000); train, test = indices[:800], indices[800:]</code> — shuffle all indices, then slice. Using <code>permutation</code> (not <code>shuffle</code>) keeps the original index array intact.
</details>

<a id="practice-questions"></a>

## 📝 Practice Questions

*(Try solving each question before running any code.)*

---

### 🟢 Easy

1. Set seed to `7` and generate a `(3,3)` matrix of random floats between 0 and 1.
2. Generate 10 random integers between 1 and 100 (inclusive at 1, exclusive at 101).
3. Randomly pick a single element from `["cat", "dog", "fish", "bird"]`.
4. Shuffle a 1D array `[10, 20, 30, 40, 50]` in place and print it.

### 🟡 Medium

5. Generate a `(4,4)` matrix using `randn()`. What is the approximate mean of all elements?
6. Use `choice()` with `replace=False` to randomly sample 3 unique elements from a 10-element array.
7. Demonstrate the difference between `shuffle()` and `permutation()` — show that `shuffle()` modifies the original while `permutation()` does not.
8. Generate the same 5 random integers twice by resetting the seed between calls.

### 🔴 Hard

9. Simulate rolling a 6-sided die 1000 times and compute the frequency of each outcome using `randint()` and `np.unique()`.
10. Randomly split an array of 200 sample indices into 70% train, 15% validation, 15% test using `permutation()`.
11. Using only `rand()` and arithmetic, generate random integers between 10 and 50 (without using `randint()`).
12. Write code that uses `choice(replace=False)` to create a random 5-fold cross-validation split of a 100-sample dataset.

<a id="mini-challenge"></a>

## 🏆 Mini Challenge — Reproducible Experiment

You need to set up a reproducible random data pipeline for a binary classification experiment.

**Complete all 4 steps:**

1. **Set** `np.random.seed(99)` to lock reproducibility for the entire pipeline.
2. **Generate** 100 feature vectors of shape `(100, 5)` using `randn()` (5 features, normally distributed).
3. **Create** 100 binary labels (`0` or `1`) using `randint(0, 2, 100)`.
4. **Split** the 100 samples into train (80%) and test (20%) using `permutation()` to shuffle indices, then slice — confirm both sets are non-overlapping and together cover all 100 samples.

*(Solutions intentionally omitted — this is a self-check exercise.)*

<a id="summary"></a>

## 📌 Summary

- **seed()** fixes reproducibility — call it once at the top of every experiment.
- **rand()** → uniform floats in [0, 1). **randn()** → Gaussian floats (mean=0, std=1). **randint()** → integers in [low, high).
- **choice()** samples from an existing array; `replace=False` prevents duplicates.
- **shuffle()** modifies in place, returns `None`. **permutation()** returns a new shuffled copy.

| Function | Output | Modifies Original? |
|---|---|---|
| `seed(n)` | None (sets state) | N/A |
| `rand(shape)` | Floats [0, 1) | No |
| `randn(shape)` | Gaussian floats | No |
| `randint(lo, hi, size)` | Integers [lo, hi) | No |
| `choice(arr, n)` | Sampled values | No |
| `shuffle(arr)` | None | **Yes** |
| `permutation(arr)` | Shuffled copy | No |

**What's next:** Stacking and concatenating arrays — combining data from multiple sources.

<a id="references"></a>

## 📚 References

### Official Documentation

- 📖 [numpy.random (legacy)](https://numpy.org/doc/stable/reference/random/legacy.html)
- 📖 [numpy.random.seed](https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html)
- 📖 [numpy.random.choice](https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html)

### Recommended Reading

- 📘 *Python for Data Analysis* — Wes McKinney

### Useful Resources

- 🔗 [NumPy Cheat Sheet (DataCamp)](https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python)

---

<div style="background: linear-gradient(135deg, #1a237e 0%, #01579b 100%); padding: 24px; border-radius: 10px; text-align:center; color:white; font-family:'Segoe UI',sans-serif;">
<b>Thanks for reading!</b> ⭐ Star the repo if this helped — feedback and PRs welcome.
</div>