<div style="background: linear-gradient(135deg, #1a237e 0%, #0d47a1 50%, #01579b 100%); padding: 48px 40px; border-radius: 12px; color: white; font-family: 'Segoe UI', sans-serif; text-align: center;">

<h1 style="font-size: 2.6em; font-weight: 800; margin: 0 0 8px 0; letter-spacing: 1px;">📦 NumPy Stacking</h1>
<p style="font-size: 1.2em; margin: 0 0 32px 0; opacity: 0.85;">concatenate · vstack · hstack · column_stack · dstack</p>

<hr style="border: 1px solid rgba(255,255,255,0.3); margin-bottom: 28px;">

<table style="margin: 0 auto; border-collapse: collapse; color: white; font-size: 0.95em;">
<tr>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Author</b>
  Harsh Thakur
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">GitHub</b>
  <a href="https://github.com/HarshAIWorks" style="color:#90CAF9;">HarshAIWorks</a>
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topic</b>
  Stacking
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Difficulty</b>
  Beginner → Intermediate
</td>
<td style="padding: 8px 28px;">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topics</b>
  5 Functions
</td>
</tr>
</table>
</div>

## 📑 Table of Contents

| # | Section |
|---|---------|
| 1 | [np.concatenate()](#fn-1) |
| 2 | [np.vstack()](#fn-2) |
| 3 | [np.hstack()](#fn-3) |
| 4 | [np.column_stack()](#fn-4) |
| 5 | [np.dstack()](#fn-5) |
| 6 | [Mistakes & Quick Reference](#fn-6) |
| 7 | [🎤 Interview Questions](#interview-questions) |
| 8 | [📝 Practice Questions](#practice-questions) |
| 9 | [🏆 Mini Challenge](#mini-challenge) |
| 10 | [📌 Summary](#summary) |
| 11 | [📚 References](#references) |

**Stacking** means combining two or more arrays into a single array — the five functions below differ only in *which axis* they combine along.

| Function | Purpose | AI Importance |
|---|---|---|
| `np.concatenate()` | Join arrays along an existing axis | ⭐⭐⭐⭐⭐ |
| `np.vstack()` | Stack vertically (row-wise, axis=0) | ⭐⭐⭐⭐⭐ |
| `np.hstack()` | Stack horizontally (column-wise, axis=1) | ⭐⭐⭐⭐⭐ |
| `np.column_stack()` | Treat 1D arrays as columns, combine | ⭐⭐⭐⭐ |
| `np.dstack()` | Stack along depth (third axis) | ⭐⭐⭐ |

<div style="border:2px solid #8B5CF6; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#7C3AED; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">🤖</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">AI Insight</span></div>
<div style="background:#F5F3FF; padding:14px 18px; color:#3B0764; font-size:0.97em; line-height:1.6;">
Stacking is how you merge feature matrices, combine batches, or assemble image channels. <code>vstack</code> and <code>hstack</code> cover 90% of real use cases; <code>concatenate</code> is the general-purpose version that can do both.
</div>
</div>

<a id="fn-1"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">1</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">np.concatenate()</code>
</div>

Joins a sequence of arrays along an **existing** axis. The most general stacking function.

**Syntax:** `np.concatenate((arr1, arr2, ...), axis=0)`

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 1D Example</span></div>

In [ ]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = np.concatenate((arr1, arr2))
print(result)

[1 2 3 4 5 6]


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 2D — Row-wise (axis=0)</span></div>

In [ ]:
arr1 = np.array([[1,2],
                 [3,4]])

arr2 = np.array([[5,6],
                 [7,8]])

print(np.concatenate((arr1, arr2), axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 2D — Column-wise (axis=1)</span></div>

In [ ]:
print(np.concatenate((arr1, arr2),axis=1))

[[1 2 5 6]
 [3 4 7 8]]


<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">💡</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Axis Reminder</span></div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
<b>axis=0</b> → add rows (stack vertically, array grows taller)<br><b>axis=1</b> → add columns (stack horizontally, array grows wider)
</div>
</div>

<a id="fn-2"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">2</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">np.vstack()</code>
</div>

Stacks arrays **vertically** (row-wise). Equivalent to `concatenate(..., axis=0)`, but handles 1D arrays more intuitively by treating them as rows.

In [ ]:
arr1 = np.array([[1,2],
                 [3,4]])

arr2 = np.array([[5,6],
                 [7,8]])
print(np.vstack((arr1, arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


```
arr1:  [[1 2]     arr2:  [[5 6]
        [3 4]]            [7 8]]

result: [[1 2]
         [3 4]
         [5 6]
         [7 8]]   ← 4 rows
```

<a id="fn-3"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">3</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">np.hstack()</code>
</div>

Stacks arrays **horizontally** (column-wise). Equivalent to `concatenate(..., axis=1)` for 2D arrays.

In [ ]:
arr1 = np.array([[1,2],
                 [3,4]])

arr2 = np.array([[5,6],
                 [7,8]])
print(np.hstack((arr1, arr2)))

[[1 2 5 6]
 [3 4 7 8]]


```
arr1:  [[1 2]     arr2:  [[5 6]
        [3 4]]            [7 8]]

result: [[1 2 5 6]
         [3 4 7 8]]   ← 4 columns
```

<a id="fn-4"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">4</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">np.column_stack()</code>
</div>

Treats each **1D input array as a column** and combines them side-by-side into a 2D result — a shortcut that avoids reshaping each vector manually.

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.column_stack((arr1, arr2)))

[[1 4]
 [2 5]
 [3 6]]


```
arr1: [1 2 3]   arr2: [4 5 6]

result: [[1 4]
         [2 5]
         [3 6]]   ← each input became a column
```

<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">💡</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">When to Use column_stack</span></div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
Use it when you have several 1D feature arrays and want to build a <code>(n_samples, n_features)</code> matrix in one call — no <code>reshape(-1,1)</code> needed for each one.
</div>
</div>

<a id="fn-5"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">5</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">np.dstack()</code>
</div>

Stacks arrays **along the third dimension** (depth). For 2D arrays, it creates a 3D result where the third axis indexes which original array each "slice" came from.

In [ ]:
arr1 = np.array([[1,2],
                 [3,4]])

arr2 = np.array([[5,6],
                 [7,8]])

print(np.dstack((arr1, arr2)))

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


```
arr1:  [[1 2]     arr2:  [[5 6]
        [3 4]]            [7 8]]

result shape: (2, 2, 2)   ← third axis = depth
result[:,:,0] = arr1      result[:,:,1] = arr2
```

<div style="border:2px solid #8B5CF6; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#7C3AED; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">🤖</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">AI Insight</span></div>
<div style="background:#F5F3FF; padding:14px 18px; color:#3B0764; font-size:0.97em; line-height:1.6;">
<code>dstack</code> is how you combine separate grayscale channel arrays into a single RGB image array of shape <code>(H, W, C)</code>.
</div>
</div>

<a id="fn-6"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">6</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">Mistakes & Quick Reference</code>
</div>

<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Common Mistake — Mismatched Shapes</span></div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
All arrays must agree on every axis <b>except</b> the one being stacked along. For example, <code>vstack</code> requires the same number of columns; <code>hstack</code> requires the same number of rows.
</div>
</div>

<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Common Mistake — Wrong Axis</span></div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
<code>axis=0</code> → rows (array grows taller)<br><code>axis=1</code> → columns (array grows wider)<br>Getting these backwards produces the wrong shape without raising an error if the arrays happen to be square.
</div>
</div>

<a id="interview-questions"></a>

## 🎤 Interview Questions

---

### 🟢 Beginner

**Q1.** What does `np.vstack()` do?
<details><summary>▶ Answer</summary>
It stacks arrays vertically — adds rows — equivalent to <code>np.concatenate((arr1, arr2), axis=0)</code>.
</details>

**Q2.** What's the difference between `hstack` and `column_stack` for 1D arrays?
<details><summary>▶ Answer</summary>
For 1D inputs, <code>hstack</code> concatenates them end-to-end into a longer 1D array. <code>column_stack</code> treats each 1D input as a column and builds a 2D matrix — a fundamentally different result.
</details>

**Q3.** What constraint must hold when using `np.concatenate()` with `axis=0`?
<details><summary>▶ Answer</summary>
All arrays must have the same number of columns (same shape on every axis except axis 0).
</details>

---

### 🟡 Intermediate

**Q4.** Given two `(3,4)` arrays, what shape does `np.vstack()` produce? What about `np.hstack()`?
<details><summary>▶ Answer</summary>
<code>vstack</code> → <code>(6,4)</code> (more rows). <code>hstack</code> → <code>(3,8)</code> (more columns).
</details>

**Q5.** You have three 1D arrays each of length 5. How do you build a `(5,3)` feature matrix without reshaping each individually?
<details><summary>▶ Answer</summary>
<code>np.column_stack((a, b, c))</code> — it treats each 1D array as a column automatically.
</details>

**Q6.** What shape does `np.dstack()` produce when applied to two `(2,2)` arrays?
<details><summary>▶ Answer</summary>
<code>(2,2,2)</code> — the two arrays become slices along the third (depth) axis.
</details>

---

### 🔴 Advanced

**Q7.** When would you prefer `concatenate()` over `vstack()` or `hstack()`?
<details><summary>▶ Answer</summary>
When working with arrays of 3 or more dimensions, where "vertical" and "horizontal" are ambiguous — <code>concatenate</code> lets you specify the exact axis explicitly.
</details>

**Q8.** Stacking three `(H, W)` grayscale images into a single `(H, W, 3)` RGB-like array — which function is most natural?
<details><summary>▶ Answer</summary>
<code>np.dstack((r, g, b))</code> — it stacks along the depth (third) axis, so each original 2D array becomes one channel in the output.
</details>

**Q9.** Why does `np.hstack((arr1d_a, arr1d_b))` produce a 1D array, while `np.column_stack((arr1d_a, arr1d_b))` produces a 2D array?
<details><summary>▶ Answer</summary>
<code>hstack</code> on 1D arrays treats them as single-row vectors and concatenates along axis 0 (their only axis), producing a longer 1D result. <code>column_stack</code> first promotes each 1D array to a <code>(n,1)</code> column vector and then concatenates along axis 1, producing an <code>(n, 2)</code> 2D matrix.
</details>

<a id="practice-questions"></a>

## 📝 Practice Questions

*(Try solving each question before running any code.)*

---

### 🟢 Easy

1. Concatenate two 1D arrays `[1,2,3]` and `[4,5,6]` into a single array.
2. Vertically stack two `(2,3)` arrays and print the resulting shape.
3. Horizontally stack two `(3,2)` arrays and print the resulting shape.
4. Use `column_stack()` to combine `[1,2,3]` and `[10,20,30]` into a `(3,2)` matrix.

### 🟡 Medium

5. Given a `(3,4)` array and a `(2,4)` array, stack them along axis=0. What is the resulting shape?
6. Given a `(3,4)` and a `(3,2)` array, stack them along axis=1. What is the resulting shape?
7. Combine three 1D arrays of length 4 into a `(4,3)` feature matrix using `column_stack`.
8. Use `dstack` on two `(3,3)` arrays and confirm the resulting shape is `(3,3,2)`.

### 🔴 Hard

9. Given five `(28,28)` grayscale images, stack them into a `(5,28,28)` batch using `vstack` after reshaping each (or alternatively, using `np.stack`).
10. Given two `(4,3)` feature matrices, concatenate them along axis=0 and confirm the result has 8 rows. Then concatenate along axis=1 and confirm it has 6 columns.
11. Explain why `np.concatenate(([1,2],[3,4]), axis=1)` raises an error — then fix it.
12. Build a `(H, W, 3)` colour image array from three separate `(H, W)` channel arrays using only `dstack`, and confirm the shape is correct.

<a id="mini-challenge"></a>

## 🏆 Mini Challenge — Feature Matrix Builder

You're assembling a feature matrix from three raw measurement arrays.

**Complete all 4 steps:**

1. **Create** three 1D arrays of length 10 representing three features — e.g. `height = np.random.rand(10)*50 + 150`, `weight = np.random.rand(10)*30 + 50`, `age = np.random.randint(20, 60, 10)`.
2. **Combine** them into a `(10, 3)` feature matrix using `np.column_stack()`.
3. **Add** a fourth feature (e.g. a BMI column computed from height and weight) by `hstack`-ing a `(10,1)` column to the matrix.
4. **Confirm** the final shape is `(10, 4)` and that each column still corresponds to its original feature.

*(Solutions intentionally omitted — this is a self-check exercise.)*

<a id="summary"></a>

## 📌 Summary

- **concatenate()** is the universal option — specify any existing axis explicitly.
- **vstack()** adds rows (axis=0); **hstack()** adds columns (axis=1) — convenience wrappers around `concatenate`.
- **column_stack()** is the cleanest way to combine multiple 1D arrays into a 2D feature matrix.
- **dstack()** stacks along the third axis — ideal for combining image channels.
- The golden rule: shapes must match on **all axes except the stacking axis**.

| Function | Direction | Shape Example |
|---|---|---|
| `concatenate(axis=0)` / `vstack` | ↕ Adds rows | `(2,3)+(2,3)` → `(4,3)` |
| `concatenate(axis=1)` / `hstack` | ↔ Adds columns | `(2,3)+(2,3)` → `(2,6)` |
| `column_stack` | 1D→columns | `(3,)+(3,)` → `(3,2)` |
| `dstack` | ↗ Adds depth | `(2,2)+(2,2)` → `(2,2,2)` |

**What's next:** Copy vs View — understanding which NumPy operations share memory and which allocate new arrays.

<a id="references"></a>

## 📚 References

### Official Documentation

- 📖 [numpy.concatenate](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html)
- 📖 [numpy.vstack](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html)
- 📖 [numpy.hstack](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html)
- 📖 [numpy.column_stack](https://numpy.org/doc/stable/reference/generated/numpy.column_stack.html)
- 📖 [numpy.dstack](https://numpy.org/doc/stable/reference/generated/numpy.dstack.html)

### Recommended Reading

- 📘 *Python for Data Analysis* — Wes McKinney
- 📘 *Python Data Science Handbook* — Jake VanderPlas

### Useful Resources

- 🔗 [NumPy Cheat Sheet (DataCamp)](https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python)

---

<div style="background: linear-gradient(135deg, #1a237e 0%, #01579b 100%); padding: 24px; border-radius: 10px; text-align:center; color:white; font-family:'Segoe UI',sans-serif;">
<b>Thanks for reading!</b> ⭐ Star the repo if this helped — feedback and PRs welcome.
</div>