<h1>🎲 02_Random_Module.ipynb

The Random Module is used to generate random numbers and perform random operations.

```
Function	                 Purpose   	          
np.random.seed()	    Reproducible results	    
np.random.rand()	     Random floats (0–1)	    
np.random.randn()	Random numbers from normal distribution	
np.random.randint()	       Random integers	        
np.random.choice()	       Random sampling	        
np.random.shuffle()	   Shuffle original array      
np.random.permutation()	  Shuffled copy	           

<h3>
1. np.random.seed()

```Produces the same random numbers every time.```<BR>This makes experiments reproducible.

<h4>Example

In [2]:
import numpy as np 
np.random.seed(42) 
print(np.random.rand(5))

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


Inside seed ```you can give any no```, but once you use seed with ```that no``` it give you ```same random now anywhere you run rand function. 

**Without seed:**

In [8]:
print(np.random.rand(7))

[0.18182497 0.18340451 0.30424224 0.52475643 0.43194502 0.29122914
 0.61185289]


Any random no comes

**with seed**

In [9]:
np.random.seed(42) 
print(np.random.rand(7))

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361]


```
Seed having 5 no in it, it gives same and remains randomly

<h3>2. np.random.rand()

Returns random decimal numbers``` between 0 and 1.```

In [11]:
np.random.rand(5)

array([0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224])

**2D Example**

In [12]:
np.random.rand(2,3)

array([[0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465]])

<h3>3. np.random.randn()

Returns random numbers from ```a Normal (Gaussian) Distribution.```
<li>Mean ≈ 0
<li>Standard Deviation ≈ 1

In [13]:
np.random.randn(5)

array([-0.7033438 , -2.13962066, -0.62947496,  0.59772047,  2.55948803])

<h3>4. np.random.randint()

Returns ```random integers.```

```np.random.randint(low, high, size)```

**2D Example**

<h3>5. np.random.choice()

Randomly ```selects values.```

In [15]:
colors = ["Red","Blue","Green"] 
np.random.choice(colors)

np.str_('Blue')

**Multiple Choices**

In [16]:
np.random.choice(colors,3)

array(['Red', 'Blue', 'Blue'], dtype='<U5')

**Without Replacement**

In [17]:
np.random.choice(colors,3,replace=False)

array(['Green', 'Red', 'Blue'], dtype='<U5')

<h3>6. np.random.shuffle()

```Shuffles the original array.```

In [18]:
arr = np.array([1,2,3,4,5]) 
np.random.shuffle(arr) 
print(arr)

[4 3 5 1 2]


In [19]:
arr

array([4, 3, 5, 1, 2])

**Important**

```It modifies the original array.```

<h3>7. np.random.permutation()

Returns a ```shuffled copy.```

In [20]:
arr = np.array([1,2,3,4,5]) 
new_arr = np.random.permutation(arr) 
print(arr) 
print(new_arr)

[1 2 3 4 5]
[1 2 5 3 4]


<h2>Common Mistakes

❌ Forgetting seed()

Results change every run.

❌ Assuming rand() returns integers

It always returns floating-point numbers between 0 and 1.


<h2>Best practices

<li>Use seed() for reproducible experiments.
<li>Use permutation() when you need to preserve the original data.
<li>Use shuffle() only when modifying the original array is acceptable.
<li>Use choice() for random sampling tasks.