<h1>📘 01_Copy_vs_View.ipynb

<h3>Visual Overview

**Copy**
```
arr
 │
 ▼
[10 20 30]

copy_arr
 │
 ▼
[10 20 30]


Two independent arrays.

Changing one does not affect the other

**View**
```
           ┌───────────────┐
arr ───────►               │
           │ [10 20 30]    │
view_arr ─►                │
           └───────────────┘

Both variables point to the same memory.

Changing one changes the other.

1. View

```view_arr = arr.view()```

In [8]:
import numpy as np 
arr = np.array([10,20,30,40]) 
view_arr = arr.view() 
view_arr[0]=111
print(view_arr)
arr is view_arr
print(id(arr))
id(view_arr)
arr

[111  20  30  40]
2101178607792


array([111,  20,  30,  40])

```
Python Object 1 (arr)
        │
        ▼
   ┌──────────────┐
   │ Data Buffer  │
   │10 20 30 40   │
   └──────────────┘
        ▲
        │
Python Object 2 (view_arr)

id() returns the identity of the Python object, not the memory address of the underlying NumPy data.

<h3>How do we prove they share memory?

<h5>Method 1 (Recommended): Use .base

In [9]:
print(view_arr.base is arr)

True


```This confirms view_arr is backed by arr's data.```

<h5>Method 3 (Best): Check the data buffer address

In [10]:
print(arr.ctypes.data)
print(view_arr.ctypes.data)

2101157607696
2101157607696


<h3>Mistakes

Many beginners think ```"View means same object." ```That's incorrect.

A view is a ```different NumPy array object``` that ```shares the same underlying data buffer.```

So:
```
id() compares Python objects.
.ctypes.data compares the memory address of the array data.
.base tells you whether the array shares memory with another array.

<h2>2. Copy

A Copy creates an entirely new array with its own memory.

In [12]:
copy_arr = arr.copy()
copy_arr


array([111,  20,  30,  40])

**Memory Representation**
```
arr
 │
 ▼
[10 20 500 40]


copy_arr
 │
 ▼
[10 200 30 40]

Two completely separate memory locations.

<h3>Checking Memory Using .base

In [13]:
print(copy_arr.base)

None


```None means copy_arr owns its own data and does not share memory.```

<h2>4. Operations That Return a View vs a Copy⭐⭐⭐⭐⭐

<h3>Operations That Return a view

```
Operation	           Returns
arr.view()	          ✅ View
Basic Slicing (:)	  ✅ View
reshape()*	          ✅ Usually a View
transpose() / .T	  ✅ Usually a View
ravel()*	          ✅ Usually a View

**Note:** ```reshape()``` and ```ravel()``` return a view whenever possible. If NumPy cannot share memory due to the array's layout, they return a copy instead.

<h4>Example 1 — Slicing Returns a View

In [18]:
arr = np.array([10,20,30,40,50])
slc=arr[:4]
slc[0]=101
arr

array([101,  20,  30,  40,  50])

Give access to users to edit a some part of a origninal thing 

<h3>Operations That Return a Copy

```
Operation	                                     Returns
copy()	                                          ✅ Copy
Fancy Indexing	                                  ✅ Copy
Boolean Masking	                                  ✅ Copy
Most arithmetic operations (arr + 5, arr * 2)	  ✅ Copy
flatten()	                                      ✅ Copy

<h4>Example 2 — Fancy Indexing Returns a Copy

In [26]:
arr = np.array([10,20,30,40])
fnc=arr[[1,3]]
fnc[1]=100
print(arr)
fnc


[10 20 30 40]


array([ 20, 100])

<h4>Example 3 — Boolean Masking Returns a Copy

In [32]:
fil = arr[arr > 20]
fil[0] = 999
print(arr)

[10 20 30 40]
