<h1>📘 03_Stacking.ipynb

Stacking means ```combining two or more arrays into a single array.```

<h3>Functions Covered

```
Function	               Purpose	                               AI Importance
np.concatenate()	       Join arrays along an existing axis	   ⭐⭐⭐⭐⭐
np.vstack()                Stack vertically (row-wise)	           ⭐⭐⭐⭐⭐
np.hstack()	               Stack horizontally (column-wise)	       ⭐⭐⭐⭐⭐
np.column_stack()	       Combine arrays as columns	           ⭐⭐⭐⭐☆
np.dstack()	               Stack along depth (3rd axis)	           ⭐⭐⭐☆☆

<h3>1. np.concatenate()

Joins arrays along an existing axis.

```
np.concatenate((arr1, arr2), axis=0)

<h5>1D Example

In [27]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = np.concatenate((arr1, arr2))
print(result)

[1 2 3 4 5 6]


**2D Example**

Columns wise (axis=0)

In [28]:
arr1 = np.array([[1,2],
                 [3,4]])

arr2 = np.array([[5,6],
                 [7,8]])

print(np.concatenate((arr1, arr2), axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Row wise(axis =1)

In [29]:
print(np.concatenate((arr1, arr2),axis=1))

[[1 2 5 6]
 [3 4 7 8]]


<h3>2. np.vstack()

Stacks arrays ```vertically (row-wise).```

In [30]:
arr1 = np.array([[1,2],
                 [3,4]])

arr2 = np.array([[5,6],
                 [7,8]])
print(np.vstack((arr1, arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


<h3>3. np.hstack()

In [31]:
arr1 = np.array([[1,2],
                 [3,4]])

arr2 = np.array([[5,6],
                 [7,8]])
print(np.hstack((arr1, arr2)))

[[1 2 5 6]
 [3 4 7 8]]


<h3>4. np.column_stack()

Treats ```each input array as a column.```

In [32]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.column_stack((arr1, arr2)))

[[1 4]
 [2 5]
 [3 6]]


<h3>5. np.dstack()

Stacks arrays ```along the third dimension (depth).```

In [33]:
arr1 = np.array([[1,2],
                 [3,4]])

arr2 = np.array([[5,6],
                 [7,8]])

print(np.dstack((arr1, arr2)))

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


<h2>Common Mistakes

<li>❌ Different Shapes
<li>❌ Wrong Axis<br>
axis=0 → Rows<br>
axis=1 → Columns<br>
