<div style="background: linear-gradient(135deg, #1a237e 0%, #0d47a1 50%, #01579b 100%); padding: 48px 40px; border-radius: 12px; color: white; font-family: 'Segoe UI', sans-serif; text-align: center;">

<h1 style="font-size: 2.6em; font-weight: 800; margin: 0 0 8px 0; letter-spacing: 1px;">🔁 NumPy Iterating Arrays</h1>
<p style="font-size: 1.2em; margin: 0 0 32px 0; opacity: 0.85;">Looping over 1D, 2D & 3D arrays · np.nditer() · np.ndenumerate()</p>

<hr style="border: 1px solid rgba(255,255,255,0.3); margin-bottom: 28px;">

<table style="margin: 0 auto; border-collapse: collapse; color: white; font-size: 0.95em;">
<tr>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Author</b>
  Harsh Thakur
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">GitHub</b>
  <a href="https://github.com/HarshAIWorks" style="color:#90CAF9;">HarshAIWorks</a>
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topic</b>
  Iterating Arrays
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Difficulty Level</b>
  Moderate
</td>
<td style="padding: 8px 28px;">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topics</b>
  5 Concepts
</td>
</tr>
</table>
</div>

## 📑 Table of Contents

| # | Section |
|---|---------|
| 1 | [Iterating a 1D Array](#fn-1) |
| 2 | [Iterating a 2D Array](#fn-2) |
| 3 | [Iterating a 3D Array](#fn-3) |
| 4 | [np.nditer()](#fn-4) |
| 5 | [np.ndenumerate()](#fn-5) |
| 6 | [Common Beginner Mistakes & Best Practices](#fn-6) |
| 7 | [🎤 Interview Questions](#interview-questions) |
| 8 | [📝 Practice Questions](#practice-questions) |
| 9 | [🏆 Mini Challenge](#mini-challenge) |
| 10 | [📌 Summary](#summary) |
| 11 | [📚 References](#references) |

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">🔁</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">Why Iterate?</code>
</div>

**Iteration** means visiting every element of an array, one by one — the same idea as looping over a Python list, just applied to NumPy's grid-shaped data.

NumPy is built for **vectorized** operations (`arr * 2` beats a `for` loop every time), but sometimes you genuinely need to touch each element yourself — custom logic, debugging, or printing values in a specific order. This notebook covers the four ways to do that, from plain loops to NumPy's purpose-built iterators.

<div style="border:2px solid #8B5CF6; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#7C3AED; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">🤖</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">AI Insight</span></div>
<div style="background:#F5F3FF; padding:14px 18px; color:#3B0764; font-size:0.97em; line-height:1.6;">
In real ML code, hand-written iteration is rare — it is a last resort, not a first choice. Reach for <code>np.nditer()</code> or <code>np.ndenumerate()</code> only when a vectorized operation genuinely cannot express what you need.
</div>
</div>

<a id="fn-1"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">1</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">Iterating a 1D Array</code>
</div>

In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50,60])


elements directly inside array:

In [ ]:
for element in arr:  # as we all se the defination of itreating-  print all elements one by one
 print(element)

10
20
30
40
50
60


<a id="fn-2"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">2</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">Iterating a 2D Array</code>
</div>

Rows directly inside array:                 ``` -----------            array([[R1],[R2],[R3]])```<br>
```........```    elements directly inside rows: ```---------[R1]--{a,b,c,d}```

In [ ]:
arr_2d= np.arange(12).reshape(3,4)
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Iterate Rows</span></div>

Looping over a 2D array directly gives you one **row** at a time — not individual elements.

In [ ]:
for rows in arr_2d:
    print(rows)
    

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


Each iteration returns one complete row.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Iterate Every Element</span></div>

To reach individual elements, nest a second loop inside the first: outer loop → row, inner loop → element.

In [ ]:
for row in arr_2d: #  every row will go once 
    for element in row: # every element of the row go once
      print(element)



0
1
2
3
4
5
6
7
8
9
10
11


<a id="fn-3"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">3</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">Iterating a 3D Array</code>
</div>

```
Layers directly inside array:
     rows directly inside layers:
         elements directly inside rows:

In [ ]:
arr_3d= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Think of a 3D array as **layers** of 2D grids: each layer contains rows, and each row contains the actual elements.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Iterate Layers</span></div>

In [ ]:
for layers in arr_3d:
    print(layers)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Iterate Rows</span></div>

In [ ]:
for layers in arr_3d:
    for rows in layers:
            print(rows)

[1 2]
[3 4]
[5 6]
[7 8]


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Iterate Every Element</span></div>

In [ ]:
for layers in arr_3d:
    for rows in layers:
            for elements in rows:
             print(elements)

1
2
3
4
5
6
7
8


<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Scales Badly</span></div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
Notice the pattern: 1D needs 1 loop, 2D needs 2 nested loops, 3D needs 3. A 5D array would need 5 nested loops — this is exactly the problem <code>np.nditer()</code> solves next.
</div>
</div>

<a id="fn-4"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">4</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">np.nditer() ⭐⭐⭐⭐⭐</code>
</div>

A universal iterator that walks through **every element**, regardless of how many dimensions the array has — no nested loops required.

In [ ]:
array=np.arange(27).reshape(3,3,3)
array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for elements in np.nditer(array):
    print(elements)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">💡</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Why Use It</span></div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
One flat loop replaces however many nested loops the array's dimensionality would otherwise demand — the code stays identical whether the array is 2D or 20D.
</div>
</div>

<a id="fn-5"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">5</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">np.ndenumerate() ⭐⭐⭐⭐⭐</code>
</div>

Like `nditer()`, but returns both the **index** and the **value** together — useful whenever position matters as much as content.

In [ ]:
arr = np.array([[10, 20], [30, 40]])
arr

array([[10, 20],
       [30, 40]])

In [ ]:
for index,values in np.ndenumerate(arr):
    print(index,values)

(0, 0) 10
(0, 1) 20
(1, 0) 30
(1, 1) 40


<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">💡</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Why Use It</span></div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
Reach for <code>ndenumerate()</code> whenever you need both the <b>position</b> of an element and its <b>value</b> — for example, locating the coordinates of a specific pixel.
</div>
</div>

<a id="fn-6"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">*</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">Mistakes & Best Practices</code>
</div>

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ ❌ Looping for Simple Arithmetic</span></div>

<div style="margin:10px 0 4px 0; font-family:'Segoe UI',sans-serif;"><span style="color:#64748B; font-weight:600; font-size:0.88em; font-style:italic;">— Bad</span></div>

In [ ]:
for i in range(len(arr)):
    arr[i] = arr[i] * 2

<div style="margin:10px 0 4px 0; font-family:'Segoe UI',sans-serif;"><span style="color:#64748B; font-weight:600; font-size:0.88em; font-style:italic;">— Good</span></div>

In [ ]:
arr = arr * 2

<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">✅</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Best Practice</span></div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
Vectorized operations are almost always faster — and shorter — than an explicit loop.
</div>
</div>

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ ❌ Forgetting 2D Iteration Returns Rows</span></div>

In [ ]:
for item in arr:
    print(item)

[40 80]
[120 160]


`item` here is a **row**, not a single element — a frequent source of confusing bugs.

<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">✅</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Best Practices Checklist</span></div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
Use vectorized operations whenever possible.<br>Use a simple <code>for</code> loop for 1D arrays.<br>Use <code>np.nditer()</code> to iterate over any-dimensional arrays in one flat loop.<br>Use <code>np.ndenumerate()</code> when you need the index alongside the value.
</div>
</div>

<a id="interview-questions"></a>

## 🎤 Interview Questions

---

### 🟢 Beginner

**Q1.** What does iterating over a 2D array with a single `for` loop give you?
<details><summary>▶ Answer</summary>
Each iteration returns one complete <b>row</b> (a 1D sub-array), not an individual element.
</details>

**Q2.** How many nested loops do you need to reach individual elements of a 3D array with plain Python loops?
<details><summary>▶ Answer</summary>
Three — one for layers, one for rows within each layer, and one for elements within each row.
</details>

**Q3.** What is the main advantage of `np.nditer()` over manual nested loops?
<details><summary>▶ Answer</summary>
It iterates over every element of an array regardless of its number of dimensions, so the same one-line loop works for a 1D, 3D, or 10D array without rewriting nested loops.
</details>

---

### 🟡 Intermediate

**Q4.** What does `np.ndenumerate()` return on each iteration that a plain loop or `nditer()` does not?
<details><summary>▶ Answer</summary>
It returns a tuple of `(index, value)` — the index tells you exactly where in the array (as a tuple of coordinates) the value came from.
</details>

**Q5.** Why is `for i in range(len(arr)): arr[i] = arr[i] * 2` considered bad practice in NumPy?
<details><summary>▶ Answer</summary>
It's slow and verbose compared to the vectorized equivalent `arr = arr * 2`, which NumPy executes in optimized C code across the whole array at once.
</details>

**Q6.** If `arr` is a `(3,4)` 2D array, what does `for item in arr` iterate over?
<details><summary>▶ Answer</summary>
It iterates over the 3 rows, each of shape `(4,)` — not the 12 individual elements.
</details>

---

### 🔴 Advanced

**Q7.** For an array of shape `(2,3,4)`, what index tuples would `np.ndenumerate()` produce, and how many total iterations?
<details><summary>▶ Answer</summary>
24 iterations total (2×3×4), with index tuples ranging from `(0,0,0)` through `(1,2,3)` — one for every element.
</details>

**Q8.** Why does NumPy still provide `np.nditer()` when vectorized operations are almost always faster?
<details><summary>▶ Answer</summary>
Some logic genuinely can't be vectorized — conditional branching per element, calling an external function per value, or custom accumulation logic. `nditer()` gives a clean, dimension-agnostic escape hatch for those cases.
</details>

**Q9.** What would happen if you tried `for element in arr_3d` on a `(2,2,2)` array and expected 8 elements?
<details><summary>▶ Answer</summary>
You'd only get 2 iterations, each returning a `(2,2)` 2D sub-array (a "layer") — a classic beginner mistake, since the top-level loop only ever unpacks the outermost axis.
</details>

<a id="practice-questions"></a>

## 📝 Practice Questions

*(Try solving each question before running any code.)*

---

### 🟢 Easy

1. Create a 1D array of 8 elements and print each element with a plain `for` loop.
2. Create a `(3,3)` 2D array and print each row using a single `for` loop.
3. Using the same `(3,3)` array, print every individual element using nested loops.
4. Use `np.nditer()` to print every element of a `(2,4)` array in one flat loop.

### 🟡 Medium

5. Create a `(2,2,2)` 3D array and print its layers, then its rows, then its individual elements (three separate loops).
6. Use `np.ndenumerate()` on a `(2,3)` array and print each index alongside its value.
7. Given a `(4,4)` array, find the index of the element with value `10` using `np.ndenumerate()` (without using `np.where()`).
8. Rewrite `for i in range(len(arr)): arr[i] = arr[i] + 5` as a single vectorized line.

### 🔴 Hard

9. Given a `(3,3,3)` array, use `np.nditer()` to sum all elements without using `np.sum()`.
10. Using `np.ndenumerate()`, find the index of the *maximum* value in a `(4,4)` array without using `np.argmax()`.
11. Explain why `for row in arr_2d: for val in row:` produces individual elements, but `for item in arr_2d:` alone does not — in terms of what each loop "peels off."
12. Write a function that accepts an array of any dimensionality and returns the count of elements greater than a threshold, using `np.nditer()` so it works for 1D, 2D, or 3D input without modification.

<a id="mini-challenge"></a>

## 🏆 Mini Challenge — Grid Scanner

You're scanning a `(5,5)` grid of sensor readings for anomalies.

**Complete all 4 steps:**

1. **Create** a `(5,5)` array with `np.random.randint(0, 100, (5,5))` representing 25 sensor readings.
2. **Loop** over the grid with `np.ndenumerate()` and print the index and value of every reading above 80.
3. **Count** how many readings are above 80 using only `np.nditer()` (no boolean masking).
4. **Compare** your loop-based count from step 3 against the vectorized equivalent `np.sum(arr > 80)` — confirm they match.

*(Solutions intentionally omitted — this is a self-check exercise.)*

<a id="references"></a>

## 📚 References

### Official Documentation

- 📖 [numpy.nditer](https://numpy.org/doc/stable/reference/generated/numpy.nditer.html)
- 📖 [numpy.ndenumerate](https://numpy.org/doc/stable/reference/generated/numpy.ndenumerate.html)
- 📖 [Iterating Over Arrays (NumPy User Guide)](https://numpy.org/doc/stable/reference/arrays.nditer.html)

### Recommended Reading

- 📘 *Python for Data Analysis* — Wes McKinney
- 📘 *Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow* — Aurélien Géron

### Useful Resources

- 🔗 [NumPy Cheat Sheet (DataCamp)](https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python)

---

<div style="background: linear-gradient(135deg, #1a237e 0%, #01579b 100%); padding: 24px; border-radius: 10px; text-align:center; color:white; font-family:'Segoe UI',sans-serif;">
<b>Thanks for reading!</b> ⭐ Star the repo if this helped — feedback and PRs welcome.
</div>