<div style="background: linear-gradient(135deg, #1a237e 0%, #0d47a1 50%, #01579b 100%); padding: 48px 40px; border-radius: 12px; color: white; font-family: 'Segoe UI', sans-serif; text-align: center;">

<h1 style="font-size: 2.6em; font-weight: 800; margin: 0 0 8px 0; letter-spacing: 1px;">🧩 NumPy Reshaping Arrays — Part 1</h1>
<p style="font-size: 1.2em; margin: 0 0 32px 0; opacity: 0.85;">reshape() · flatten() · ravel() · transpose() / .T · expand_dims() · squeeze()</p>

<hr style="border: 1px solid rgba(255,255,255,0.3); margin-bottom: 28px;">

<table style="margin: 0 auto; border-collapse: collapse; color: white; font-size: 0.95em;">
<tr>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Author</b>
  Harsh Thakur
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">GitHub</b>
  <a href="https://github.com/HarshAIWorks" style="color:#90CAF9;">HarshAIWorks</a>
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topic</b>
  Reshaping Arrays
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Difficulty Level</b>
  moderate
</td>
<td style="padding: 8px 28px;">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topics</b>
  6 Functions
</td>
</tr>
</table>
</div>

## 📑 Table of Contents

| # | Section |
|---|---------|
| 1 | [reshape()](#fn-1) |
| 2 | [flatten()](#fn-2) |
| 3 | [ravel()](#fn-3) |
| 4 | [transpose() / .T](#fn-4) |
| 5 | [expand_dims()](#fn-5) |
| 6 | [squeeze()](#fn-6) |
| 7 | [🎤 Interview Questions](#interview-questions) |
| 8 | [📝 Practice Questions](#practice-questions) |
| 9 | [🏆 Mini Challenge](#mini-challenge) |
| 10 | [📌 Summary](#summary) |
| 11 | [📚 References](#references) |

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">1.</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;"> reshape()</code>
</div>

⭐ AI Importance: 10/10

<h3>Why is Reshaping So Important?

Reshaping is a daily task for AI engineers.

<div style="border:2px solid #8B5CF6; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#7C3AED; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">🤖</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">AI Insight</span></div>
<div style="background:#F5F3FF; padding:14px 18px; color:#3B0764; font-size:0.97em; line-height:1.6;">
Reshaping is one of the few NumPy skills you will use in <b>every single</b> AI project — from flattening images for a dense layer to adding a batch dimension before calling <code>model.predict()</code>.
</div>
</div>

It changes the shape (dimensions) of an array without changing its data.

Syntax: ```array.reshape(new_shape)``` or ```np.reshape(array, new_shape)```

<div style="margin:10px 0 4px 0; font-family:'Segoe UI',sans-serif;"><span style="color:#64748B; font-weight:600; font-size:0.88em; font-style:italic;"><h3> ⭐ Golden Rule: The total number of elements must remain the same.</span></div>

6 elements<br>
<br>
↓<br>
<br>
Can become<br>
<br>
2 × 3 = 6 ✅<br>
<br>
3 × 2 = 6 ✅<br>
<br>
1 × 6 = 6 ✅<br>
<br>
6 × 1 = 6 ✅<br><br>But, Cannot reshape: 2 × 4 = 8 ❌

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 1 — 1D → 2D</span></div>

In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr,"\n")
reshape=arr.reshape(2,3)
print(reshape)

[10 20 30 40 50 60] 

[[10 20 30]
 [40 50 60]]


Orignal shape: ```(6,)```  <br>reshaped into: ```(2,3)```

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 2 — 1D → 3×2</span></div>

In [ ]:
reshape= arr.reshape(3,2)
reshape


array([[10, 20],
       [30, 40],
       [50, 60]])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 3 — Row Vector⭐⭐⭐⭐⭐</span></div>

``Row =1``

as we now total elements are 6 and no of rows will 1, then shape will be (1,6)

In [ ]:
vector= arr.reshape(1,6)
vector

array([[10, 20, 30, 40, 50, 60]])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 4 — Column Vector ⭐⭐⭐⭐⭐</span></div>

```column=1```

In [ ]:
col_vector= arr.reshape(6,1)
col_vector

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60]])

This is extremely common in Machine Learning.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 5 — 2D → 1D</span></div>

1D form - ```(x,) or (x)``` , x=total no of elements.

In [ ]:
arr = np.array([
    [10,20,30],
    [40,50,60]
])
arr_1d= arr.reshape(6,)
arr_1ds= arr.reshape(6)

print(arr_1d)
print(arr_1ds)


[10 20 30 40 50 60]
[10 20 30 40 50 60]


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 6 — 2D → 3D</span></div>

In [ ]:
array_3d=arr.reshape(2,3,1) #2X3X1=6elements preserve
print(array_3d)

[[[10]
  [20]
  [30]]

 [[40]
  [50]
  [60]]]


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 2. Using -1 with reshape() ⭐⭐⭐⭐⭐</span></div>

<div style="margin:10px 0 4px 0; font-family:'Segoe UI',sans-serif;"><span style="color:#64748B; font-weight:600; font-size:0.88em; font-style:italic;">— What does -1 mean?</span></div>

It tells NumPy: ```"You calculate this dimension automatically."```

NumPy knows: Total elements = 6<br><br>
Rows = 2<br>
Columns = ?<br>
6 ÷ 2 = 3<br>
So it becomes: ```(2,3)```

<div style="margin:10px 0 4px 0; font-family:'Segoe UI',sans-serif;"><span style="color:#64748B; font-weight:600; font-size:0.88em; font-style:italic;">— Giving rows only and leave column on Numpy</span></div>

In [ ]:
print("array: ",arr,"\n")
reshaped= arr.reshape(3,-1)
print("reshaped: ",reshaped)

array:  [[10 20 30]
 [40 50 60]] 

reshaped:  [[10 20]
 [30 40]
 [50 60]]


<div style="margin:10px 0 4px 0; font-family:'Segoe UI',sans-serif;"><span style="color:#64748B; font-weight:600; font-size:0.88em; font-style:italic;">— Giving colmuns only and leave rows on Numpy</span></div>

In [ ]:
reshaped= arr.reshape(-1,6)
print(reshaped)

[[10 20 30 40 50 60]]


<div style="margin:10px 0 4px 0; font-family:'Segoe UI',sans-serif;"><span style="color:#64748B; font-weight:600; font-size:0.88em; font-style:italic;">— Invalid Shape</span></div>

In [ ]:
arr.reshape(4,2)

ValueError: cannot reshape array of size 6 into shape (4,2)

<a id="flatten"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">2</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">flatten()</code>
</div>

```
Original
     │
     ├────────► Copy
     │
     ▼

No shared memory

Converts a multidimensional array into a one-dimensional (1D) array.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Why is it Important?</span></div>

Many machine learning algorithms require input in a single row (1D) instead of a matrix.

Syntax: ```array.flatten(order='C')```

```
Order	Meaning<br><br>
'C' 	Row-wise (C-style) ⭐ Most Common <br>
'F' 	Column-wise (Fortran-style)<br>
'A' 	Column-wise if Fortran contiguous, otherwise row-wise<br>
'K'	    Preserve memory order<br><br>For beginners and AI projects,you'll almost always use the default 'C' order.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 1 — Basic Flatten</span></div>

In [ ]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60]
])
arr.flatten()

array([10, 20, 30, 40, 50, 60])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 2 — 3D Array</span></div>

by default- row wise flatten

In [ ]:
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

All dimensions become one continuous array.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 3 — Column-wise Flatten</span></div>

In [ ]:
arr.flatten(order='F')

array([1, 5, 3, 7, 2, 6, 4, 8])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 4 — Flatten Returns a Copy ⭐⭐⭐⭐⭐</span></div>

In [ ]:
arr = np.array([
    [10,20],
    [30,40]
])

flat = arr.flatten()

flat[0] = 100

In [ ]:
print(arr)
print(flat)

[[10 20]
 [30 40]]
[100  20  30  40]


Changing the flattened array does not affect the original array.

Because flatten() returns a copy.

```
flatten() → Returns a copy
reshape(-1) → Usually returns a view (if possible)

<a id="ravel"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">3</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">ravel()</code>
</div>

```
Original
     │
     ▼
View

Both point to the same data (when possible).

Changing one affects the othe

converts a multidimensional array into a 1D array, just like flatten()<br><br>
The key difference is: <br>
ravel( ) returns a ```view whenever possible, not a copy.```<br>

This makes it faster and more memory efficient.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Why is it Important?</span></div>

AI datasets can contain millions of values.<br>
<br>
Creating unnecessary copies wastes:<br>
<br>
Memory<br>
Processing time<br>
<br>
ravel() avoids copying data whenever possible.<br>

Syntax: ```np.ravel(array, order='C')```

orders are same as flatten

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 1 — Basic Example</span></div>

In [ ]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60]
])
arr.ravel()

array([10, 20, 30, 40, 50, 60])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ ravel() Returns a View ⭐⭐⭐⭐⭐</span></div>

In [ ]:
arr = np.array([
    [10,20],
    [30,40]
])

flat = arr.ravel()

flat[0] = 100

In [ ]:
print(flat)
print(arr)

[100  20  30  40]
[[100  20]
 [ 30  40]]


You can see the flat array also have change and the orignal array also at 0index

Changing the flattened array also changes the original array because both share the same memory (when a view is possible).

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 3 — Column-wise</span></div>

In [ ]:
arr.ravel(order='F')

array([100,  30,  20,  40])

array([[100,  20],
       [ 30,  40]])

<a id="transpose-/-t"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">4</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">transpose() / .T</code>
</div>

We ahve already covered transpose ---

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 1 — 1D Array ⭐⭐⭐⭐⭐</span></div>

```you will get same output after Transpose also```

In [ ]:
array= np.arange(5)
print(array.shape)
array


(5,)


array([0, 1, 2, 3, 4])

there is no ro no colums available, only one axis.

In [ ]:
array.T

array([0, 1, 2, 3, 4])

In [ ]:
np.transpose(array)

array([0, 1, 2, 3, 4])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 2 — 3D Array ⭐⭐⭐⭐☆</span></div>

In [ ]:
array=np.arange(24).reshape(3,2,4)
print(array)
array.shape

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


(3, 2, 4)

In [ ]:
print(np.transpose(array))
array.T.shape

[[[ 0  8 16]
  [ 4 12 20]]

 [[ 1  9 17]
  [ 5 13 21]]

 [[ 2 10 18]
  [ 6 14 22]]

 [[ 3 11 19]
  [ 7 15 23]]]


(4, 2, 3)

```
Before transpose:

[[[ 0  1  2  3]
  [ 4  5  6  7]]   l1

 [[ 8  9 10 11]    
  [12 13 14 15]]   l2

 [[16 17 18 19]
  [20 21 22 23]]]   l3


After Transpose:

    l1 L2  l3

[[[ 0   8  16]
  [ 4  12  20]]

 [[ 1   9  17]
  [ 5  13  21]]

 [[ 2  10  18]
  [ 6  14  22]]

 [[ 3  11  19]
  [ 7  15  23]]]


Shape changing from (3, 2, 4)to (4,2,3)

You are changing the order of the axes.

<a id="expand_dims"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">5</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">expand_dims()</code>
</div>

<div style="margin:10px 0 4px 0; font-family:'Segoe UI',sans-serif;"><span style="color:#64748B; font-weight:600; font-size:0.88em; font-style:italic;">— expand_dims()?</span></div>

```
adds a new axis (dimension) to an existing array.

It does NOT add new data.

It only adds a new dimension of size 1.

<h2>Most Important Rule: (ROW, CoLUMN)</h2><br><br>
axis 0--> column<br>
axis 1--> row<br>
axis 2--> layer<br>
<br>
1D- only 1 axis required at row side(row,) - so axis=0 only applicable to convt into 1d from 0d```<br>
2D- (row,col) required- both axis, axis=0, axis = 1 will applicable.<br>
3D- (layer,row,columns) - 3 axis, x=0,x=1,x=2 applicable<br>
<h3> Example of 1d to 2d</h3>

orignal array: ```(5,)``` --no row column only one axis

If axis =0, add one row ------> ```(1,5)``` 
step1: dimension---> 2d, so every element of array seems under 2 []

```[[r1],[r2],[r3],[r4],[r5]]```

if axis =1, add one column----- ```(5,1)```
```
[[r1],
 [r2],
 [r3],
 [r4],
 [r5]]

 *** short summary, np.exapand_dims() increase dimension by one.
     if row=0 - dimension change by adding 1 at row place.
     if row=1, dimension change by 1 dimension by add 1 at place of column.***

Note: in 0d, you can give axis =1---> (,1) is not allowed.



<div style="margin:10px 0 4px 0; font-family:'Segoe UI',sans-serif;"><span style="color:#64748B; font-weight:600; font-size:0.88em; font-style:italic;">— Why is it Important?</span></div>

Many AI models expect data in a specific number of dimensions.<br>
<br>
For example:<br>
<br>
A grayscale image (28,28) may need to become (28,28,1).<br>
A single image (224,224,3) may need to become (1,224,224,3) before prediction.<br>
A feature vector (5,) may need to become (1,5) or (5,1).<br>

Syntax: ```np.expand_dims(array, axis)```

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Understanding axis</span></div>

```
1D: (x,)- 1 axis only, x-axis
2D: (x,y) - 2 axis, x-axis and y-axis
3D: (x,y,z) - 3 axis, x-axis, y-axis, z-axis


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 0-D to 1-D</span></div>

In [ ]:
arr_0d= np.array(2)
print("array of 0d: ", arr_0d)
print("shape: ",arr_0d.shape)

array of 0d:  2
shape:  ()


axis=0

In [ ]:
array_converted_2d= np.expand_dims(arr_0d, axis=0)
print(array_converted_2d)
print(array_converted_2d.shape) # dimension expaned to 0d to 1d by putting 1 at row side but it not row in actual

[2]
(1,)


axis= 1

In [ ]:
array_converted_2d= np.expand_dims(arr_0d, axis=1)
print(array_converted_2d)
print(array_converted_2d.shape)

AxisError: axis 1 is out of bounds for array of dimension 1

error because, (,1) is not possible

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 1D to 2d</span></div>

In [ ]:
arr = np.array([10,20,30])
arr.shape

(3,)

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ axis = 0</span></div>

In [ ]:
print(np.expand_dims(arr, axis=0))
np.expand_dims(arr, axis=0).shape

[[10 20 30]]


(1, 3)

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ axis = 1</span></div>

In [ ]:
print(np.expand_dims(arr, axis=1))
np.expand_dims(arr, axis=1).shape


[[10]
 [20]
 [30]]


(3, 1)

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 2D to 3D</span></div>

In [ ]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
arr.shape

(2, 3)

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Axis=0</span></div>

In [ ]:
new_arr=np.expand_dims(arr,axis=0)
print(new_arr)
new_arr.shape

[[[1 2 3]
  [4 5 6]]]


(1, 2, 3)

<div style="margin:10px 0 4px 0; font-family:'Segoe UI',sans-serif;"><span style="color:#64748B; font-weight:600; font-size:0.88em; font-style:italic;">— Visualisation</span></div>

```
arr:     2 Rows
         3 Columns

new_arr: 1layer
          2rows 
          2cloumns        

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Axis= 1</span></div>

orignal shape= (2,3) add 1 at column place make it like-- (2,1,3)

In [ ]:
new_arr=np.expand_dims(arr,axis=1)
print(new_arr)
new_arr.shape

[[[1 2 3]]

 [[4 5 6]]]


(2, 1, 3)

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Axis=2</span></div>

Here new term introduce in 3d Axis =2 as we know there are 3 parameters layer, row, col, so one more axis.


In [ ]:
new_arr=np.expand_dims(arr,axis=2)
print(new_arr)
new_arr.shape

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


(2, 3, 1)

Add Last Axis

In [ ]:
new_arr = np.expand_dims(arr, axis=2)
print(new_arr)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


Each element now has an extra dimension.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Negative Axis ⭐⭐⭐⭐⭐ add 1 at -index place</span></div>

In [ ]:
arr
print(arr.shape)

(2, 3)


<div style="margin:10px 0 4px 0; font-family:'Segoe UI',sans-serif;"><span style="color:#64748B; font-weight:600; font-size:0.88em; font-style:italic;">— axis=-1</span></div>

add 1 at -1 index(last osition)

In [ ]:

print(np.expand_dims(arr,axis=-1).shape)
np.expand_dims(arr,axis=-1)

(2, 3, 1)


array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

<div style="margin:10px 0 4px 0; font-family:'Segoe UI',sans-serif;"><span style="color:#64748B; font-weight:600; font-size:0.88em; font-style:italic;">— axis =-2</span></div>

In [ ]:
print(np.expand_dims(arr,axis=-2).shape)

(2, 1, 3)


<div style="margin:10px 0 4px 0; font-family:'Segoe UI',sans-serif;"><span style="color:#64748B; font-weight:600; font-size:0.88em; font-style:italic;">— axis=-3</span></div>

In [ ]:
print(np.expand_dims(arr,axis=-3).shape)

(1, 2, 3)


<div style="margin:10px 0 4px 0; font-family:'Segoe UI',sans-serif;"><span style="color:#64748B; font-weight:600; font-size:0.88em; font-style:italic;">— axis=-4   (no index value -4)</span></div>

In [ ]:
print(np.expand_dims(arr,axis=-4).shape)

AxisError: axis -4 is out of bounds for array of dimension 3

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Common Mistakes</span></div>

<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Common Mistake</span></div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
❌ 1. Confusing reshape() with expand_dims()<br><br>
<br><br>
reshape()<br><br>
<br><br>
Changes the entire shape.<br><br>
<br><br>
expand_dims()<br><br>
<br><br>
Only inserts one new axis.
</div>
</div>

<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Common Mistake</span></div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
❌ 2. Using the wrong axis<br>
<br>
Always check<br>
<br>
arr.shape<br>
<br>
before using expand_dims().
</div>
</div>

<a id="squeeze"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">6</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">squeeze()</code>
</div>

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ What is squeeze()?</span></div>

Removes axes (dimensions) whose size is 1.<br>

```Think of it as the opposite of expand_dims().```
<br><br>
expand_dims() ➜ Adds a dimension of size 1<br>
squeeze() ➜ Removes a dimension of size 1<br>
<br>
It does not remove data—it only removes unnecessary dimensions.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Why is it Important?</span></div>

Many AI models return outputs with extra dimensions.<br>
<br>
For example: <br>
<br>
Prediction Shape: (1, 1000)<br>
<br>
But you only want: (1000,)

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 1- Axis is not provided</span></div>

In [ ]:
import numpy as np
arr = np.array([[10,20,30]])
arr.shape

(1, 3)

In [ ]:
print(np.squeeze(arr).shape)
np.squeeze(arr)

(3,)


array([10, 20, 30])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 2 — Column Vector / having only rows</span></div>

In [ ]:
arr=np.arange(10,40,10).reshape(3,1)
print(arr)
arr.shape

[[10]
 [20]
 [30]]


(3, 1)

In [ ]:
print(np.squeeze(arr).shape)
np.squeeze(arr)


(3,)


array([10, 20, 30])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 3 — 3D Array</span></div>

In [ ]:
arr = np.array([[[1,2,3]]])
arr.shape

(1, 1, 3)

In [ ]:
print(np.squeeze(arr))
np.squeeze(arr).shape

[1 2 3]


(3,)

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 4 — Remove Only One Axis</span></div>

In [ ]:
arr = np.array([[[10,20,30]]])
arr.shape

(1, 1, 3)

In [ ]:
np.squeeze(arr, axis=0)
print(np.squeeze(arr, axis=0).shape)

(1, 3)


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 5 — Invalid Axis</span></div>

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])
arr.shape

(2, 3)

In [ ]:
np.squeeze(arr, axis=0)

ValueError: cannot select an axis to squeeze out which has size not equal to one

```
ValueError:
cannot select an axis to squeeze out which has size not equal to one```

<a id="interview-questions"></a>

## 🎤 Interview Questions

---

### 🟢 Beginner

**Q1.** What is the golden rule of `reshape()`?
<details><summary>▶ Answer</summary>
The total number of elements must stay the same before and after reshaping. You can go from `(6,)` to `(2,3)` because 2×3=6, but not to `(2,4)` because 2×4=8≠6.
</details>

**Q2.** What does passing `-1` as a dimension in `reshape()` do?
<details><summary>▶ Answer</summary>
It tells NumPy to calculate that dimension automatically based on the array's total size and the other dimensions you specified.
</details>

**Q3.** What is the main difference between `flatten()` and `ravel()`?
<details><summary>▶ Answer</summary>
<code>flatten()</code> always returns a <b>copy</b> of the data. <code>ravel()</code> returns a <b>view</b> whenever possible, so it is faster and more memory-efficient, but modifying the result can modify the original array.
</details>

---

### 🟡 Intermediate

**Q4.** For a 1D array, why does `.T` (transpose) appear to do nothing?
<details><summary>▶ Answer</summary>
Transpose reverses the order of axes. A 1D array has only one axis, so there is nothing to reverse — the shape stays `(n,)`.
</details>

**Q5.** What is the difference between `expand_dims()` and `reshape()`?
<details><summary>▶ Answer</summary>
<code>expand_dims()</code> only inserts a single new axis of size 1 at a specified position, leaving all other axes untouched. <code>reshape()</code> can rearrange the entire shape, not just add one axis.
</details>

**Q6.** Given an array of shape `(1, 1000)` — a typical model prediction — how would you get it down to `(1000,)`?
<details><summary>▶ Answer</summary>
Use <code>np.squeeze(arr)</code>, which removes all axes of size 1.
</details>

---

### 🔴 Advanced

**Q7.** Why does `np.squeeze(arr, axis=0)` raise a `ValueError` on an array of shape `(2, 3)`?
<details><summary>▶ Answer</summary>
<code>squeeze()</code> can only remove axes whose size is exactly 1. Axis 0 has size 2 here, so NumPy refuses — it would silently discard real data otherwise.
</details>

**Q8.** For a 3D array of shape `(3, 2, 4)`, what shape does `array.T` produce, and why?
<details><summary>▶ Answer</summary>
`(4, 2, 3)` — plain transpose fully reverses the axis order (axis 0 ↔ axis 2, axis 1 stays in the middle), it does not just swap two chosen axes.
</details>

**Q9.** Can `expand_dims()` be called with `axis=1` on a 0-D array (a scalar wrapped in an array)? Why or why not?
<details><summary>▶ Answer</summary>
No — a 0-D array has no existing axis, so the only valid position to insert a new axis is `axis=0` (producing shape `(1,)`). `axis=1` is out of bounds and raises an `AxisError`.
</details>

<a id="practice-questions"></a>

## 📝 Practice Questions

*(Try solving each question before running any code.)*

---

### 🟢 Easy

1. Create a 1D array of 12 elements and reshape it into a `(3,4)` matrix.
2. Reshape the same array into `(4,-1)`, letting NumPy compute the missing dimension.
3. Flatten a 3×3 2D array and confirm modifying the flattened copy does not change the original.
4. Use `.T` on a `(2,3)` array and print the resulting shape.

### 🟡 Medium

5. Given a `(4,4)` array, use `ravel()` to get a 1D view, modify an element in the view, and confirm the original array changed too.
6. Create a `(28,28)` "image" array and reshape it into `(784,)` — a common preprocessing step before feeding it to a dense layer.
7. Given a `(5,)` feature vector, use `expand_dims()` twice (with different axes) to produce both `(1,5)` and `(5,1)` shapes.
8. Given a `(1, 1, 3)` array, use `squeeze()` to remove only one specific axis (not both) and confirm the resulting shape.

### 🔴 Hard

9. Given a `(2, 3, 4)` array, explain (without running code) what shape `array.T` will produce, then verify.
10. Write code that reshapes a `(6,)` array into a column vector `(6,1)` and confirm it is equivalent to `expand_dims(arr, axis=1)`.
11. Given a `(2,3)` array, predict whether `arr.flatten()[0] = 999` affects `arr`, and whether `arr.ravel()[0] = 999` affects `arr`. Verify both.
12. A model returns predictions of shape `(1, 10)`. Write the single line of code that converts this to a plain `(10,)` array, and explain what would happen if you called `squeeze()` on a `(2,10)` batch instead.

<a id="mini-challenge"></a>

## 🏆 Mini Challenge — Image Pipeline Prep

You're preparing a batch of grayscale images for a neural network.

**Complete all 5 steps:**

1. **Create** a `(4, 28, 28)` array with `np.arange(4*28*28).reshape(4,28,28)` representing 4 grayscale 28×28 images.
2. **Flatten** each image into a single row per image, producing shape `(4, 784)` (hint: `reshape`, not `flatten`, since you want to keep 4 rows).
3. **Add** a channel dimension back with `expand_dims()` so the shape becomes `(4, 784, 1)`.
4. **Transpose** a single `(28,28)` image and confirm the shape stays `(28,28)` (square images transposed look shape-identical, but data is mirrored).
5. **Squeeze** the channel dimension you added in step 3 back out, and confirm you're back to `(4, 784)`.

*(Solutions intentionally omitted — this is a self-check exercise.)*

<a id="summary"></a>

## 📌 Summary

### Key Takeaways

- **reshape()** changes shape without changing data — total element count must stay identical; `-1` lets NumPy compute one dimension automatically.
- **flatten()** always returns a **copy**; **ravel()** returns a **view** whenever possible — prefer `ravel()` for large arrays when you don't need an independent copy.
- **transpose() / .T** reverses (or reorders) axes — for 1D arrays it has no visible effect.
- **expand_dims()** inserts one new size-1 axis at a chosen position — essential for matching a model's expected input rank.
- **squeeze()** removes size-1 axes — the inverse of `expand_dims()` — and raises an error if you try to squeeze an axis that isn't size 1.

### Function Quick Reference

| Function | Purpose | Copy or View? |
|---|---|---|
| `arr.reshape(shape)` | Change shape, same data | View (usually) |
| `arr.flatten()` | Collapse to 1D | Copy (always) |
| `arr.ravel()` | Collapse to 1D | View (usually) |
| `arr.T` / `np.transpose(arr)` | Reverse/reorder axes | View |
| `np.expand_dims(arr, axis)` | Add a size-1 axis | View |
| `np.squeeze(arr, axis=None)` | Remove size-1 axis(es) | View |

### What's Next

Continue to **Part 2** of this notebook — `swapaxes()`, `moveaxis()`, and `resize()` — which cover more advanced axis manipulation and in-place resizing.

<a id="references"></a>

## 📚 References

### Official Documentation

- 📖 [numpy.reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)
- 📖 [numpy.ndarray.flatten](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html)
- 📖 [numpy.ravel](https://numpy.org/doc/stable/reference/generated/numpy.ravel.html)
- 📖 [numpy.transpose](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html)
- 📖 [numpy.expand_dims](https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html)
- 📖 [numpy.squeeze](https://numpy.org/doc/stable/reference/generated/numpy.squeeze.html)

### Recommended Reading

- 📘 *Python for Data Analysis* — Wes McKinney
- 📘 *Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow* — Aurélien Géron

### Useful Resources

- 🔗 [NumPy Cheat Sheet (DataCamp)](https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python)

---

<div style="background: linear-gradient(135deg, #1a237e 0%, #01579b 100%); padding: 24px; border-radius: 10px; text-align:center; color:white; font-family:'Segoe UI',sans-serif;">
<b>Thanks for reading!</b> ⭐ Star the repo if this helped — feedback and PRs welcome.
</div>