<div style="background: linear-gradient(135deg, #1a237e 0%, #0d47a1 50%, #01579b 100%); padding: 48px 40px; border-radius: 12px; color: white; font-family: 'Segoe UI', sans-serif; text-align: center;">

<h1 style="font-size: 2.6em; font-weight: 800; margin: 0 0 8px 0; letter-spacing: 1px;">🧩 NumPy Reshaping Arrays — Part 2</h1>
<p style="font-size: 1.2em; margin: 0 0 32px 0; opacity: 0.85;">swapaxes() · moveaxis() · resize()</p>

<hr style="border: 1px solid rgba(255,255,255,0.3); margin-bottom: 28px;">

<table style="margin: 0 auto; border-collapse: collapse; color: white; font-size: 0.95em;">
<tr>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Author</b>
  Harsh Thakur
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">GitHub</b>
  <a href="https://github.com/HarshAIWorks" style="color:#90CAF9;">HarshAIWorks</a>
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topic</b>
  Reshaping Arrays (Part-2)
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Difficulty Level</b>
  moderate
</td>
<td style="padding: 8px 28px;">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topics</b>
  3 Functions
</td>
</tr>
</table>
</div>

## 📑 Table of Contents

| # | Section |
|---|---------|
| 1 | [swapaxes()](#fn-7) |
| 2 | [moveaxis()](#fn-8) |
| 3 | [resize()](#fn-9) |
| 4 | [🎤 Interview Questions](#interview-questions) |
| 5 | [📝 Practice Questions](#practice-questions) |
| 6 | [🏆 Mini Challenge](#mini-challenge) |
| 7 | [📌 Summary](#summary) |
| 8 | [📚 References](#references) |

<div style="border:2px solid #16A34A; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#15803D; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">ℹ️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Info — Continuing From Part 1</span></div>
<div style="background:#F0FDF4; padding:14px 18px; color:#14532D; font-size:0.97em; line-height:1.6;">
This is Part 2 of the Reshaping Arrays notebook. Part 1 covered <code>reshape()</code>, <code>flatten()</code>, <code>ravel()</code>, <code>transpose()/.T</code>, <code>expand_dims()</code>, and <code>squeeze()</code>.
</div>
</div>

<a id="swapaxes"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">7</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">swapaxes()</code>
</div>

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ What is swapaxes()?</span></div>

swaps two specific axes of an array while keeping all other axes unchanged.<br>
<br>
Think of it as: ```"Exchange Axis A with Axis B."```<br>
Syntax: ```np.swapaxes(array, axis1, axis2)```

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Why is it Important?</span></div>

Deep learning models often require tensors in different formats.

For example:

```Height × Width × Channels```

may need to become:

```Channels × Width × Height```

Instead of manually reshaping everything, we swap the required axes.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 1 — Swap Axis 0 and Axis 1 ⭐⭐⭐⭐⭐</span></div>

(x,y,z)<br>
three axis: x-xis, y-axis, z-axis

In [ ]:
import numpy as np
arr = np.arange(24).reshape(2,3,4)
print(arr)
arr.shape


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


(2, 3, 4)

In [ ]:
new_arr = np.swapaxes(arr,0,1)
print(new_arr,"\n")
print(new_arr.shape)


[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]] 

(3, 2, 4)


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 2 — Swap Axis 1 and Axis 2</span></div>

In [ ]:
new_arr = np.swapaxes(arr,1,2)
new_arr.shape

(2, 4, 3)

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Common Mistakes</span></div>

<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Common Mistake</span></div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
❌ Thinking it changes data<br>
<br>
- No.<br>
<br>
Only the positions of the axes change.
</div>
</div>

<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Common Mistake</span></div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
❌ Using reshape() instead<br>
<br>
reshape() changes the layout of elements.<br>
<br>
swapaxes() changes which dimension is considered rows, columns, layers, etc.
</div>
</div>

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Best Practices</span></div>

<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">✅</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Best Practice</span></div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
✅ Check the shape before and after.<br>
<br>
print(arr.shape)<br>
print(new_arr.shape)
</div>
</div>

<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">✅</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Best Practice</span></div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
✅ Draw the axes on paper for 3D arrays.
</div>
</div>

<a  id="moveaxis"></a>

<div  style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">8</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;"> moveaxis()</code>
</div>

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ What is moveaxis()?</span></div>

```moves one or more axes to new positions without changing the relative order of the remaining axes.```<br>
<br>
Unlike swapaxes(), it doesn't simply exchange two axes.<br>
<br>
It moves an axis to a new position.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 1 — Move Axis 0 to Axis 2</span></div>

In [ ]:
arr =np.arange(24).reshape(2,3,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
new_arr= np.moveaxis(arr,0,2)
print(new_arr)
print(arr.shape, "changes to :",new_arr.shape)

[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]
(2, 3, 4) changes to : (3, 4, 2)


```This is move axis not swap so, only 2 chnages position to axis 2 and all move one axis back```

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 2 — Move Last Axis to Front</span></div>

In [ ]:
print(arr)
arr.shape

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


(2, 3, 4)

In [ ]:
new_arr= np.moveaxis(arr,-1,0)
print(new_arr)
new_arr.shape

[[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]


(4, 2, 3)

<a id="resize"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">9</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">resize()</code>
</div>

resize() changes the shape and size of an array.Unlike reshape(), it can:<br><br>

```
Increase the number of elements.
Decrease the number of elements.

If the new array is larger, NumPy repeats existing elements to fill the extra space.

syntax: array.resize(new_shape), This modifies the original array.

Function: np.resize(array, new_shape)<br><br>This returns a new resized array.<br>These behave differently, so we'll learn both.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 1) array.resize(new_shape) (In-place)</span></div>

Example 1

In [ ]:
import numpy as np
arr = np.array([10,20,30,40])
arr.resize(2,2)
print(arr)


[[10 20]
 [30 40]]


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 2) Method- arr.resize((shape))</span></div>

Example 2 — Increasing Size

In [ ]:
arr = np.array([1,2,3])
arr.resize((6,))
print(arr)

[1 2 3 0 0 0]


Unlike np.resize(), the array method fills new elements with 0.

Example 3 — Decreasing Size

In [ ]:
arr = np.array([1,2,3,4,5,6])
arr.resize((3,))
arr

array([1, 2, 3])

Extra elements are discarded.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 3) np.resize() Function</span></div>

Unlike the method, this returns a new array.

Example

In [ ]:
arr = np.array([1,2,3])
new_arr = np.resize(arr,(6,))
print(arr)
print(new_arr)

[1 2 3]
[1 2 3 1 2 3]


Notice that NumPy repeats the data.
```
1 2 3

↓

1 2 3 1 2 3

Example 2

In [ ]:
arr = np.array([[1,2],
                [3,4]])

np.resize(arr,(3,3))

array([[1, 2, 3],
       [4, 1, 2],
       [3, 4, 1]])

Notice how the original values are repeated.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Visual Understanding</span></div>

Original: 1 2 3 4

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 1. reshape(2,2)</span></div>

```
1 2
3 4

No values are added or removed.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 2. array.resize( (6, ) )</span></div>

```
1 2 3 4 0 0

The array grows by adding zeros.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 3. np.resize( ... , (6, ) )</span></div>

```
1 2 3 4 1 2

The array grows by repeating values.

<a id="interview-questions"></a>

## 🎤 Interview Questions

---

### 🟢 Beginner

**Q1.** What does `np.swapaxes(arr, 0, 1)` do?
<details><summary>▶ Answer</summary>
It exchanges axis 0 and axis 1 of the array, leaving any other axes in place. It does <b>not</b> change the underlying data — only which axis is considered "first" and "second."
</details>

**Q2.** Does `resize()` change the number of elements in an array?
<details><summary>▶ Answer</summary>
Yes — unlike <code>reshape()</code>, <code>resize()</code> can both increase (by filling/repeating) and decrease (by discarding) the total element count.
</details>

**Q3.** What's the difference between `arr.resize()` (method) and `np.resize()` (function)?
<details><summary>▶ Answer</summary>
The array method <code>arr.resize()</code> modifies the array in place and pads new elements with <b>zeros</b>. The function <code>np.resize(arr, shape)</code> returns a <b>new</b> array and pads by <b>repeating</b> the original data.
</details>

---

### 🟡 Intermediate

**Q4.** How is `moveaxis()` different from `swapaxes()`?
<details><summary>▶ Answer</summary>
<code>swapaxes()</code> exchanges exactly two axes with each other. <code>moveaxis()</code> relocates one (or more) axes to new positions while keeping the relative order of all other axes unchanged — it's not a simple swap.
</details>

**Q5.** Given a `(2, 3, 4)` array, what shape results from `np.swapaxes(arr, 1, 2)`?
<details><summary>▶ Answer</summary>
`(2, 4, 3)` — axis 1 (size 3) and axis 2 (size 4) trade places; axis 0 is untouched.
</details>

**Q6.** If you call `arr.resize((6,))` on a 3-element array, what fills the 3 new slots?
<details><summary>▶ Answer</summary>
Zeros — the in-place <code>.resize()</code> method pads growth with 0, unlike <code>np.resize()</code> which repeats the data.
</details>

---

### 🔴 Advanced

**Q7.** For a `(2, 3, 4)` array, `np.moveaxis(arr, 0, 2)` produces what shape, and why?
<details><summary>▶ Answer</summary>
`(3, 4, 2)` — axis 0 (size 2) is removed from the front and reinserted at position 2 (the end); the remaining axes (3 and 4) shift left to fill the gap, keeping their relative order.
</details>

**Q8.** Why would a deep learning pipeline use `swapaxes()` or `moveaxis()` instead of `reshape()` when converting `Height × Width × Channels` to `Channels × Height × Width`?
<details><summary>▶ Answer</summary>
Because the goal is to reorder existing axes without changing which values belong together spatially. `reshape()` would reinterpret the flat memory layout and scramble pixel/channel relationships; `swapaxes()`/`moveaxis()` correctly permute axes while preserving the data's meaning.
</details>

**Q9.** What happens if you call `np.resize(arr, (3,3))` on a `(2,2)` array `[[1,2],[3,4]]`?
<details><summary>▶ Answer</summary>
It returns a new `(3,3)` array where the 4 original values are repeated in row-major order to fill all 9 slots: `[[1,2,3],[4,1,2],[3,4,1]]`.
</details>

<a id="practice-questions"></a>

## 📝 Practice Questions

*(Try solving each question before running any code.)*

---

### 🟢 Easy

1. Create a `(2, 3, 4)` array and swap axis 0 with axis 1. Print the resulting shape.
2. Use `moveaxis()` to move the last axis of a `(2,3,4)` array to the front. Print the resulting shape.
3. Create a 1D array of 4 elements and use `.resize((8,))` to grow it in place.
4. Use `np.resize()` (the function) on a 3-element array to produce a 9-element array. Explain the pattern in the output.

### 🟡 Medium

5. Given a `(3, 4, 5)` array, write the `swapaxes()` call that produces shape `(5, 4, 3)`.
6. Given a `(3, 4, 5)` array, write the `moveaxis()` call that moves axis 2 to axis 0, producing shape `(5, 3, 4)`.
7. Explain, without running code, whether `arr.resize((2,2))` on a 6-element array will succeed or raise an error, then verify.
8. Compare `np.swapaxes(arr, 0, 2)` and `np.moveaxis(arr, 0, 2)` on the same `(2,3,4)` array — are the resulting shapes the same? Are the resulting values the same?

### 🔴 Hard

9. Given an image batch of shape `(N, H, W, C)` (channels-last), write the single call that converts it to `(N, C, H, W)` (channels-first) using only `moveaxis()`.
10. Given a `(2,2)` array `[[1,2],[3,4]]`, predict the exact output of `np.resize(arr, (3,3))` before running it.
11. Write code demonstrating that `swapaxes()` never changes the total number of elements, while `resize()` can.
12. Given a `(4,3,2)` array, find two different combinations of `moveaxis()` and/or `swapaxes()` calls that both produce shape `(2,4,3)`, and explain whether the resulting data layout is identical.

<a id="mini-challenge"></a>

## 🏆 Mini Challenge — Channel Format Converter

You're converting an image batch between channels-last and channels-first formats — a real preprocessing step for many deep learning frameworks.

**Complete all 5 steps:**

1. **Create** a `(8, 32, 32, 3)` array with `np.arange(8*32*32*3).reshape(8,32,32,3)` representing 8 RGB 32×32 images (channels-last: `N,H,W,C`).
2. **Convert** it to channels-first format `(8, 3, 32, 32)` using `moveaxis()`.
3. **Convert** it back to channels-last using `moveaxis()` again, and confirm the shape matches the original.
4. **Grow** a small 1D array of 5 elements to 10 elements using both `arr.resize()` and `np.resize()` — compare the two outputs.
5. **Swap** the height and width axes of a single `(32, 32, 3)` image using `swapaxes()` and confirm the shape stays `(32, 32, 3)` (square images) while the data is transposed.

*(Solutions intentionally omitted — this is a self-check exercise.)*

<a id="references"></a>

## 📚 References

### Official Documentation

- 📖 [numpy.swapaxes](https://numpy.org/doc/stable/reference/generated/numpy.swapaxes.html)
- 📖 [numpy.moveaxis](https://numpy.org/doc/stable/reference/generated/numpy.moveaxis.html)
- 📖 [numpy.resize](https://numpy.org/doc/stable/reference/generated/numpy.resize.html)
- 📖 [numpy.ndarray.resize](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.resize.html)

### Recommended Reading

- 📘 *Python for Data Analysis* — Wes McKinney
- 📘 *Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow* — Aurélien Géron

### Useful Resources

- 🔗 [NumPy Cheat Sheet (DataCamp)](https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python)

---

<div style="background: linear-gradient(135deg, #1a237e 0%, #01579b 100%); padding: 24px; border-radius: 10px; text-align:center; color:white; font-family:'Segoe UI',sans-serif;">
<b>Thanks for reading!</b> ⭐ Star the repo if this helped — feedback and PRs welcome.
</div>