<div style="background: linear-gradient(135deg, #1a237e 0%, #0d47a1 50%, #01579b 100%); padding: 48px 40px; border-radius: 12px; color: white; font-family: 'Segoe UI', sans-serif; text-align: center;">

<h1 style="font-size: 2.6em; font-weight: 800; margin: 0 0 8px 0; letter-spacing: 1px;">📘 NumPy Broadcasting</h1>
<p style="font-size: 1.2em; margin: 0 0 32px 0; opacity: 0.85;">Operating on different-shaped arrays without writing a single loop</p>

<hr style="border: 1px solid rgba(255,255,255,0.3); margin-bottom: 28px;">

<table style="margin: 0 auto; border-collapse: collapse; color: white; font-size: 0.95em;">
<tr>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Author</b>
  Harsh Thakur
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">GitHub</b>
  <a href="https://github.com/HarshAIWorks" style="color:#90CAF9;">HarshAIWorks</a>
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topic</b>
  Broadcasting
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Difficulty</b>
  Beginner → Intermediate
</td>
<td style="padding: 8px 28px;">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topics</b>
  Core Concept
</td>
</tr>
</table>
</div>

## 📑 Table of Contents

| # | Section |
|---|---------|
| 1 | [Why Broadcasting Matters](#fn-1) |
| 2 | [The Two Broadcasting Rules](#fn-2) |
| 3 | [Walking Through an Example](#fn-3) |
| 4 | [More Broadcasting Examples](#fn-4) |
| 5 | [When Broadcasting Fails](#fn-5) |
| 6 | [Scalar & 2D Broadcasting](#fn-6) |
| 7 | [🎤 Interview Questions](#interview-questions) |
| 8 | [📝 Practice Questions](#practice-questions) |
| 9 | [🏆 Mini Challenge](#mini-challenge) |
| 10 | [📌 Summary](#summary) |
| 11 | [📚 References](#references) |

<a id="fn-1"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">1</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">Why Broadcasting Matters</code>
</div>

**Broadcasting** is NumPy's ability to perform operations on arrays of *different* shapes by automatically "stretching" the smaller one to match the larger one — without ever writing a loop.

> Broadcasting doesn't actually copy data. NumPy only **acts as if** the smaller array has been expanded — think of it as *"NumPy stretches the smaller array to match the bigger array, virtually."*

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Without Broadcasting</span></div>

Without it, adding 10 to every element of a 2D array would take an explicit double loop:

In [ ]:
for i in range(rows):
    for j in range(cols):
        result[i][j] = arr[i][j] + 10

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ With Broadcasting</span></div>

The same result, one line, no loop:

```python
arr + 10
```

<div style="border:2px solid #8B5CF6; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#7C3AED; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">🤖</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">AI Insight</span></div>
<div style="background:#F5F3FF; padding:14px 18px; color:#3B0764; font-size:0.97em; line-height:1.6;">
Broadcasting is what lets you add a bias vector to every row of a weight matrix, or normalize an entire image batch by one mean/std pair — all without a single explicit loop.
</div>
</div>

<a id="fn-2"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">2</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">The Two Broadcasting Rules</code>
</div>

**Rule 1 — Equalize the number of dimensions.**
If the two arrays don't have the same number of dimensions, NumPy pads new size-1 dimensions onto the *head* (left side) of the smaller array's shape.

**Rule 2 — Equalize each dimension's size.**
For every dimension, if the sizes don't match, a dimension of size 1 is *stretched* to match the other array. If neither side is 1 and the sizes differ, broadcasting is impossible and NumPy raises an error.

<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">

In short: the smaller array is "broadcast" across the larger one so both end up with compatible shapes.

<a id="fn-3"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">3</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">Walking Through an Example</code>
</div>

In [ ]:
# diff shape
import numpy as np
arr1 = np.arange(6).reshape(2,3)
arr2 = np.arange(3).reshape(3)
print(arr1,arr1.ndim)
print(arr2, arr2.ndim)


[[0 1 2]
 [3 4 5]] 2
[0 1 2] 1


**Step 1 — Match the number of dimensions.**
`arr1` is `(2,3)` (2D). `arr2` is `(3,)` (1D). Pad a `1` onto the head of the smaller shape: `(3,) → (1,3)`.

**Step 2 — Stretch any size-1 dimensions.**
Now compare `(2,3)` vs `(1,3)` — the `1` in `arr2`'s first axis stretches to `2`, so both become `(2,3)`.

```
arr2 before: [0 1 2]              shape (3,)
arr2 after:  [[0 1 2]             shape (2,3) — the row is repeated
              [0 1 2]]

arr1:        [[0 1 2]
              [3 4 5]]

arr1 + arr2: [[0 2 4]
              [3 5 7]]
```

In [ ]:
arr1 + arr2

array([[0, 2, 4],
       [3, 5, 7]])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ One More Walkthrough</span></div>

In [ ]:
# More examples

a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a, a.shape, sep=" " )
print()
print(b, b.shape, sep="  ")

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] (4, 3)

[0 1 2]  (3,)


```
a shape: (4,3)         b shape: (3,)  →  pad head → (1,3)  →  stretch → (4,3)

a = [[0 1 2]        b (stretched) = [[0 1 2]
     [3 4 5]                         [0 1 2]
     [6 7 8]                         [0 1 2]
     [9 10 11]]                      [0 1 2]]

a + b = [[0  2  4]
         [3  5  7]
         [6  8 10]
         [9 11 13]]
```

In [ ]:
a+b

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

<a id="fn-4"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">4</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">More Broadcasting Examples</code>
</div>

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 1 — Incompatible Shapes</span></div>

In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)

print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


`a` is `(3,4)`. `b` is `(3,)` → pad head → `(1,3)` → stretch → `(4,3)`.

Same number of dimensions now, but the shapes themselves — `(3,4)` vs `(4,3)` — don't match, so **broadcasting is not possible** here.

In [ ]:
a+b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 2 — Two Arrays That Both Need Stretching</span></div>

In [ ]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)



[[0 1 2]]
[[0]
 [1]
 [2]]


Both arrays are already 2D, so skip straight to Rule 2. Both have a `1` somewhere in their shape:

- `a`: `(1,3)` → stretch axis 0 → `(3,3)`
- `b`: `(3,1)` → stretch axis 1 → `(3,3)`

Once both reach `(3,3)`, the addition works — this is how a row vector and a column vector combine to build a full grid.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Try It Yourself</span></div>

In [ ]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)



[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]


In [ ]:
a = np.array([1])
# shape -> (1,1)
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print(b)


[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">💡</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Tip</span></div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
Work out the resulting shape on paper *before* running the cell above — that's the fastest way to build broadcasting intuition.
</div>
</div>

<a id="fn-5"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">5</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">When Broadcasting Fails</code>
</div>

If neither array has a `1` in a mismatched dimension, NumPy has no way to reconcile the shapes — it raises a `ValueError` instead of guessing.

In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [ ]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Common Mistake</span></div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
A `ValueError: operands could not be broadcast together` almost always means one of the trailing dimensions differs and neither side is 1. Print both shapes first — don't guess.
</div>
</div>

<a id="fn-6"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">6</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">Scalar & 2D Broadcasting</code>
</div>

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Example 1 — Scalar Broadcasting</span></div>

In [ ]:
import numpy as np
arr= np.arange(10,40,10)
print(arr)
arr.shape

[10 20 30]


(3,)

<div style="margin:10px 0 4px 0; font-family:'Segoe UI',sans-serif;"><span style="color:#64748B; font-weight:600; font-size:0.88em; font-style:italic;">— Sum</span></div>

In [ ]:
result= arr + 5
print(arr)
print(result)

[10 20 30]
[15 25 35]


<div style="margin:10px 0 4px 0; font-family:'Segoe UI',sans-serif;"><span style="color:#64748B; font-weight:600; font-size:0.88em; font-style:italic;">— Shape of the sum</span></div>

In [ ]:

print('shape of arr: ',arr.shape)
print('shape of 5: () ')
print("shape of arr+5:" ,result.shape )

shape of arr:  (3,)
shape of 5: () 
shape of arr+5: (3,)


```
arr:            [10 20 30]
scalar:          5

NumPy pretends the scalar is: [5 5 5]
Then computes:  [10+5  20+5  30+5]
Result:          [15 25 35]
```

A plain scalar has "shape" `()` — it broadcasts against *any* shape with zero cost, since NumPy never actually builds `[5,5,5]` in memory.

In [ ]:
arr=np.arange(1,7).reshape(2,3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr +5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

<a id="interview-questions"></a>

## 🎤 Interview Questions

---

### 🟢 Beginner

**Q1.** In one sentence, what is broadcasting?
<details><summary>▶ Answer</summary>
It's NumPy's mechanism for performing element-wise operations on arrays of different shapes by virtually stretching the smaller array to match the larger one, without copying data.
</details>

**Q2.** Does broadcasting create a new, larger copy of the smaller array in memory?
<details><summary>▶ Answer</summary>
No — NumPy only <i>behaves</i> as if the smaller array were expanded. This is what makes broadcasting memory-efficient.
</details>

**Q3.** What shape does a plain Python scalar (like `5`) have for broadcasting purposes?
<details><summary>▶ Answer</summary>
`()` — an empty shape. It broadcasts against any array shape with no restrictions.
</details>

---

### 🟡 Intermediate

**Q4.** An array of shape `(3,)` is being combined with an array of shape `(4,3)`. What's the first thing NumPy does?
<details><summary>▶ Answer</summary>
It pads a `1` onto the head of the smaller shape, turning `(3,)` into `(1,3)`, so both arrays have the same number of dimensions (Rule 1) before checking sizes (Rule 2).
</details>

**Q5.** Arrays of shape `(1,3)` and `(3,1)` are added together. What is the resulting shape?
<details><summary>▶ Answer</summary>
`(3,3)` — the size-1 axis in each array stretches to match the other array's size in that position.
</details>

**Q6.** Why does adding arrays of shape `(3,4)` and `(4,3)` raise an error even though both are 2D?
<details><summary>▶ Answer</summary>
Rule 1 is already satisfied (both have 2 dimensions), but Rule 2 fails: comparing `(3,4)` to `(4,3)` axis by axis, neither `3` vs `4` pair is a `1`, so the mismatched sizes cannot be reconciled.
</details>

---

### 🔴 Advanced

**Q7.** Given shapes `(8, 1, 6, 1)` and `(7, 1, 5)`, what is the resulting broadcast shape?
<details><summary>▶ Answer</summary>
`(8, 7, 6, 5)`. Pad `(7,1,5)` → `(1,7,1,5)`, then compare axis by axis from the right: `1&5`→5, `6&1`→6, `1&7`→7, `8&1`→8.
</details>

**Q8.** Why is broadcasting generally faster than an equivalent explicit Python loop?
<details><summary>▶ Answer</summary>
The actual iteration happens in optimized, compiled C code inside NumPy rather than the Python interpreter, and no intermediate expanded array is ever materialized — avoiding both interpreter overhead and extra memory allocation.
</details>

**Q9.** Can you broadcast a `(3,4)` array with a `(3,)` array directly (without reshaping)? Why or why not?
<details><summary>▶ Answer</summary>
No — `(3,)` pads to `(1,3)`, which conflicts with `(3,4)`'s last axis (`3` vs `4`, neither is 1). You'd need to reshape it to `(3,1)` first so it aligns with the first axis instead.
</details>

<a id="practice-questions"></a>

## 📝 Practice Questions

*(Try solving each question before running any code.)*

---

### 🟢 Easy

1. Create a `(4,)` array and add the scalar `100` to it. Print the result.
2. Create a `(2,3)` array and a `(3,)` array. Add them and print the resulting shape.
3. Predict the resulting shape of `(5,1) + (1,5)` before running it, then verify.
4. Multiply a `(3,3)` array by the scalar `2` and confirm every element doubled.

### 🟡 Medium

5. Given a `(4,3)` array representing 4 samples with 3 features, subtract a `(3,)` array of per-feature means to center the data.
6. Create a `(1,4)` array and a `(4,1)` array. Add them and explain, step by step, how NumPy arrives at the `(4,4)` result.
7. Try adding arrays of shape `(2,3)` and `(2,4)`. Predict whether it raises an error, then verify and explain why.
8. Given a `(10,)` array, reshape it to `(10,1)` and add it to a `(1,10)` array — describe the resulting grid.

### 🔴 Hard

9. Given shapes `(6,1,4,1)` and `(5,4,1)`, work out the broadcast result shape by hand, then verify with actual arrays.
10. Explain why `(3,4) + (4,)` works, but `(4,3) + (4,)` does not, without running any code — then verify both.
11. Write code that broadcasts a `(3,)` RGB scaling factor across a `(100,100,3)` image array to adjust each channel independently.
12. A batch of `N` samples each with `F` features is stored as `(N,F)`. Write the single broadcasting expression that standardizes every column (subtract per-column mean, divide by per-column std) without any loop.

<a id="mini-challenge"></a>

## 🏆 Mini Challenge — Feature Normalizer

You're preparing a small dataset for a model and need to normalize it using broadcasting only.

**Complete all 4 steps:**

1. **Create** a `(5,3)` array of random integers (0–100) representing 5 samples with 3 features: `np.random.randint(0, 100, (5,3))`.
2. **Compute** the per-column mean using `arr.mean(axis=0)` — note its shape is `(3,)`.
3. **Subtract** the mean from every row using broadcasting (no loop) to center the data.
4. **Divide** the centered data by `arr.std(axis=0)` (also shape `(3,)`) to complete a full standardization — confirm the result's shape stayed `(5,3)` throughout.

*(Solutions intentionally omitted — this is a self-check exercise.)*

<a id="summary"></a>

## 📌 Summary

- Broadcasting lets arrays of different shapes interact in element-wise operations **without copying data or writing loops**.
- **Rule 1:** pad the smaller shape with `1`s on the left until both arrays have the same number of dimensions.
- **Rule 2:** stretch any dimension of size `1` to match the other array; if neither side is `1` and the sizes differ, it fails.
- Scalars broadcast against anything — they have shape `()`.
- A `ValueError` on broadcasting almost always means: print both `.shape`s and compare from the right — a mismatch with neither side equal to `1` is the culprit.

**What's next:** Boolean masking and fancy indexing build directly on top of these shape rules — many of their conditions and index arrays broadcast exactly the same way.

<a id="references"></a>

## 📚 References

### Official Documentation

- 📖 [NumPy Broadcasting (User Guide)](https://numpy.org/doc/stable/user/basics.broadcasting.html)
- 📖 [numpy.broadcast](https://numpy.org/doc/stable/reference/generated/numpy.broadcast.html)

### Recommended Reading

- 📘 *Python Data Science Handbook* — Jake VanderPlas (source of the broadcasting figure above)
- 📘 *Python for Data Analysis* — Wes McKinney

### Useful Resources

- 🔗 [NumPy Cheat Sheet (DataCamp)](https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python)

---

<div style="background: linear-gradient(135deg, #1a237e 0%, #01579b 100%); padding: 24px; border-radius: 10px; text-align:center; color:white; font-family:'Segoe UI',sans-serif;">
<b>Thanks for reading!</b> ⭐ Star the repo if this helped — feedback and PRs welcome.
</div>