<div style="background: linear-gradient(135deg, #1a237e 0%, #0d47a1 50%, #01579b 100%); padding: 48px 40px; border-radius: 12px; color: white; font-family: 'Segoe UI', sans-serif; text-align: center;">

<h1 style="font-size: 2.6em; font-weight: 800; margin: 0 0 8px 0; letter-spacing: 1px;">📘 NumPy Boolean Masking</h1>
<p style="font-size: 1.2em; margin: 0 0 32px 0; opacity: 0.85;">Filtering and modifying arrays with True/False conditions</p>

<hr style="border: 1px solid rgba(255,255,255,0.3); margin-bottom: 28px;">

<table style="margin: 0 auto; border-collapse: collapse; color: white; font-size: 0.95em;">
<tr>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Author</b>
  Harsh Thakur
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">GitHub</b>
  <a href="https://github.com/HarshAIWorks" style="color:#90CAF9;">HarshAIWorks</a>
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topic</b>
  Boolean Masking
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Difficulty</b>
  Beginner → Intermediate
</td>
<td style="padding: 8px 28px;">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topics</b>
  Core Concept
</td>
</tr>
</table>
</div>

## 📑 Table of Contents

| # | Section |
|---|---------|
| 1 | [What Is a Boolean Mask?](#fn-1) |
| 2 | [Basic Comparisons](#fn-2) |
| 3 | [Combining Multiple Conditions](#fn-3) |
| 4 | [Masking 2D Arrays](#fn-4) |
| 5 | [Modifying Values With a Mask](#fn-5) |
| 6 | [Real AI Examples](#fn-6) |
| 7 | [🎤 Interview Questions](#interview-questions) |
| 8 | [📝 Practice Questions](#practice-questions) |
| 9 | [🏆 Mini Challenge](#mini-challenge) |
| 10 | [📌 Summary](#summary) |
| 11 | [📚 References](#references) |

<a id="fn-1"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">1</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">What Is a Boolean Mask?</code>
</div>

**Boolean masking** selects or modifies array elements using a `True`/`False` array — think of it as a filter you apply directly to the data.

In [ ]:
import numpy as np
scores = np.array([45, 80, 65, 90, 30])
scores > 60

array([False,  True,  True,  True, False])

This `True`/`False` array is the **mask** itself.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Applying the Mask</span></div>

In [ ]:
scores[scores > 60]

array([80, 65, 90])

Only the elements where the mask is `True` are returned.

<div style="border:2px solid #8B5CF6; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#7C3AED; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">🤖</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">AI Insight</span></div>
<div style="background:#F5F3FF; padding:14px 18px; color:#3B0764; font-size:0.97em; line-height:1.6;">
Almost every AI project starts with cleaning and filtering data: removing missing values, dropping outliers, keeping only certain classes, or filtering images. Boolean masking makes all of it a one-liner.
</div>
</div>

**Syntax:** `arr[condition]`

<a id="fn-2"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">2</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">Basic Comparisons</code>
</div>

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Greater Than</span></div>

In [ ]:
arr = np.array([10,20,30,40,50])
arr[arr > 25]

array([30, 40, 50])

```
10  20  30  40  50
❌  ❌  ✅  ✅  ✅
```

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Less Than</span></div>

In [ ]:
arr[arr < 30]

array([10, 20])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Equal To</span></div>

In [ ]:
arr[arr == 20]

array([20])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Not Equal</span></div>

In [ ]:
arr[arr != 20]

array([10, 30, 40, 50])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Even Numbers</span></div>

In [ ]:
arr[arr % 2 == 0]

array([10, 20, 30, 40, 50])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Odd Numbers</span></div>

In [ ]:
arr[arr % 2 != 0]

array([], dtype=int64)

<a id="fn-3"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">3</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">Combining Multiple Conditions</code>
</div>

<div style="margin:10px 0 4px 0; font-family:'Segoe UI',sans-serif;"><span style="color:#64748B; font-weight:600; font-size:0.88em; font-style:italic;">— AND ( & )</span></div>

In [ ]:
arr = np.array([5,10,15,20,25,30])
arr[(arr > 10) & (arr < 30)]

array([15, 20, 25])

```
5   10  15  20  25  30
❌  ❌  ✅  ✅  ✅  ❌
```

<div style="margin:10px 0 4px 0; font-family:'Segoe UI',sans-serif;"><span style="color:#64748B; font-weight:600; font-size:0.88em; font-style:italic;">— OR ( | )</span></div>

In [ ]:
arr[(arr < 10) | (arr > 20)]

array([ 5, 25, 30])

<div style="margin:10px 0 4px 0; font-family:'Segoe UI',sans-serif;"><span style="color:#64748B; font-weight:600; font-size:0.88em; font-style:italic;">— NOT ( ~ )</span></div>

In [ ]:
arr[~(arr > 20)]

array([ 5, 10, 15, 20])

<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Common Mistake</span></div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
Use <code>&</code>, <code>|</code>, <code>~</code> — not Python's <code>and</code>/<code>or</code>/<code>not</code> — for element-wise conditions, and wrap each comparison in parentheses: <code>(arr &gt; 10) &amp; (arr &lt; 30)</code>.
</div>
</div>

<a id="fn-4"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">4</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">Masking 2D Arrays</code>
</div>

In [ ]:
arr = np.array([
    [10,20,30],
    [40,50,60]
])

arr[arr > 30]

array([40, 50, 60])

```
10  20  30      ❌ ❌ ❌
40  50  60      ✅ ✅ ✅
        ↓
     [40 50 60]
```
Masking a 2D array always returns a **flat 1D array** of the matching values — the ```original shape is not preserved.```

<a id="fn-5"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">5</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">Modifying Values With a Mask</code>
</div>

Instead of just *selecting* values, you can assign directly to a masked slice to *change* them in place.

In [ ]:
arr = np.array([10,20,30,40,50])
arr[arr > 30] = 0
arr

array([10, 20, 30,  0,  0])

<a id="fn-6"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">6</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">Real AI Examples</code>
</div>

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Remove Invalid Ages</span></div>

In [ ]:
ages = np.array([15,22,-1,35,-5,40])
ages[ages >= 0]

array([15, 22, 35, 40])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Remove Low-Confidence Predictions</span></div>

In [ ]:
confidence = np.array([0.95,0.82,0.31,0.97,0.45])
confidence[confidence > 0.8]

array([0.95, 0.82, 0.97])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Replace Missing Values</span></div>

In [ ]:
arr[arr == -1] = 0

Useful whenever a sentinel value like `-1` represents missing data.

<a id="interview-questions"></a>

## 🎤 Interview Questions

---

### 🟢 Beginner

**Q1.** What does `arr > 25` return when `arr` is a NumPy array?
<details><summary>▶ Answer</summary>
A new array of the same shape, filled with `True`/`False` — a Boolean mask — not a filtered array yet.
</details>

**Q2.** What does `arr[arr > 25]` return?
<details><summary>▶ Answer</summary>
A new 1D array containing only the elements of `arr` where the corresponding mask value is `True`.
</details>

**Q3.** How do you assign a new value to every element greater than 30 in `arr`?
<details><summary>▶ Answer</summary>
`arr[arr > 30] = 0` — indexing with a Boolean mask on the left side of an assignment modifies those elements in place.
</details>

---

### 🟡 Intermediate

**Q4.** Why does `arr[(arr > 10) & (arr < 30)]` fail if you remove the parentheses around each comparison?
<details><summary>▶ Answer</summary>
Because of Python operator precedence, `&` binds tighter than `>`/`<`, so `arr > 10 & arr < 30` gets parsed incorrectly. Each comparison must be parenthesized.
</details>

**Q5.** What shape does `arr2d[arr2d > 30]` return, given `arr2d` is `(2,3)`?
<details><summary>▶ Answer</summary>
A flat 1D array — Boolean masking on a 2D array always collapses the result to 1D, since only the matching elements (in row-major order) are kept.
</details>

**Q6.** What's the difference between `arr[arr != -1]` and `arr[arr == -1] = 0`?
<details><summary>▶ Answer</summary>
The first *selects* (returns a new array of) all elements that aren't `-1`, leaving `arr` unchanged. The second *modifies* `arr` in place, replacing every `-1` with `0`.
</details>

---

### 🔴 Advanced

**Q7.** How would you use `~` to select everything *except* values greater than 20, and why does it work?
<details><summary>▶ Answer</summary>
`arr[~(arr > 20)]` — `~` is the element-wise Boolean NOT, flipping every `True` to `False` and vice versa in the mask before it's used to index.
</details>

**Q8.** Why is `arr[condition] = value` more efficient than looping with `if` and manual assignment?
<details><summary>▶ Answer</summary>
The comparison and the assignment both run as vectorized, compiled operations across the whole array at once, avoiding Python-level iteration entirely.
</details>

**Q9.** Given `predictions` and `confidence` arrays of the same shape, how would you keep only predictions with confidence above 0.8?
<details><summary>▶ Answer</summary>
`predictions[confidence > 0.8]` — the mask is computed from one array and applied to index into another, as long as their shapes match.
</details>

<a id="practice-questions"></a>

## 📝 Practice Questions

*(Try solving each question before running any code.)*

---

### 🟢 Easy

1. Create an array of 10 random integers (0–100) and select all values above 50.
2. From the same array, select all values divisible by 5.
3. Select all values that are *not* divisible by 5, using `~`.
4. Set every value below 20 to `0` using a Boolean mask assignment.

### 🟡 Medium

5. Given an array of exam scores, select scores that are either below 40 **or** above 90 (using `|`).
6. Given a `(3,3)` array, select all values greater than 5 **and** even, using `&`.
7. Given an array of temperatures with some `-999` sentinel values for missing readings, replace all `-999` with `np.nan`.
8. Given a `(4,4)` array, count how many elements are greater than the array's mean, without using a loop.

### 🔴 Hard

9. Given two same-shape arrays `predicted` and `actual`, compute the mask of where they disagree, then count the disagreements.
10. Given a `(100,)` array of pixel intensities, clip every value above 255 down to 255 using Boolean masking (not `np.clip()`).
11. Given a `(5,5)` grid, replace every value in the first column that's below the column's mean with the column's mean itself.
12. Write a one-liner that returns the *indices* (not the values) of all elements greater than 50 in a 1D array, using a Boolean mask combined with `np.nonzero()` or `np.where()`.

<a id="mini-challenge"></a>

## 🏆 Mini Challenge — Sensor Data Cleaner

You've received a batch of noisy sensor readings that need cleaning before analysis.

**Complete all 4 steps:**

1. **Create** a `(20,)` array with `np.random.randint(-10, 120, 20)` simulating sensor readings (valid range is 0–100; anything outside is noise).
2. **Flag** invalid readings — below 0 or above 100 — using a combined Boolean mask with `|`.
3. **Replace** every invalid reading with `np.nan` using mask assignment.
4. **Count** how many valid readings remain using `~np.isnan(arr)` combined with `.sum()`.

*(Solutions intentionally omitted — this is a self-check exercise.)*

<a id="summary"></a>

## 📌 Summary

- A Boolean mask is an array of `True`/`False` values, usually produced by a comparison like `arr > 25`.
- `arr[mask]` **selects** only the elements where the mask is `True`, always returning a flat 1D array.
- `arr[mask] = value` **modifies** those same elements in place — no loop required either way.
- Combine conditions with `&` (AND), `|` (OR), `~` (NOT) — always parenthesize each comparison.
- Boolean masking is the backbone of data cleaning: removing invalid values, filtering low-confidence predictions, and replacing sentinel/missing values.

| Operator | Meaning | Example |
|---|---|---|
| `&` | AND | `(arr > 10) & (arr < 30)` |
| `\|` | OR | `(arr < 10) \| (arr > 20)` |
| `~` | NOT | `~(arr > 20)` |

**What's next:** Fancy indexing extends this idea from conditions to explicit lists of indices — the two techniques are often combined in the same line of code.

<a id="references"></a>

## 📚 References

### Official Documentation

- 📖 [Boolean Array Indexing (NumPy User Guide)](https://numpy.org/doc/stable/user/basics.indexing.html#boolean-array-indexing)
- 📖 [numpy.where](https://numpy.org/doc/stable/reference/generated/numpy.where.html)

### Recommended Reading

- 📘 *Python for Data Analysis* — Wes McKinney
- 📘 *Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow* — Aurélien Géron

### Useful Resources

- 🔗 [NumPy Cheat Sheet (DataCamp)](https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python)

---

<div style="background: linear-gradient(135deg, #1a237e 0%, #01579b 100%); padding: 24px; border-radius: 10px; text-align:center; color:white; font-family:'Segoe UI',sans-serif;">
<b>Thanks for reading!</b> ⭐ Star the repo if this helped — feedback and PRs welcome.
</div>