<div style="background: linear-gradient(135deg, #1a237e 0%, #0d47a1 50%, #01579b 100%); padding: 48px 40px; border-radius: 12px; color: white; font-family: 'Segoe UI', sans-serif; text-align: center;">

<h1 style="font-size: 2.6em; font-weight: 800; margin: 0 0 8px 0; letter-spacing: 1px;">📘 NumPy Fancy Indexing</h1>
<p style="font-size: 1.2em; margin: 0 0 32px 0; opacity: 0.85;">Selecting and reordering elements with index arrays instead of slices</p>

<hr style="border: 1px solid rgba(255,255,255,0.3); margin-bottom: 28px;">

<table style="margin: 0 auto; border-collapse: collapse; color: white; font-size: 0.95em;">
<tr>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Author</b>
  Harsh Thakur
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">GitHub</b>
  <a href="https://github.com/HarshAIWorks" style="color:#90CAF9;">HarshAIWorks</a>
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topic</b>
  Fancy Indexing
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Difficulty</b>
  Beginner → Intermediate
</td>
<td style="padding: 8px 28px;">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topics</b>
  1D & 2D Selection
</td>
</tr>
</table>
</div>

## 📑 Table of Contents

| # | Section |
|---|---------|
| 1 | [What Is Fancy Indexing?](#fn-1) |
| 2 | [Fancy Indexing on 1D Arrays](#fn-2) |
| 3 | [Fancy Indexing on 2D Arrays](#fn-3) |
| 4 | [🎤 Interview Questions](#interview-questions) |
| 5 | [📝 Practice Questions](#practice-questions) |
| 6 | [🏆 Mini Challenge](#mini-challenge) |
| 7 | [📌 Summary](#summary) |
| 8 | [📚 References](#references) |

<a id="fn-1"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">1</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">What Is Fancy Indexing?</code>
</div>

**Fancy indexing** means selecting elements using a *list or array of indices*, instead of a contiguous slice — it lets you pick any elements, in any order.

| | |
|---|---|
| **Slicing** | `arr[1:4]` — consecutive elements only |
| **Fancy indexing** | `arr[[0, 3, 5]]` — any elements, any order |

<div style="border:2px solid #8B5CF6; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#7C3AED; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">🤖</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">AI Insight</span></div>
<div style="background:#F5F3FF; padding:14px 18px; color:#3B0764; font-size:0.97em; line-height:1.6;">
Say you only need students 2, 8, and 15 out of a class of 100 — slicing can't express that gap-filled selection, but `students[[2, 8, 15]]` does it in one line.
</div>
</div>

**Syntax:** `arr[[index1, index2, index3]]` or `arr[np.array([...])]`

<a id="fn-2"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">2</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">Fancy Indexing on 1D Arrays</code>
</div>

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Basic Selection</span></div>

In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
arr[[0,2,5]]

array([10, 30, 60])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Reordering Elements</span></div>

In [ ]:
arr[[5,4,3,2,1,0]]

array([60, 50, 40, 30, 20, 10])

Fancy indexing can also change the order — here it reverses the array by listing indices in reverse.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Duplicate Indices</span></div>

In [ ]:
arr[[1,1,3,3]] 

array([20, 20, 40, 40])

The same index can appear multiple times in the result.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Using a NumPy Array of Indices</span></div>

In [ ]:
indices = np.array([0,2,4])
arr[indices]

array([10, 30, 50])

<a id="fn-3"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">3</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">Fancy Indexing on 2D Arrays</code>
</div>

```
arr[[row, col], [row, col], ...]
         item1        item2
```

In [ ]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Select Rows</span></div>

In [ ]:
arr[[0,2]]

array([[10, 20, 30],
       [70, 80, 90]])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Reorder Rows</span></div>

In [ ]:
arr[[2,0,1]]

array([[70, 80, 90],
       [10, 20, 30],
       [40, 50, 60]])

Rows come back in exactly the order requested.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Select Specific Elements</span></div>

**Syntax:** `arr[[row,col],[row,col],...]` — the row and column index lists are paired **element by element**, not combined as a grid.

In [ ]:
arr[[0,2],[1,0]]

array([20, 70])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Select Columns</span></div>

In [ ]:
arr[:, [0,2]]

array([[10, 30],
       [40, 60],
       [70, 90]])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Select Rows and Columns Together</span></div>

`arr[[0,2]][:, [1,2]]` is a **two-step process**:

1. `arr[[0,2]]` — select rows 0 and 2, producing a new array
2. `[:, [1,2]]` — from *that* new array, select columns 1 and 2

It works like `row[cols]`, because the intermediate result is itself a plain array you can index again.

In [ ]:
print(arr)
arr[[0,2]][:, [1,2]]

[[10 20 30]
 [40 50 60]
 [70 80 90]]


array([[20, 30],
       [80, 90]])

<a id="interview-questions"></a>

## 🎤 Interview Questions

---

### 🟢 Beginner

**Q1.** What's the key difference between slicing and fancy indexing?
<details><summary>▶ Answer</summary>
Slicing (`arr[1:4]`) selects a contiguous range. Fancy indexing (`arr[[0,3,5]]`) selects arbitrary elements, in any order, including repeats.
</details>

**Q2.** Can fancy indexing return the same element more than once?
<details><summary>▶ Answer</summary>
Yes — `arr[[1,1,3,3]]` is valid and returns the values at index 1 and 3 twice each.
</details>

**Q3.** Does fancy indexing return a view or a copy of the original array?
<details><summary>▶ Answer</summary>
A copy. Unlike slicing (which returns a view), fancy indexing always returns a new array — modifying the result doesn't affect the original.
</details>

---

### 🟡 Intermediate

**Q4.** What does `arr[[2,0,1]]` do to a 2D array's rows?
<details><summary>▶ Answer</summary>
It returns a new array with row 2 first, then row 0, then row 1 — rows are reordered exactly as requested.
</details>

**Q5.** What does `arr[[0,2],[1,0]]` select from a 2D array — and what's a common misconception here?
<details><summary>▶ Answer</summary>
It selects two individual elements: `arr[0,1]` and `arr[2,0]` — the index lists are paired element-by-element, *not* combined into a 2×2 grid of every row/column combination (that misconception is a frequent bug source).
</details>

**Q6.** How do you select columns 0 and 2 from every row of a 2D array?
<details><summary>▶ Answer</summary>
`arr[:, [0,2]]` — a `:` for all rows, paired with a fancy index list for the columns.
</details>

---

### 🔴 Advanced

**Q7.** Why does `arr[[0,2]][:, [1,2]]` need two separate indexing steps instead of one?
<details><summary>▶ Answer</summary>
Because `arr[[0,2],[1,2]]` in a single step would pair the lists element-by-element (giving `arr[0,1]` and `arr[2,2]`), not select the full "rows 0,2 × columns 1,2" sub-grid. The two-step form first slices rows, then slices columns from that intermediate result.
</details>

**Q8.** If `indices = np.array([0,2,4])`, is `arr[indices]` functionally different from `arr[[0,2,4]]`?
<details><summary>▶ Answer</summary>
No — both are fancy indexing with the same effect. A Python list and a NumPy integer array of indices behave identically here.
</details>

**Q9.** Given a `(5,5)` array, how would you select the diagonal elements using fancy indexing?
<details><summary>▶ Answer</summary>
`arr[[0,1,2,3,4],[0,1,2,3,4]]` (or more generally `arr[np.arange(5), np.arange(5)]`) — pairing matching row/column indices selects exactly the diagonal.
</details>

<a id="practice-questions"></a>

## 📝 Practice Questions

*(Try solving each question before running any code.)*

---

### 🟢 Easy

1. Create a 1D array of 8 elements and select elements at indices 1, 3, and 6.
2. Reverse a 1D array of 6 elements using fancy indexing (not slicing).
3. Select the same element 3 times from a 1D array using duplicate indices.
4. Given a `(4,4)` array, select rows 0 and 3.

### 🟡 Medium

5. Given a `(4,4)` array, reorder its rows so row 3 comes first, then row 0, then row 1, then row 2.
6. Given a `(5,5)` array, select the diagonal elements using fancy indexing.
7. Given a `(4,4)` array, select columns 1 and 3 for every row.
8. Given a `(3,3)` array, select the elements at `(0,0)`, `(1,1)`, and `(2,2)` in one fancy-indexing call.

### 🔴 Hard

9. Given a `(6,6)` array, select the sub-grid formed by rows `[1,3,5]` and columns `[0,2,4]` (9 elements total) using the two-step pattern.
10. Given a `(5,)` array of student IDs and a `(5,)` array of scores, use fancy indexing to print the top-3 scoring students in descending order (hint: combine with `np.argsort()`).
11. Explain, without running code, why `arr[[0,2],[1,3]]` on a `(4,4)` array returns 2 elements, not 4 — then verify.
12. Given a `(10,10)` array, write fancy-indexing code that extracts every other row and every other column simultaneously (the resulting shape should be `(5,5)`).

<a id="mini-challenge"></a>

## 🏆 Mini Challenge — Leaderboard Extractor

You have exam results for 20 students and need to build a custom leaderboard view.

**Complete all 4 steps:**

1. **Create** a `(20,)` array of random scores with `np.random.randint(40, 100, 20)`.
2. **Find** the indices of the top 5 scores using `np.argsort(scores)[-5:]`.
3. **Extract** those 5 scores using fancy indexing, and print them in descending order.
4. **Given** a `(20,3)` array of `(id, score, class)` per student, use the same top-5 indices to fancy-index all 3 columns for those students at once.

*(Solutions intentionally omitted — this is a self-check exercise.)*

<a id="summary"></a>

## 📌 Summary

- Fancy indexing selects elements using a **list or array of indices**, not a contiguous range — unlike slicing, it always returns a **copy**.
- On a 1D array, `arr[[i1, i2, ...]]` picks (and can reorder or repeat) any elements you name.
- On a 2D array, `arr[rows]` selects whole rows; `arr[:, cols]` selects whole columns; `arr[rows, cols]` pairs the two lists **element-by-element** — it does not produce a full sub-grid.
- To select a sub-grid of specific rows *and* columns, index in two steps: `arr[rows][:, cols]`.

| Goal | Syntax |
|---|---|
| Select specific elements (1D) | `arr[[i1, i2, i3]]` |
| Select specific rows | `arr[[r1, r2]]` |
| Select specific columns | `arr[:, [c1, c2]]` |
| Select paired elements | `arr[[r1,r2], [c1,c2]]` |
| Select a row/column sub-grid | `arr[[r1,r2]][:, [c1,c2]]` |

**What's next:** `np.where()`, `np.argsort()`, and `np.unique()` (Searching & Sorting) frequently produce the index arrays that fancy indexing then consumes.

<a id="references"></a>

## 📚 References

### Official Documentation

- 📖 [Advanced (Fancy) Indexing — NumPy User Guide](https://numpy.org/doc/stable/user/basics.indexing.html#advanced-indexing)

### Recommended Reading

- 📘 *Python for Data Analysis* — Wes McKinney
- 📘 *Python Data Science Handbook* — Jake VanderPlas

### Useful Resources

- 🔗 [NumPy Cheat Sheet (DataCamp)](https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python)

---

<div style="background: linear-gradient(135deg, #1a237e 0%, #01579b 100%); padding: 24px; border-radius: 10px; text-align:center; color:white; font-family:'Segoe UI',sans-serif;">
<b>Thanks for reading!</b> ⭐ Star the repo if this helped — feedback and PRs welcome.
</div>