<div style="background: linear-gradient(135deg, #1a237e 0%, #0d47a1 50%, #01579b 100%); padding: 48px 40px; border-radius: 12px; color: white; font-family: 'Segoe UI', sans-serif; text-align: center;">

<h1 style="font-size: 2.6em; font-weight: 800; margin: 0 0 8px 0; letter-spacing: 1px;">📘 NumPy Searching & Sorting</h1>
<p style="font-size: 1.2em; margin: 0 0 32px 0; opacity: 0.85;">np.where() · np.argmax() · np.argmin() · np.sort() · np.argsort() · np.unique()</p>

<hr style="border: 1px solid rgba(255,255,255,0.3); margin-bottom: 28px;">

<table style="margin: 0 auto; border-collapse: collapse; color: white; font-size: 0.95em;">
<tr>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Author</b>
  Harsh Thakur
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">GitHub</b>
  <a href="https://github.com/HarshAIWorks" style="color:#90CAF9;">HarshAIWorks</a>
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topic</b>
  Searching & Sorting
</td>
<td style="padding: 8px 28px; border-right: 1px solid rgba(255,255,255,0.3);">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Difficulty</b>
  Beginner → Intermediate
</td>
<td style="padding: 8px 28px;">
  <b style="font-size:0.8em; opacity:0.7; display:block; text-transform:uppercase;">Topics</b>
  6 Functions
</td>
</tr>
</table>
</div>

## 📑 Table of Contents

| # | Section |
|---|---------|
| 1 | [np.where()](#fn-1) |
| 2 | [np.argmax()](#fn-2) |
| 3 | [np.argmin()](#fn-3) |
| 4 | [np.sort()](#fn-4) |
| 5 | [np.argsort()](#fn-5) |
| 6 | [np.unique()](#fn-6) |
| 7 | [🎤 Interview Questions](#interview-questions) |
| 8 | [📝 Practice Questions](#practice-questions) |
| 9 | [🏆 Mini Challenge](#mini-challenge) |
| 10 | [📌 Summary](#summary) |
| 11 | [📚 References](#references) |

<a id="fn-1"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">1</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">np.where() ⭐⭐⭐⭐⭐</code>
</div>

`np.where()` checks a condition and returns values based on whether it's `True` or `False` — think of it as a **vectorized if-else**.

**Syntax:** `np.where(condition, value_if_true, value_if_false)`

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Replace Negative Numbers</span></div>

In [ ]:
import numpy as np

arr = np.array([10, -5, 20, -8, 30])
result = np.where(arr < 0, 0, arr)
print(result)

[10  0 20  0 30]


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Pass / Fail</span></div>

In [ ]:
marks = np.array([45, 70, 35, 90, 55])
result= np.where(marks>40,"Pass","Fail")
print(result)

['Pass' 'Pass' 'Fail' 'Pass' 'Pass']


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Even / Odd</span></div>

In [ ]:
arr = np.arange(1,8)
np.where(arr % 2 == 0, "Even", "Odd")

array(['Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd'], dtype='<U4')

<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Common Mistake</span></div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
Forgetting all three arguments changes the meaning entirely: <code>np.where(arr &gt; 5)</code> does not replace values — it returns the <b>indices</b> where the condition is true.
</div>
</div>

In [ ]:
np.where(arr > 5)

(array([5, 6]),)

<a id="fn-2"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">2</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">np.argmax() ⭐⭐⭐⭐⭐</code>
</div>

`np.argmax()` returns the **index (position)** of the largest value in an array — not the value itself.

**Syntax:** `np.argmax(array, axis=None)` — `axis` controls which direction to search; the default searches the entire flattened array.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 1D Array</span></div>

In [ ]:
import numpy as np 
arr = np.array([15, 45, 20, 80, 60]) 
np.argmax(arr)

np.int64(3)

<div style="margin:10px 0 4px 0; font-family:'Segoe UI',sans-serif;"><span style="color:#64748B; font-weight:600; font-size:0.88em; font-style:italic;">— Get the actual maximum value</span></div>

In [ ]:
arr[np.argmax(arr)]

np.int64(80)

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 2D Array (Entire Array)</span></div>

In [ ]:
arr = np.array([ [10,20,30], [40,90,60] ]) 
np.argmax(arr)

np.int64(4)

For a full 2D array, `argmax()` always answers in the **flattened** index space:

```
Index : 0   1   2   3   4   5
Value : 10  20  30  40  90  60
```
Largest value is 90, at flattened position **4**.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Column-wise Maximum Index (axis=0)</span></div>

In [ ]:
arr = np.array([ [10,20,30], [40,90,60] ]) 
np.argmax(arr, axis=0)

array([1, 1, 1])

Each returned number is the **row index** of the maximum element in that column.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Row-wise Maximum Index (axis=1)</span></div>

In [ ]:
np.argmax(arr, axis=1)


array([2, 1])

<div style="border:2px solid #F59E0B; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#D97706; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">⚠️</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Common Mistakes</span></div>
<div style="background:#FFFBEB; padding:14px 18px; color:#78350F; font-size:0.97em; line-height:1.6;">
<b>Expecting the value, not the index:</b> if the max value is 80 at position 3, <code>argmax()</code> returns <code>3</code>, not <code>80</code>.<br><br><b>Forgetting the <code>axis</code> parameter:</b> without it, NumPy searches the entire flattened 2D array instead of per row/column.
</div>
</div>

<a id="fn-3"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">3</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">np.argmin() ⭐⭐⭐⭐⭐</code>
</div>

The mirror image of `argmax()` — returns the index of the **smallest** value, not the value itself.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 1D Array</span></div>

In [ ]:
import numpy as np 
arr =np.array([15, 45, 20, 80, 5]) 
np.argmin(arr)

np.int64(4)

<div style="margin:10px 0 4px 0; font-family:'Segoe UI',sans-serif;"><span style="color:#64748B; font-weight:600; font-size:0.88em; font-style:italic;">— Get the actual minimum value</span></div>

In [ ]:
arr[np.argmin(arr)]

np.int64(5)

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 2D Array (Entire Array)</span></div>

In [ ]:
arr = np.array([ [10,20,30], [40,5,60] ])
np.argmin(arr)

np.int64(4)

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Column-wise Minimum Index (axis=0)</span></div>

In [ ]:
arr = np.array([ [10,20,30], [40,5,60] ]) 
np.argmin(arr, axis=0)

array([0, 1, 0])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Row-wise Minimum Index (axis=1)</span></div>

In [ ]:
np.argmin(arr, axis=1)

array([0, 1])

<a id="fn-4"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">4</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">np.sort()</code>
</div>

`np.sort()` returns a **new sorted array** — it does not modify the original.

**Syntax:** `np.sort(array, axis=-1)` — the axis to sort along; default is `-1` (the last axis).

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Sort a 1D Array</span></div>

In [ ]:
import numpy as np 
arr = np.array([40, 10, 80, 20, 60]) 
sorted_arr = np.sort(arr) 
print(sorted_arr)

[10 20 40 60 80]


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Sort a 2D Array (Default)</span></div>

In [ ]:
arr = np.array([ [30,10,20], [90,50,70] ]) 
np.sort(arr)

array([[10, 20, 30],
       [50, 70, 90]])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Column-wise Sorting (axis=0)</span></div>

In [ ]:
np.sort(arr, axis=0)

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Row-wise Sorting (axis=1)</span></div>

In [ ]:
np.sort(arr, axis=1)

array([[10, 20, 30],
       [50, 70, 90]])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Descending Order</span></div>

In [ ]:
np.sort(arr)[::-1]

array([[50, 70, 90],
       [10, 20, 30]])

<div style="border:2px solid #2563EB; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#1D4ED8; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">💡</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">Tip</span></div>
<div style="background:#EFF6FF; padding:14px 18px; color:#1E3A5F; font-size:0.97em; line-height:1.6;">
NumPy has no direct "descending" flag — sort ascending, then reverse with <code>[::-1]</code>.
</div>
</div>

<a id="fn-5"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">5</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">np.argsort()</code>
</div>

`np.argsort()` returns the **indices** that would sort an array — not the sorted values themselves. Think of it as: *"tell me the order of indices that will sort this array."*

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 1D Array</span></div>

In [ ]:
import numpy as np 
arr = np.array([40,10,80,20]) 
np.argsort(arr)

array([1, 3, 0, 2])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Get Sorted Values Using argsort()</span></div>

In [ ]:
arr = np.array([40,10,80,20]) 
arr[np.argsort(arr)]

array([10, 20, 40, 80])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ 2D Array (axis=1)</span></div>

In [ ]:
arr = np.array([ [30,10,20], [90,50,70] ]) 
np.argsort(arr, axis=1)

array([[1, 2, 0],
       [1, 2, 0]])

Row-wise sorted indices — each row is sorted independently.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Top 3 Highest Values</span></div>

In [ ]:
scores = np.array([75,90,60,95,85]) 
top3 = np.argsort(scores)[-3:] 
print(top3)

[4 1 3]


<div style="border:2px solid #8B5CF6; border-radius:10px; margin:18px 0; overflow:hidden; font-family:'Segoe UI',sans-serif; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<div style="background:#7C3AED; padding:8px 16px; display:flex; align-items:center; gap:8px;"><span style="font-size:1.1em;">🤖</span><span style="color:#FFFFFF; font-weight:700; font-size:0.95em; letter-spacing:0.5px;">AI Insight</span></div>
<div style="background:#F5F3FF; padding:14px 18px; color:#3B0764; font-size:0.97em; line-height:1.6;">
<code>argsort()</code> is exactly how you build "top-K" results — sort the indices, then slice the last (or first) K and use them to fancy-index the original array.
</div>
</div>

<a id="fn-6"></a>

<div style="background:#1E2235; border-radius:10px; padding:16px 24px; margin:36px 0 18px 0; font-family:'Segoe UI',sans-serif; display:flex; align-items:center; gap:14px; border-left:5px solid #3D6FDB; box-shadow:0 4px 12px rgba(0,0,0,0.25);">
<span style="background:#2A2F47; color:#FFFFFF; font-weight:800; font-size:1.05em; padding:4px 12px; border-radius:6px;">6</span>
<code style="background:#2A2F47; color:#E8A84A; font-size:1.1em; font-weight:700; padding:5px 14px; border-radius:6px; font-family:'Courier New',monospace;">np.unique()</code>
</div>

`np.unique()` returns the unique (distinct) values from an array — it automatically removes duplicates and sorts the result in ascending order.

**Syntax:** `np.unique(array, return_counts=False)` — with `return_counts=True`, it also returns how many times each unique value appears.

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Find Unique Values</span></div>

In [ ]:
import numpy as np 
arr = np.array([1,2,2,3,1,4,4,5]) 
np.unique(arr)

array([1, 2, 3, 4, 5])

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Count Occurrences</span></div>

In [ ]:
arr = np.array([1,2,2,3,1,4,4,5]) 
values, counts = np.unique(arr, return_counts=True) 
print(values) 
print(counts)

[1 2 3 4 5]
[2 2 1 2 1]


<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ String Labels</span></div>

In [ ]:
labels = np.array([ "Cat", "Dog", "Cat", "Bird", "Dog" ]) 
np.unique(labels)

array(['Bird', 'Cat', 'Dog'], dtype='<U4')

<div style="background:#1E3A5F; border-radius:6px; padding:7px 14px; margin:16px 0 6px 0; display:inline-block; font-family:'Segoe UI',sans-serif;"><span style="color:#93C5FD; font-weight:700; font-size:0.97em;">▸ Real AI Example — Dataset Classes</span></div>

In [ ]:

y = np.array([
    "Spam",
    "Ham",
    "Spam",
    "Spam",
    "Ham"
])

np.unique(y)



array(['Ham', 'Spam'], dtype='<U4')

One call tells you the dataset contains exactly 2 classes — a routine first step before building any classifier.

<a id="interview-questions"></a>

## 🎤 Interview Questions

---

### 🟢 Beginner

**Q1.** What's the difference between `np.where(condition)` and `np.where(condition, a, b)`?
<details><summary>▶ Answer</summary>
With one argument, `np.where()` returns the indices where the condition is `True`. With three arguments, it returns an array of values picked from `a` (where `True`) or `b` (where `False`) — a vectorized if-else.
</details>

**Q2.** Does `np.argmax()` return a value or an index?
<details><summary>▶ Answer</summary>
An index (position) — to get the actual value, you must index back into the array: `arr[np.argmax(arr)]`.
</details>

**Q3.** Does `np.sort()` modify the original array?
<details><summary>▶ Answer</summary>
No — it always returns a new sorted array, leaving the original untouched.
</details>

---

### 🟡 Intermediate

**Q4.** For a 2D array, what does `np.argmax(arr)` (no axis) return, and why can that be confusing?
<details><summary>▶ Answer</summary>
It returns a single index into the array as if it were flattened to 1D, which can be confusing because that flat index doesn't directly tell you the row/column — you'd need `np.unravel_index()` to convert it back.
</details>

**Q5.** What does `np.argsort()` return, and how do you get the actual sorted values from it?
<details><summary>▶ Answer</summary>
It returns the indices that *would* sort the array. To get sorted values, fancy-index the original array with that result: `arr[np.argsort(arr)]`.
</details>

**Q6.** How would you sort an array in descending order, given NumPy has no built-in "descending" argument?
<details><summary>▶ Answer</summary>
Sort ascending first, then reverse: `np.sort(arr)[::-1]`.
</details>

---

### 🔴 Advanced

**Q7.** How do you find the top 3 highest values in an array using `argsort()`?
<details><summary>▶ Answer</summary>
`arr[np.argsort(arr)[-3:]]` — sort the indices ascending, take the last 3 (the largest), then fancy-index the array with them.
</details>

**Q8.** Given `values, counts = np.unique(arr, return_counts=True)`, how would you find the *most frequent* value?
<details><summary>▶ Answer</summary>
`values[np.argmax(counts)]` — `argmax()` on the counts array gives the position of the highest count, then index into `values` at that position.
</details>

**Q9.** Why might `np.argmax(arr, axis=0)` and `np.argmax(arr, axis=1)` give arrays of different lengths?
<details><summary>▶ Answer</summary>
`axis=0` returns one index per column (length = number of columns), finding the max down each column; `axis=1` returns one index per row (length = number of rows), finding the max across each row. For a non-square array these lengths differ.
</details>

<a id="practice-questions"></a>

## 📝 Practice Questions

*(Try solving each question before running any code.)*

---

### 🟢 Easy

1. Given an array of temperatures, use `np.where()` to replace every value below 0 with `0`.
2. Find the index and value of the largest element in a 1D array of 10 random integers.
3. Sort a 1D array of 8 random integers in ascending order, then in descending order.
4. Find the unique values in `[3,1,4,1,5,9,2,6,5,3]`.

### 🟡 Medium

5. Given a `(4,4)` array, find the row-wise index of the maximum value in each row.
6. Given an array of exam scores, use `np.where()` to label each as `"Pass"` or `"Fail"` based on a 40-point threshold.
7. Given an array of class labels, use `np.unique()` with `return_counts=True` to find which class appears most often.
8. Given a `(3,4)` array, sort each column independently (axis=0) and each row independently (axis=1) — compare the two results.

### 🔴 Hard

9. Given predicted probabilities `[0.2, 0.7, 0.05, 0.05]` for 4 classes, use `np.argmax()` to determine the predicted class index.
10. Given an array of 100 random scores, find the indices of the top 5 using `argsort()`, and confirm they match `np.sort(arr)[-5:]`'s values when fancy-indexed back.
11. Given two arrays `actual` and `predicted` of equal length, use `np.where()` to build a mask of correct predictions, then compute accuracy as a percentage.
12. Given a `(1000,)` array of pixel values (0–255), find the 3 most frequent values and their counts using `np.unique()` and `argsort()` together.

<a id="mini-challenge"></a>

## 🏆 Mini Challenge — Leaderboard Builder

You're building a simple leaderboard system from raw exam scores.

**Complete all 5 steps:**

1. **Create** a `(15,)` array of random scores with `np.random.randint(0, 100, 15)`.
2. **Label** each score `"Pass"` or `"Fail"` using `np.where()` with a 40-point cutoff.
3. **Rank** all students by finding the indices that sort the scores in descending order (hint: `np.argsort(scores)[::-1]`).
4. **Extract** the top 3 scores using those ranked indices.
5. **Count** how many distinct score values appear more than once using `np.unique(scores, return_counts=True)`.

*(Solutions intentionally omitted — this is a self-check exercise.)*

<a id="summary"></a>

## 📌 Summary

- **np.where(cond, a, b)** is a vectorized if-else; called with just a condition, it returns matching indices instead.
- **np.argmax() / np.argmin()** return the *position* of the largest/smallest value, not the value — index back into the array to get the value itself.
- **np.sort()** returns a new sorted array; **np.argsort()** returns the indices that *would* sort it — combine `argsort()` with fancy indexing for "top-K" queries.
- **np.unique()** removes duplicates and sorts the result; `return_counts=True` turns it into a quick frequency table.

### Function Quick Reference

| Function | Returns | Common Use |
|---|---|---|
| `np.where(cond, a, b)` | Values chosen per condition | Vectorized if-else |
| `np.argmax(arr, axis=None)` | Index of max | Predicted class from probabilities |
| `np.argmin(arr, axis=None)` | Index of min | Closest match / lowest error |
| `np.sort(arr, axis=-1)` | New sorted array | Ordering values |
| `np.argsort(arr, axis=-1)` | Indices that sort the array | Top-K, ranking |
| `np.unique(arr, return_counts=False)` | Distinct values (+ counts) | Class discovery, frequency tables |

**What's next:** These functions are the toolkit you reach for after Boolean masking and fancy indexing — searching, ranking, and deduplicating data are the natural next step once you can filter and select it.

<a id="references"></a>

## 📚 References

### Official Documentation

- 📖 [numpy.where](https://numpy.org/doc/stable/reference/generated/numpy.where.html)
- 📖 [numpy.argmax](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html)
- 📖 [numpy.argmin](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html)
- 📖 [numpy.sort](https://numpy.org/doc/stable/reference/generated/numpy.sort.html)
- 📖 [numpy.argsort](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html)
- 📖 [numpy.unique](https://numpy.org/doc/stable/reference/generated/numpy.unique.html)

### Recommended Reading

- 📘 *Python for Data Analysis* — Wes McKinney
- 📘 *Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow* — Aurélien Géron

### Useful Resources

- 🔗 [NumPy Cheat Sheet (DataCamp)](https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python)

---

<div style="background: linear-gradient(135deg, #1a237e 0%, #01579b 100%); padding: 24px; border-radius: 10px; text-align:center; color:white; font-family:'Segoe UI',sans-serif;">
<b>Thanks for reading!</b> ⭐ Star the repo if this helped — feedback and PRs welcome.
</div>